- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/v1x-release.yml
- .github/workflows/v2x-release.yml
Currently, `babel-plugin-transform-react-remove-prop-types` isn't being applied, making component `propTypes` always appear in the bundle (the same should be true for other productionPlugins)
This seems to be because these are production-only plugins (`process.env.NODE_ENV === "production"`), but production mode isn't being set anywhere.
This PR adds the `NODE_ENV="production"` to the publish workflows
> chore: add NODE_ENV=production to apply babel plugins

- packages/core/src/TagsInput/TagsInput.d.ts
- packages/core/src/TagsInput/TagsInput.js
- packages/core/src/TagsInput/stories/TagsInput.stories.js
- packages/core/src/TagsInput/styles.js
- update `onChange` signature
- update type definition to extend from `HvInputProps` instead of `HvBaseInputProps`
- Remove max-width limit on tags
- Add outline on focus
- Add error message and status validation
- Disable default behavior when enter is pressed to add a tag to prevent submiting a form where the component might be included 
- Added new story to illustrate usage of the component in a form
> fix(TagsInput): add status validation and other fixes

- .storybook/props/extractArgTypes.js
- Fixed missing props on the Properties table when a class with the same name exists. This was happening because we were creating an array with the prop or class name as id. This meant that when a CSS class with the same name as a property existed it would replace the property on the array therefore effectivelly eliminating the property from the array.
>  docs: fix props not showing on the Properties table

- packages/core/src/TagsInput/TagsInput.d.ts
- packages/core/src/TagsInput/TagsInput.js
- packages/core/src/TagsInput/stories/TagsInput.stories.js
- packages/core/src/TagsInput/tests/tagsInput.test.js
- new property `commitOnTag` allows passing an array of key codes that can be used to commit a tag
- new property `commitOnBlur` allows commiting a tag when clicking outside of the input box
> feat(TagsInput): allow commiting tags with other characters and on blur

- package-lock.json
- package.json
- packages/core/package.json
Allows an app to use `plotly.js` v1 or v2, which fixes #2710.
~Testing if internal bump to `plotly.js@2` breaks~. It seems like the [breaking changes](https://github.com/plotly/plotly.js/releases/tag/v2.0.0) ~might~do not affect UI-Kit's charts.
Does it make sense to make this bump in a patch/minor?
Looking forward, given:
- that plotly still relies heavily on `window.document`
- that plotly is a large library
- how often the charts are used
- that in Design System they're in a separate "visualisation" component library
it might be worth it to look into splitting the Visualisation components into a separate library
> chore: allow plotly.js@2

- packages/core/src/Barchart/barchartPlotlyOverrides.js
- packages/core/src/Chart/chartPlotlyOverrides.js
- packages/core/src/Donutchart/donutchartPlotlyOverrides.js
- packages/core/src/Linechart/lineChartPlotlyOverrides.js
I was trying to use the Linechart of ui-kit and came upon a problem. I want to force a showline: false , however the function setterIfNil  inside lineChartPlotlyOverrides and chartPlotlyOverrides is only checking for truthy values, since false  is not, it always defaults to true when applying the defaults.
I think you could swap the ||  with ??  to allow false and 0 in some cases.
> fix(chart): prevent chart defaults for some falsy values.

- packages/lab/src/QueryBuilder/RuleGroup/RuleGroup.js
- packages/lab/src/Slider/tests/slider.test.js
- Fixed the query builder allowing creating a new group when the `maxDepth` property is set to 0. This was caused by the level using base 0 indexing and the maxDepth using base 1 indexing (ie, when the maxDepth is 0 the current level is 1).
- Also fixed the tests for slider in lab throwing an error for an unexpected `console.warn`.
> fix(QueryBuilder): don't allow adding groups when maxDepth is 0

- packages/lab/src/QueryBuilder/Context.js
- packages/lab/src/QueryBuilder/Rule/Value/Value.js
- packages/lab/src/QueryBuilder/index.d.ts
- packages/lab/src/QueryBuilder/index.js
- packages/lab/src/QueryBuilder/stories/QueryBuilder.stories.js
- packages/lab/src/index.js
Allow adding custom `QueryBuilder` attribute types. For now, they will fallback to `TextValue`
> feat(querybuilder): allow custom attribute types

- .eslintrc.js
- packages/core/src/Focus/Focus.d.ts
- packages/core/src/index.d.ts
- packages/core/src/index.js
- packages/lab/src/Table/TableBody/TableBody.js
The `@hitachivantara/uikit-react-core/dist/Focus` is breaking my tests that include an `HvTable`.
```
FAIL  src/components/Wizard/FilterData/FilterData.test.tsx [ src/components/Wizard/FilterData/FilterData.test.tsx ]
FAIL  src/routes/Publications/Publications.test.tsx [ src/routes/Publications/Publications.test.tsx ]
FAIL  src/routes/PublicationsCreate/PublicationsCreate.test.tsx [ src/routes/PublicationsCreate/PublicationsCreate.test.tsx ]
FAIL  src/routes/PublicationsEdit/PublicationsEdit.test.tsx [ src/routes/PublicationsEdit/PublicationsEdit.test.tsx ]
FAIL  src/components/Wizard/Wizard.test.tsx [ src/components/Wizard/Wizard.test.tsx ]
FAIL  src/components/Wizard/EnterDetails/EnterDetails.test.tsx [ src/components/Wizard/EnterDetails/EnterDetails.test.tsx ]
FAIL …
```
> fix(table): fix `HvFocus` import

- packages/lab/src/QueryBuilder/Rule/Rule.js
- packages/lab/src/QueryBuilder/RuleGroup/RuleGroup.js
- packages/lab/src/QueryBuilder/types.d.ts
`HvQueryBuilder` behaves _strangely_ when no `id`s are passed to `Rule`, because of a `Math.random()` fallback on the `key`. These unstable `key` lead to different rules re-rendering updating when changing their values.
Demo: https://stackblitz.com/edit/uikit-querybuilder-key?file=src%2FApp.tsx
Video:
https://user-images.githubusercontent.com/638946/177589780-65fe197f-36b4-4e60-ad65-b88c0440f1ff.mov
> fix(querybuilder): stable `id`/`key`

- packages/themes/package.json
These exports point to non-existing files. `themes` only has a couple of `.json` and `.sass` files
> fix(themes): remove index exports

- packages/icons/package.json
The previous script would not work on windows.
It now should work on all machines.
> build: modify build icons scprit to run on windows

- .storybook/manager.js
- .storybook/preview.js
- .storybook/theme/styles/docs.js
After upgrading SB for latest version we got two problems:
1. The theme was not being properly set on the preview code block;
2. The `isToolShown` options was [deprecated](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#renamed-istoolshown-to-showtoolbar) and renamed to `showToolbar `;
> docs: fix storybook config

- packages/core/src/Login/Login.js
- packages/core/src/Slider/Slider.js
- packages/lab/src/Slider/Slider.js
Hello 👋 
Our team tried updating to UI-Kit's latest release, but `vitest` tests started breaking with:
```
SyntaxError: Unexpected token '.'
❯ Object.compileFunction node:vm:352:18
❯ Object.<anonymous> node_modules/@hitachivantara/uikit-react-core/dist/Slider/Slider.js:66:1
```
This seems to have happened because: 
- with the latest `package.json` `exports` changes, `vitest` is now pointing to `./dist/index.js` instead of `./dist/modern/index.js`
- leading to the whole package being imported (as opposed to only the components we use)
- which means `HvSlider` and `HvLogin` are imported
- which have direct imports to `.css` and `.svg` files
- which we don't have any special loaders to
The same error would happen if we tried to use `HvLogin` or `HvSlider` in our codebase.
These `.css` and …
> chore: make css/svg imports dynamic

- packages/lab/src/NotificationPanel/NotificationPanel.js
- packages/lab/src/TimeAgo/stories/TimeAgo.stories.js
This locale loading logic should live in the Apps' root configurations, not inside a UI Kit component.
This logic will be present in the apps anyways, and the dynamic import can mess up bundling and tree-shaking
@andrefrua @lumada-design/imperial please review.
PS: something's wrong with tagging @lumada-design/imperial as reviewer 🤔
> fix(NotificationPanel): remove locale logic app

- packages/icons/package-lock.json
- packages/icons/package.json
These dependencies are only used to build the icons, so they can be in `devDependencies`
> chore(icons): move build deps to devDeps

- packages/core/src/FilterGroup/RightPanel/RightPanel.js
If `HvFilterGroups`'s `filters` is `[]` the component crashes when opened, because it's assuming at least one element is present.
In our case, the filters come from the server, so there's a moment where we don't yet have filters
> fix(FilterGroup): crash if no filters are passed

- packages/core/src/FilterGroup/FilterGroup.d.ts
Added `Record<string, unknown>` for compatibility with the `object` that was there previously, so that `filterContentProps={{myUnknownKey: 123}}` doesn't error out
> test(FilterGroup): typings for `filterContentProps`

- packages/core/src/FilterGroup/FilterContent/FilterContent.d.ts
- packages/core/src/FilterGroup/FilterContent/FilterContent.js
- packages/core/src/FilterGroup/FilterContent/index.d.ts
- packages/core/src/FilterGroup/FilterGroup.d.ts
- packages/core/src/FilterGroup/LeftPanel/LeftPanel.js
- packages/core/src/FilterGroup/RightPanel/RightPanel.js
- packages/core/src/FilterGroup/stories/FilterGroup.stories.js
As of now, if there are no filters or a filter has empty data, we can't show the user any indicator (ie. `HvLoading`, `HvEmptyState`, etc.) to inform the user why
**Changes**
- add configurable `emptyElement` to `LeftPanel` and `RightPanel`
- add typings to `FilterContent`
Let me know what you think about the API!
> feat(FilterGroup): add configurable `emptyElement`

- packages/core/src/AssetInventory/ListView/ListViewCell/ListViewCell.d.ts
- packages/core/src/AssetInventory/ListView/ListViewRow/ListViewRow.d.ts
- packages/lab/src/Tag/Tag.d.ts
There's a mismatch between the existing palette colours and variant props (eg. missing `sema20`). Also reduces duplication
> chore: align color props

- packages/core/src/Banner/BannerContent/BannerContent.d.ts
Variant is wrongly assuming MUI variant instead of UI-Kit's
> chore(BannerContent): variant typings

- packages/core/src/Tag/Tag.js
- packages/core/src/Tag/stories/Tag.stories.js
- packages/core/src/Tag/styles.js
`HvTag` has a default max size, but if the `label` is long enough it doesn't overflow correctly.
MUI's `Chip` already takes care of this issue (overflowing), but since the user-provided string `label` is wrapped in an `HvTypography`, it essentially overrides the fix.
**Actual (left) vs Expected (right):**
This PR
- fixes the overflow issue by removing the `HvTypography` that _breaks_ `Chip` overflow fix.
- simplifies Long Label sample by leveraging `HvOverflowTooltip`
> fix(Tag): add ellipsis on overflow

- packages/lab/src/StepNavigation/StepNavigation.d.ts
The `separatorClassName` and `titleClassName` should be optional and inside each "step", not alongside the Array
> fix(StepNavigation): `steps` ts declaration

- packages/core/src/SimpleGrid/SimpleGrid.d.ts
- packages/core/src/SimpleGrid/SimpleGrid.js
- packages/core/src/SimpleGrid/stories/SimpleGrid.stories.js
Fixes `SimpleGrid`'s typings (`spacing` and `children` mismatch with PropTypes) and docs (invisible in `wicked`)
> fix(SimpleGrid): typings & docs

- packages/core/src/Dialog/Dialog.d.ts
- packages/core/src/Dialog/Dialog.js
- packages/core/src/Dialog/DialogActions/DialogActions.js
- packages/core/src/Dialog/DialogActions/styles.js
- packages/core/src/Dialog/DialogContent/DialogContent.js
- packages/core/src/Dialog/DialogContent/styles.js
- packages/core/src/Dialog/DialogTitle/DialogTitle.js
- packages/core/src/Dialog/DialogTitle/styles.js
- packages/core/src/Dialog/stories/Dialog.stories.js
- packages/core/src/Dialog/stories/Dialog.stories.test.js
- packages/core/src/Dialog/styles.js
- packages/lab/package-lock.json
- packages/viz/package-lock.json
The current `HvDialog` has a strict `100px` top and bottom "margin" that, along with the `75px+` of `HvDialogTitle` and `HvDialogActions`, leaves little "room" for `HvDialogContent`. 
For an `HvDialogContent` that needs to be at least `300px` in height, `HvDialog` starts becoming unusable in a HD display height `768p` or `1080p` scaled to HD "resolution".
Furthermore, (unrelated to the point above) a Dialog that needs to be full-height has an odd behaviour by default. When applying `height: 100%` to it, `HvDialogTitle` and `HvDialogActions` grow as much as possible, while `HvDialogContent` stays as small as possible 🤷 
This PR:
- Adds a vertical breakpoint that removes the `200px` margin on smaller screens (`sm`)
- Fixes `HvDialogTitle` and `HvDialogActions` growing, instead of …
> fix(dialog): height & fullscreen styles

- packages/core/src/DatePicker/DatePicker.d.ts
- packages/core/src/DatePicker/DatePicker.js
- packages/core/src/DatePicker/stories/Datepicker.stories.js
Expose `HvCalendar` props via `calendarProps` prop, to allow configuration of `minimumDate`, `maximumDate`, and others
> feat(DatePicker): expose `HvCalendar` props

- packages/core/package-lock.json
- packages/core/package.json
- packages/lab/package-lock.json
- packages/lab/package.json
`core-js@3` is missing from `core`/`lab` packages.
The bundles will fail with multiple errors, such as ([demo](https://stackblitz.com/edit/uikit-no-corejs?file=package.json)):
```
✘ [ERROR] Could not resolve "core-js/modules/es.array.from.js"
node_modules/@hitachivantara/uikit-react-core/dist/legacy/Slider/utils.js:20:7:
20 │ import "core-js/modules/es.array.from.js";
```
> fix(deps): add missing core-js to core/lab

- packages/core/src/components/Button/Button.styles.ts
- packages/core/src/components/Button/Button.tsx
- removed the `focusVisibleClassName` prop since that was specific of the MUI button (which is not being used here anymore)
- added `onFocus` and `onBlur` event handlers to add and remove the specific class for when the button in focused
- adjust the styles
> fix(Button): fix button focus

- packages/core/src/components/Tab/Tab.styles.tsx
- packages/core/src/components/Tab/Tab.test.tsx
- packages/core/src/components/Tab/Tab.tsx
- packages/core/src/components/Tab/__snapshots__/Tab.test.tsx.snap
- packages/core/src/components/Tab/index.tsx
- packages/core/src/components/index.ts
- packages/styles/src/theme.ts
- packages/styles/src/themes/ds3Theme.ts
- packages/styles/src/themes/ds5Theme.ts
- I removed `labelContainer` from the classes since it was not being used (https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/Tab/Tab.js#L48).
> feat(Tab): add Tab component

- packages/core/src/components/Panel/Panel.stories.tsx
- packages/core/src/components/Panel/Panel.styles.tsx
- packages/core/src/components/Panel/Panel.test.tsx
- packages/core/src/components/Panel/Panel.tsx
- packages/core/src/components/Panel/__snapshots__/Panel.test.tsx.snap
- packages/core/src/components/Panel/index.ts
- packages/core/src/components/index.ts
In the previous component it was possible to add certain styles directly like so: `<HvPanel width="100%" height="200px" boxShadow={theme.hv.shadows[1]}>`
In this version the styles are added with a style object like so: 
` <HvPanel style={{ width: "100%", height: "200px", boxShadow: theme.shadows.sm,  }}>`
I don't know if it is worth it to add those style props.
> feat(panel): add panel component

- app/src/App.tsx
- app/src/components/BaseDropdown/BaseDropdown.tsx
- app/src/components/BaseDropdown/index.ts
- app/src/components/index.ts
- packages/core/package.json
- packages/core/src/components/BaseCheckBox/BaseCheckBox.styles.ts
- packages/core/src/components/BaseCheckBox/__snapshots__/BaseCheckBox.test.tsx.snap
- packages/core/src/components/BaseDropdown/BaseDropdown.styles.tsx
- packages/core/src/components/BaseDropdown/BaseDropdown.test.tsx
- packages/core/src/components/BaseDropdown/BaseDropdown.tsx
- packages/core/src/components/BaseDropdown/BaseDropdownContext/BaseDropdownContext.tsx
- packages/core/src/components/BaseDropdown/BaseDropdownContext/index.ts
- packages/core/src/components/BaseDropdown/__snapshots__/BaseDropdown.test.tsx.snap
- packages/core/src/components/BaseDropdown/index.ts
- packages/core/src/components/ListContainer/__snapshots__/ListContainer.test.tsx.snap
- packages/core/src/components/SelectionList/__snapshots__/SelectionList.test.tsx.snap
- packages/core/src/components/index.ts
- packages/styles/src/theme.ts
- packages/styles/src/themes/ds3Theme.ts
- packages/styles/src/themes/ds5Theme.ts
- pnpm-lock.yaml
The `BaseDropdown` component needed the following dependencies: `react-popper`, `react-max-size-modifier`, and `@popperjs/core`. However, `react-max-size-modifier` is currently deprecated, and the maintainer recommends switching to Floating UI. Since switching to Floating UI would require dropping `react-popper` and `@popperjs/core` all together and possibly lead to some breaking changes, I added the max size modifier directly to the code and stopped using `react-max-size-modifier`. This seemed like the most appropriate solution at the moment.
> feat(BaseDropdown): add BaseDropdown component

- packages/core/src/components/Button/Button.styles.ts
I don't think we need this here. The button will take whatever size the icon inside has and we might need icons bigger than 32px (check the `Avatar` stories).
> fix: remove static width and height from the button when in icon mode

- packages/core/src/components/Dialog/Dialog.stories.tsx
- packages/core/src/components/Dialog/Dialog.tsx
- the code that sets the `focusableQueue` was causing a re-render of the `Dialog` component because of the `useState` hook and this re-render was removing the focus of the intended element. 
- updated the code to the `useRef` hook to prevent the re-render.
> fix: fix Dialog firstFocusable property not working properly. #HVUIKIT-6609

- package.json
- packages/core/package.json
- packages/core/src/components/BaseDropdown/__snapshots__/BaseDropdown.test.tsx.snap
- packages/core/src/components/DropDownMenu/__snapshots__/DropDownMenu.test.tsx.snap
- packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/core/src/providers/Provider.tsx
- pnpm-lock.yaml
- `CacheProvider` from emotion is used to prepend the UI Kit styles;
- `react-google-charts` removed from the core package and switched to the project root.
> fix: load UI Kit styles first to enable styling overrides

- packages/core/src/components/Badge/Badge.styles.tsx
- packages/core/src/components/Badge/__snapshots__/Badge.test.tsx.snap
- packages/styles/src/types.ts
- also removed `textTransform` from the `TypographyProps` type as it's not used. The only typography variant that uses it is the legacy variant `sectionTitle` and that is setting the `textTransform` itself.
> fix(Badge): constrain badge size to specs

- packages/core/src/providers/ThemeProvider.tsx
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/ds5.ts
- In the master branch, if no `bgcolor` was provided to the `HvCard`, the card would have a transparent background color. This was fixed in this PR since the applications that are currently using the UI Kit are expecting to have this transparent background color.
> fix: default transparent background color for HvCard

- packages/core/src/components/Radio/Radio.tsx
I opted to leave the `value` prop typed as `any` because MUI's `Radio` component which we are using also types it as `any`: https://mui.com/material-ui/api/radio/
> chore: update types for the Radio component

- app/src/headerTheme.ts
- packages/core/src/components/BaseDropdown/BaseDropdown.styles.tsx
- packages/core/src/components/BaseDropdown/__snapshots__/BaseDropdown.test.tsx.snap
- packages/core/src/components/BaseInput/BaseInput.styles.tsx
- packages/core/src/components/BaseInput/__snapshots__/BaseInput.test.tsx.snap
- packages/core/src/components/BreadCrumb/Page/Page.styles.tsx
- packages/core/src/components/BreadCrumb/__snapshots__/BreadCrumb.test.tsx.snap
- packages/core/src/components/Controls/__snapshots__/Controls.test.tsx.snap
- packages/core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/core/src/components/MultiButton/MultiButton.styles.tsx
- packages/core/src/components/Pagination/Pagination.styles.tsx
- packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/core/src/components/TagsInput/TagsInput.styles.tsx
- packages/core/src/components/TextArea/__snapshots__/TextArea.test.tsx.snap
- packages/styles/src/themes/ds5.ts
- Replace occurrences of `borderRadius: "2px"` with the same value but from the theme (`base` value).
- Allows us to customize the theme to change the value of the `base` property and have it reflected everywhere
> chore: replace static references to base radius with the theme value

- packages/core/package.json
- packages/core/src/hocs/withId.tsx
- packages/core/src/providers/ThemeProvider.tsx
- packages/core/src/types/generic.ts
- packages/core/src/types/theme.ts
- packages/icons/package.json
- packages/shared/CHANGELOG.md
- packages/shared/README.md
- packages/shared/package.json
- packages/shared/src/context/ThemeContext.ts
- packages/shared/src/context/index.ts
- packages/shared/src/index.ts
- packages/shared/src/types/generic.ts
- packages/shared/src/types/index.ts
- packages/shared/src/types/theme.ts
- packages/shared/tsconfig.json
- packages/shared/vite.config.js
- packages/styles/package.json
- pnpm-lock.yaml
- tsconfig.json
The package provides shared React contexts for the Hitachi Vantara UI Kit. It allows UI Kit components to share state (e.g. active theme) even if they are built with different versions of the UI Kit or are not using the same HvProvider instance.
This package is intended to be used in embedded scenarios, particularly when using the Hitachi Vantara App Shell framework. In these cases, declare the @hitachivantara/uikit-react-shared package as external in your bundler configuration. An ESM bundle is provided in the package, which can be deployed, and the importmap can be configured to point to it.
For regular usage of the UI Kit, you don't need to know about this package. All the contexts and types are re-exported from the core package.
> feat: package providing shared React context

- packages/core/src/providers/ThemeProvider.tsx
I noticed that the themes list on the `ThemeSwitcher` was not updating when I updated the themes on the code. From what I understand the themes variable that we're setting on the `ThemeContext` is not getting updated so the `ThemeSwitcher`was not reflecting that change.
> fix: update themes when themes list changes

- packages/core/src/components/AppSwitcher/Action/Action.tsx
- packages/core/src/components/AppSwitcher/AppSwitcher.stories.tsx
- packages/core/src/components/AppSwitcher/AppSwitcher.tsx
- packages/core/src/components/Banner/Banner.stories.tsx
- packages/core/src/components/Banner/Banner.tsx
- packages/core/src/components/Banner/BannerContent/ActionContainer/ActionContainer.tsx
- packages/core/src/components/Banner/BannerContent/BannerContent.tsx
- packages/core/src/components/Forms/FormElement/FormElement.tsx
- packages/core/src/components/Forms/Suggestions/Suggestions.tsx
- packages/core/src/components/Input/Input.stories.tsx
- packages/core/src/components/Input/Input.tsx
- packages/core/src/components/Pagination/Pagination.tsx
- packages/core/src/components/SelectionList/SelectionList.tsx
- packages/core/src/components/TagsInput/TagsInput.tsx
- packages/core/src/components/ToggleButton/ToggleButton.tsx
- packages/core/src/hooks/useClickOutside.ts
- packages/core/src/types/forms.ts
The generic function types were removed this was not providing enough context while using the components. 
`HvApplication` was also renamed to `HvAppSwitcherActionApplication`. This is the old name and it seems more specific.
> fix: generic function types removed

- packages/core/src/components/Table/TableRow/TableRow.tsx
- packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
A border radius was added to the table outline focus.
Note: The table needs to be reviewed later on because in Firefox the background color overflows the outline.
> fix: border radius added to table outline focus

- packages/core/src/components/AppSwitcher/Action/Action.tsx
- packages/core/src/components/AppSwitcher/AppSwitcher.test.tsx
- packages/core/src/components/AppSwitcher/__snapshots__/AppSwitcher.test.tsx.snap
Fix for https://github.com/lumada-design/hv-uikit-react/issues/3233
I decided to implement the change limited to the appswitcher component (and not at Avatar component) as I'm not aware of the consequences that could occur at any other components/scenarios where Avatar is used.
> feat(app-switcher | accessibility): remove avatar from accessibility tree - issue 3233

- packages/core/src/components/AppSwitcher/Action/Action.tsx
- packages/core/src/components/AppSwitcher/__snapshots__/AppSwitcher.test.tsx.snap
Fix for https://github.com/lumada-design/hv-uikit-react/issues/3234
<A> or <BUTTON> elements have now aria-describedby & aria-label
After a further analysis was decided to not add aria-label also to the <LI> as it's not required (Action is at <A> or <BUTTON>
> feat(app-switcher | accessibility): remove description from <a>/<li> name - issue 3234

- packages/core/src/components/Accordion/Accordion.tsx
- packages/core/src/components/BaseDropdown/BaseDropdown.test.tsx
- packages/core/src/components/BreadCrumb/BreadCrumb.styles.tsx
- packages/core/src/components/Button/Button.stories.tsx
- packages/core/src/components/Button/Button.tsx
- packages/core/src/components/Card/Card.stories.tsx
- packages/core/src/components/GlobalActions/GlobalActions.stories.tsx
- packages/core/src/components/Panel/Panel.stories.tsx
- packages/core/src/components/Typography/Typography.tsx
- packages/core/src/components/Typography/utils.ts
- packages/core/src/components/VerticalNavigation/NavigationSlider/NavigationSlider.styles.tsx
- Unnecessary button prop removed: `sx`
- Typography and button warnings are only shown when the DS3 theme is used
> chore: remove warnings for DS3 and unnecessary button prop

- app/src/generator/Colors/index.ts
- app/src/generator/FontFamily/index.ts
- app/src/generator/FontSizes/index.ts
- app/src/generator/Radii/index.ts
- app/src/generator/Sidebar/Sidebar.tsx
- app/src/generator/Sizes/index.ts
- app/src/generator/Spacing/index.ts
- app/src/generator/Typography/index.ts
- app/src/generator/Zindices/index.ts
- packages/core/src/providers/Provider.tsx
This significantly improves the performance of the Theme Generator when opening / closing the sidebar. By lazily loading the components inside the accordions we guarantee their styles are added and removed from the `<head>` element.
https://user-images.githubusercontent.com/7498785/229217234-e737710c-8e1d-4945-9e6b-b45f90cc6f3c.mov
> chore: improve generator performance

- packages/core/src/components/BreadCrumb/Page/Page.tsx
- packages/core/src/components/BulkActions/BulkActions.stories.tsx
- packages/core/src/components/Dialog/Dialog.tsx
- packages/core/src/components/FileUploader/DropZone/DropZone.tsx
- packages/core/src/components/Focus/Focus.tsx
- packages/core/src/components/GlobalActions/GlobalActions.tsx
- packages/core/src/components/Grid/Grid.tsx
- packages/core/src/components/MultiButton/MultiButton.stories.tsx
- packages/core/src/components/Snackbar/Snackbar.tsx
- packages/core/src/components/Table/TableCell/TableCell.tsx
- packages/core/src/components/Table/TableHeader/TableHeader.tsx
- packages/core/src/components/TagsInput/TagsInput.stories.tsx
- packages/core/src/components/TextArea/TextArea.tsx
- Lodash functions are imported one-by-one to reduce the bundle size.
> chore: import lodash functions one-by-one to reduce bundle size

- packages/core/src/components/ActionsGeneric/ActionsGeneric.styles.tsx
- packages/core/src/components/Banner/BannerContent/ActionContainer/ActionContainer.styles.tsx
- packages/core/src/components/BreadCrumb/BreadCrumb.styles.tsx
- packages/core/src/components/BreadCrumb/Page/Page.styles.tsx
- packages/core/src/components/Dialog/Dialog.styles.tsx
- packages/core/src/components/DropDownMenu/DropDownMenu.styles.tsx
- packages/core/src/components/FileUploader/File/File.styles.tsx
- packages/core/src/components/FileUploader/Preview/Preview.styles.tsx
- packages/core/src/components/Header/Brand/Brand.styles.tsx
- packages/core/src/components/Login/Login.stories.tsx
- packages/core/src/components/Table/TableHeader/TableHeader.styles.tsx
- packages/core/src/components/Tag/Tag.styles.tsx
- packages/core/src/components/VerticalNavigation/Header/Header.styles.tsx
Since we were using functional components with the `styled` utility in some situations to avoid circular dependencies, the references were not being forwarded. This was fixed.
> fix: dropdown menu popper positioning

- app/src/generator/Sidebar/Sidebar.styles.tsx
- app/src/generator/Sidebar/Sidebar.tsx
- make the line columns on the `CodeEditor` narrower to give more space to the code section;
- make the `CodeEditor` readonly until we support manually editing the theme;
> chore: small changes on the Code Editor

- app/src/generator/Sidebar/Sidebar.styles.tsx
- app/src/generator/Sidebar/Sidebar.tsx
Proposed layout for the `CodeEditor` in this commit:
> chore: recover the reset and copy code buttons on the code editor and css refactor

- package-lock.json
- packages/code-editor/README.md
- packages/code-editor/package.json
- packages/code-editor/src/components/CodeEditor/CodeEditor.stories.tsx
- packages/code-editor/src/components/CodeEditor/CodeEditor.tsx
- Updated the React package that the `CodeEditor` was using from `react-monaco-editor` to `@monaco-editor/react`:
> react-monaco-editor is a third-party package that provides a React wrapper around Monaco Editor. While it's still actively maintained and used by many developers, it's no longer the recommended package for using Monaco Editor with React.
> 
> The reason for this is that react-monaco-editor hasn't been updated to use the latest version of Monaco Editor (currently version 0.28.2 as of this writing). This means that it's missing some of the latest features and bug fixes available in the latest version.
> 
> @monaco-editor/react, on the other hand, is maintained by the same team that develops Monaco Editor and is updated to use the latest version. It also provides a more …
> chore: update CodeEditor to use a different package and enable syntax highlighting and validation

- app/src/components/common/Header/Header.tsx
- app/src/generator/Colors/Colors.tsx
- app/src/generator/FontFamily/FontFamily.tsx
- app/src/generator/FontSizes/FontSizes.tsx
- app/src/generator/GeneratorContext.tsx
- app/src/generator/Radii/Radii.tsx
- app/src/generator/Sidebar/Sidebar.styles.tsx
- app/src/generator/Sidebar/Sidebar.tsx
- app/src/generator/Sizes/Sizes.tsx
- app/src/generator/Spacing/Spacing.tsx
- app/src/generator/Typography/Typography.tsx
- app/src/generator/Zindices/Zindices.tsx
- app/src/generator/utils.ts
- removed the unnecessary `changedValues` logic. It was only used to keep track of the changes made to the theme and show those on the Code Editor but was very prone to mistakes. Now the actual changed theme is used to display those changes;
- removed the badge icon on Header as it's totally irrelevant there and `Badge` component is already on the components list;
- added Undo / Redo logic to the Code Editor as it might be useful whenever someone is updating the theme and making several changes;
> chore: refactor Theme Generator

- package-lock.json
- packages/lab/package.json
Was leading to a wrong build file structure:
> fix: install missing `clsx` in lab

- packages/core/src/components/Banner/BannerContent/BannerContent.tsx
- packages/core/src/components/Card/Card.tsx
- packages/core/src/components/Card/Content/Content.tsx
- packages/core/src/components/Card/Header/Header.tsx
- packages/core/src/components/Card/Media/Media.tsx
- packages/core/src/components/Card/__snapshots__/Card.test.tsx.snap
- packages/core/src/components/Controls/__snapshots__/Controls.test.tsx.snap
- packages/core/src/components/DatePicker/DatePicker.tsx
- packages/core/src/components/Dialog/Dialog.tsx
- packages/core/src/components/DropDownMenu/DropDownMenu.tsx
- packages/core/src/components/FilterGroup/Counter/Counter.tsx
- packages/core/src/components/FilterGroup/FilterContent/FilterContent.tsx
- packages/core/src/components/FilterGroup/FilterGroup.tsx
- packages/core/src/components/FilterGroup/LeftPanel/LeftPanel.tsx
- packages/core/src/components/FilterGroup/RightPanel/RightPanel.tsx
- packages/core/src/components/InlineEditor/InlineEditor.tsx
- packages/core/src/components/QueryBuilder/RuleGroup/RuleGroup.tsx
- packages/core/src/components/ScrollTo/Horizontal/HorizontalScrollListItem/HorizontalScrollListItem.tsx
- packages/core/src/components/ScrollTo/Horizontal/ScrollToHorizontal.tsx
- packages/core/src/components/ScrollTo/Horizontal/__snapshots__/ScrollToHorizontal.test.tsx.snap
- packages/core/src/components/ScrollTo/Vertical/ScrollToVertical.tsx
- packages/core/src/components/ScrollTo/Vertical/VerticalScrollListItem/VerticalScrollListItem.tsx
- packages/core/src/components/ScrollTo/Vertical/__snapshots__/ScrollToVertical.test.tsx.snap
- packages/lab/src/components/StepNavigation/SimpleNavigation/Dot/Dot.tsx
- packages/lab/src/components/StepNavigation/StepNavigation.tsx
- packages/lab/src/components/StepNavigation/__snapshots__/StepNavigation.test.tsx.snap
- packages/lab/src/components/Wizard/WizardActions/WizardActions.tsx
- packages/lab/src/components/Wizard/WizardContainer/WizardContainer.tsx
- packages/lab/src/components/Wizard/WizardContent/WizardContent.tsx
- packages/lab/src/components/Wizard/WizardTitle/WizardTitle.tsx
- We started using `cx` in some components to fix override problems we were having when external classes were provided to the component. To maintain consistency I did the same for all the components that are using `ClassNames`. The classes order was also changed in some cases since external classes should be the last ones listed.
> chore: clsx replaced by cx and classes order updated

- packages/core/src/components/InlineEditor/InlineEditor.styles.tsx
- packages/core/src/components/InlineEditor/InlineEditor.test.tsx
- packages/styles/src/theme.ts
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/ds5.ts
- packages/styles/src/types.ts
- The inline editor height was changing when the input was in edit mode or not.
Before:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/8422b1f4-a002-400e-8d12-7a2ce854c99a
After:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/75f5c4d9-8cf3-42ec-b38f-8d9f168db32b
> fix: inline editor height variation

- packages/core/src/components/BulkActions/__snapshots__/BulkActions.test.tsx.snap
- packages/core/src/components/DropDownMenu/DropDownMenu.styles.tsx
- packages/core/src/components/DropDownMenu/__snapshots__/DropDownMenu.test.tsx.snap
> fix(DropdownMenu): fix missing border

- packages/core/src/components/Header/Navigation/MenuItem/MenuItem.styles.tsx
- The hover was not behaving correctly: when hovering a parent item, the child items were also highlighted. This was detected on our local app. On storybook everything seemed to be fine.
> fix: header hover

- packages/core/src/components/Banner/BannerContent/BannerContent.tsx
- packages/core/src/components/Dialog/Dialog.stories.tsx
- packages/core/src/components/Dialog/Dialog.styles.tsx
- packages/core/src/components/Dialog/Dialog.tsx
- packages/core/src/components/Dialog/Title/Title.tsx
- packages/core/src/components/Snackbar/SnackbarContentWrapper/SnackbarContentWrapper.tsx
- packages/core/src/utils/iconVariant.tsx
- Fix `Dialog` being `fullWidth` by default
- Defaults to the previous `sm` size
- Improve paper styles
- Remove redundant styles
- Decrease specificity
- (`HvDialog-paper`, `MuiPaper-root`, `MuiDialog-paper` all point to the same thing)
- Improve samples
- Add sizing controls to `Main`
- Mege semantic/custom icon samples
> fix(dialog): `maxWidth` defaults & configuration

- packages/core/src/components/VerticalNavigation/Navigation/Navigation.tsx
- packages/core/src/components/VerticalNavigation/Navigation/navigationClasses.ts
- packages/core/src/components/VerticalNavigation/NavigationPopup/NavigationPopup.tsx
- packages/core/src/components/VerticalNavigation/VerticalNavigation.stories.tsx
Hi guys,
On App Shell we need to be able to customize the VerticalNavigation popup, at this point we need to customize the maximum height of the popup. The approach we were using was to wrap App Shell in a GlobalStyles and the then force the customization of the popup with this css code:
```
div[role="tooltip"] {
max-height: calc(100vh - 64px);
overflow-y: auto;
}
```
However, by doing so, we detected that this could cause some issue on the embedded application when using tooltips, we need to get rid of that global style but still be able to customize the Vertical Navigation popup.
The content of this PR opens the possibility for us to customize the styling of the popup, however, we are aware that this is not at all a very elegant solution. If you have a better approach to achieve this, …
> chore(VerticalNavigation): created a property to customize popup styling

- packages/core/src/components/Calendar/CalendarNavigation/ComposedNavigation/__snapshots__/ComposedNavigation.test.tsx.snap
- packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
- packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.tsx
- packages/core/src/components/VerticalNavigation/TreeView/__snapshots__/TreeView.test.tsx.snap
- packages/core/src/components/VerticalNavigation/__snapshots__/VerticalNavigation.test.tsx.snap
- Change `VerticalNavigation`'s deprecated `placeholderText` Typography variant to `body` + `disabled`
> fix(VerticalNavigation): disabled element styles

- packages/core/src/components/VerticalNavigation/Navigation/Navigation.tsx
- packages/core/src/components/VerticalNavigation/NavigationSlider/NavigationSlider.tsx
- packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.tsx
- packages/core/src/components/VerticalNavigation/VerticalNavigation.stories.tsx
- packages/core/src/components/VerticalNavigation/VerticalNavigation.test.tsx
- packages/core/src/components/VerticalNavigation/VerticalNavigation.tsx
- packages/core/src/components/VerticalNavigation/__snapshots__/VerticalNavigation.test.tsx.snap
Fixes the usage of `aria-current` in `VerticalNavigation`
- use `aria-current="page"` when selected **and** element is a `link`, otherwise `aria-current="true"`
- add `aria-current` to Slider variant
- improve `NavigationData` typings. defaults to `"a"`'s properties, but can be overriden with other types
- eg. `NavigationData<"button">[]` or `NavigationData<typeof Link>[]`
- add & improve tests
> fix(VerticalNavigation): use of `aria-current`

- packages/lab/src/components/StepNavigation/StepNavigation.tsx
- packages/lab/src/components/StepNavigation/__snapshots__/StepNavigation.test.tsx.snap
- packages/lab/src/components/Wizard/Wizard.tsx
- packages/lab/src/components/Wizard/WizardContainer/WizardContainer.tsx
- packages/lab/src/components/Wizard/WizardTitle/WizardTitle.tsx
* `HvStepNavigation`: Definition of missing maxWidth on `xl` breakpoint
* `HvWizard`: Extend definition of props `maxWidth` and `fullWidth` of `HvDialog`. Value `lg` is now default for prop `maxWidth`.
> fix(HvWizard, HvStepNavigation): step navigation with maxWidth on xl breakpoint. #3368

- packages/core/src/components/VerticalNavigation/NavigationSlider/NavigationSlider.tsx
`HvListItem` expects `undefined` if no adornment is present and having `<div>{item.icon}</div>` incorrectly messes that up.
> fix(VerticalNavigation): no padding on menu items

- packages/lab/src/components/StepNavigation/SimpleNavigation/Dot/Dot.tsx
- packages/lab/src/components/Wizard/WizardTitle/WizardTitle.tsx
- Using absolute imports to fix the d.ts typing file for the lab package: aliases can't be used if not properly configured
Before:
After:
> fix: d.ts typing file for the lab package

- packages/core/src/components/AppSwitcher/AppSwitcher.styles.tsx
- packages/core/src/components/AppSwitcher/AppSwitcher.tsx
> fix(AppSwitcher): header and footer font styling

- packages/core/src/components/ActionsGeneric/__snapshots__/ActionsGeneric.test.tsx.snap
- packages/core/src/components/Banner/__snapshots__/Banner.test.tsx.snap
- packages/core/src/components/BulkActions/__snapshots__/BulkActions.test.tsx.snap
- packages/core/src/components/Button/Button.test.tsx
- packages/core/src/components/Button/Button.tsx
- packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/core/src/components/Controls/__snapshots__/Controls.test.tsx.snap
- packages/core/src/components/DropDownMenu/__snapshots__/DropDownMenu.test.tsx.snap
- packages/core/src/components/FileUploader/File/__snapshots__/File.test.tsx.snap
- packages/core/src/components/FileUploader/FileList/__snapshots__/FileList.test.tsx.snap
- packages/core/src/components/FileUploader/__snapshots__/FileUploader.test.tsx.snap
- packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/core/src/components/QueryBuilder/__snapshots__/QueryBuilder.test.tsx.snap
- packages/core/src/components/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
- packages/core/src/components/VerticalNavigation/__snapshots__/VerticalNavigation.test.tsx.snap
- packages/lab/src/components/StepNavigation/__snapshots__/StepNavigation.test.tsx.snap
By default, HTML `button`s are of `type="submit"`. This is typically not desirable in web apps, because is common to want custom behaviour instead. The `type="button"` was the default in previous majors, inherited from MUI.
This PR restores the previous default behaviour `type="button"`.
> fix(Button): restore default `type=button` behaviour

- app/src/components/common/IconButton.tsx
- app/src/generator/CodeEditor/CodeEditor.tsx
- app/src/generator/utils.ts
- accessible Download button
- leverages new `HvButton`'s `component` prop
- allows to "save as" theme, open in new tab (sharable URL), etc.
- add `IconButton` component to dedupe code
- includes `aria-label` and `span` to always show tooltip
> chore(app): improve `ThemeCreator` download & action buttons

- packages/core/src/components/Tooltip/Tooltip.stories.tsx
- packages/core/src/components/Tooltip/Tooltip.styles.tsx
- packages/core/src/components/Tooltip/Tooltip.tsx
- Add sample on how to correctly disable tooltips
- Merge 'complex' tooltip samples & add docs on best-practices
- Dedupe typings docs (refer to MUI)
- Dedupe tooltip stylings
> docs(Tooltip): improve samples and typings docs

- packages/core/src/components/Calendar/SingleCalendar/CalendarCell.tsx
- packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
`Tooltip` on CalendarCell shows redundant information (month and year is show just above) and can make selection a date more difficult. This removes the use of the tooltip.
https://github.com/lumada-design/hv-uikit-react/assets/638946/e0f766d3-55a5-43ff-9f39-4931df1a7513
> chore(Calendar): remove Tooltip on cell

- packages/core/src/components/FilterGroup/Counter/Counter.tsx
Separating the `flat` function call from the rest of the chained array operations solves the issue. I believe this is related to the fact that `flat` [returns a new array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) instead of modifying the original array in place, whereas `filter` and `forEach` operate on the original array (well `filter` [returns a shallow copy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) of the original array that shares the same references as the original).
> fix(FilterGroup): fix incorrect counter value

- .config/vite.config.js
- package-lock.json
- package.json
- packages/code-editor/package.json
- packages/core/package.json
- packages/lab/package.json
add `npm run coverage` & required configuration to have a coverage report generated.
disabled by default in `npm test`
> test: add coverage config & script

- app/src/generator/Typography/Typography.tsx
- app/src/generator/utils.ts
Made some changes to the Typography section:
- in the list of typographies each has the styles of the corresponding typography
- the font size is now a slider with a unit dropdown
-- prevents incorrect values being entered on the input as was possible before
-- the scale of the slider changes depending on the type of unit (`px/pt`: 0-100, `em/rem`: 0-10) and the value is clamped to the new range
https://github.com/lumada-design/hv-uikit-react/assets/7498785/35a976a1-8754-487c-87d6-8f8e1a01e0f1
> chore: refactor Typography section

- packages/core/src/components/BaseInput/BaseInput.tsx
- Disable more browser-dependent input elements
- Fixes warnings:
```
BaseInput.tsx:20 Using kebab-case for css properties in objects is not supported. Did you mean WebkitBoxShadow?
BaseInput.tsx:20 Using kebab-case for css properties in objects is not supported. Did you mean WebkitTextFillColor?
```
> chore(BaseInput): remove calendar icon & fix class warnings

- app/src/components/common/Header/Header.tsx
- app/src/pages/Instructions/Instructions.tsx
Right now on smaller resolutions the header of the app disappears in favor of an icon menu button (which makes sense) but that button does nothing. I'm removing this logic for now as we have to think how to integrate a vertical navigation on smaller resolutions because there are scenarios where we already have that space filled with a side menu (components page). Also included a small refactor of the **Instructions** page.
> chore: fix Header on the app disappearing

- .storybook/theme/styles/docs.ts
When doing the line and bar charts I added `overflow: visible` in the Storybook CSS to avoid hiding the chart tooltips. However I did not notice at the time this added an horizontal scrollbar to the docs. Moreover, I just noticed now that the Global Actions stories were overflowing. 
I fixed this and now the `overflow: visible` CSS is only applied to the line and bar charts stories (to avoid any side effects in other components' stories) and the horizontal scrollbar no longer appears.
> docs: fix storybook horizontal scrollbar

- packages/core/src/components/BaseInput/BaseInput.tsx
- packages/core/src/components/ColorPicker/Fields/Fields.tsx
- packages/core/src/components/Forms/Suggestions/Suggestions.tsx
- packages/core/src/components/Input/Input.tsx
- packages/core/src/components/TextArea/TextArea.tsx
- add `forwardRef` to `HvInput`/`HvTextArea`/`HvSuggestions`
- deprecate `inputRef` in favour of `ref`
- improve/fix typings
- change `HvInput`'s clear & to trigger internal `onChange`, so that the external `onChange` is triggered with the correct event
> fix(Input): `onChange` event type & forwardRef

- packages/core/src/components/DatePicker/DatePicker.stories.tsx
- packages/core/src/components/DatePicker/DatePicker.tsx
- Removed the `HvDatePickerStatus` type in favor of `HvFormStatus`
- I opted to leave the `empty` value for the `HvDatePicker` status as it might make sense to have it there
- Updated the `DatePicker` stories to have a "Variants"  story instead of multiple unnecessary stories for each variant
> fix(DatePicker): have DatePicker use the HvFormStatus type for its status prop

- packages/core/src/components/BreadCrumb/BreadCrumb.tsx
- packages/core/src/components/BreadCrumb/Page/Page.tsx
- remove `startCase` to allow special characters to be passed. still converts to start-case
> fix(breadcrumb): allow special characters

- app/src/generator/CodeEditor/CodeEditor.tsx
- app/src/generator/Colors/Colors.tsx
- app/src/generator/FontFamily/FontFamily.tsx
- app/src/generator/FontSizes/FontSizes.tsx
- app/src/generator/GeneratorContext.tsx
- app/src/generator/Radii/Radii.tsx
- app/src/generator/Sidebar/Sidebar.tsx
- app/src/generator/Sizes/Sizes.tsx
- app/src/generator/Spacing/Spacing.tsx
- app/src/generator/Typography/Typography.tsx
- app/src/generator/Zindices/Zindices.tsx
- app/src/generator/utils.ts
- app/src/pages/Instructions/tutorialData.ts
- packages/core/src/types/generic.ts
- packages/styles/src/types.ts
- refactor of the logic on the Theme Creator 
- removed undo / redo buttons. 
- this functionality is available on the `Code Editor` since it's no longer readonly
- if we find we need these controls, we should consider implementing it by using some library that provides us this functionality.
> chore: refactor theme creator

- .config/applitools.config.js
- packages/core/src/components/BreadCrumb/BreadCrumb.tsx
- packages/core/src/components/BreadCrumb/Page/Page.tsx
- packages/core/src/components/Carousel/Carousel.stories.tsx
- reverts #3469 which for some reason is making Applitools break
- reverts some Applitools settings
- waitFor Carousel images to load
> Revert "fix(breadcrumb): allow special characters on labels (#3469)"

- README.md
- docs/overview/GetStarted.stories.mdx
- add CLI recommendation in Get Started
- instead of manual setup + examples
- remove duplicated manual setup from README
> docs: promote CLI instead of examples

- docs/foundation/colors/Colors.tsx
- packages/core/src/components/BreadCrumb/BreadCrumb.stories.tsx
- packages/core/src/components/BreadCrumb/BreadCrumb.tsx
- packages/core/src/components/BreadCrumb/Page/Page.tsx
- This is the same fix @zettca did previously but I'm also removing `startCase` in the colors doc page to fix applitools (indefinitely reading stories problem).
> fix(breadcrumb): remove startCase

- app/src/components/common/IconButton.tsx
- app/src/generator/CodeEditor/CodeEditor.tsx
- app/src/generator/Colors/Colors.tsx
- app/src/generator/GeneratorContext.tsx
- app/src/generator/Typography/Typography.tsx
whenever we were manually **removing** anything from the Code Editor those changes weren't being taken into consideration since we're diffing with the current changes with the previous changes and merging the result:
```
const diff = themeDiff(prev, changes);
return merge({}, prev, diff);
```
but the previous versions include what we're removing so they're never actually removed. I added a `isCodeEdit`prop because editing the code manually is actually different from making changes using the other controls.
> chore: fix theme creator app not considering the removal of customisations from the code editor

- packages/core/src/components/Carousel/Carousel.stories.tsx
- packages/core/src/components/Carousel/Carousel.styles.ts
- packages/core/src/components/Carousel/Carousel.tsx
- packages/core/src/components/Carousel/CarouselControls.tsx
- packages/core/src/components/Carousel/CarouselSlide/CarouselSlide.tsx
- packages/core/src/components/Carousel/CarouselThumbnail.tsx
- packages/core/src/components/Carousel/CarouselThumbnails.tsx
- packages/core/src/utils/classes.ts
- packages/styles/src/theme.ts
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/ds5.ts
- packages/styles/src/types.ts
- break down `HvCarousel` into sub-components
- makes it easier to build a custom carousel, if the current `HvCarousel` doesn't suit some use-case
- add `controlsPosition` & `thumbnailsPosition` props to configure thumbnail/controls position
> feat(Carousel): add customisable controls/thumbnail position

- app/package.json
- app/src/generator/CodeEditor/CodeEditor.tsx
- package-lock.json
Using the `json5` library will prevent us from needing to do several manual validations on the parsing of the theme to a JSON object (like including comments, trailing commas, etc)
> chore: use json5 library to parse the code editor theme

- app/src/generator/Typography/Typography.tsx
- app/src/generator/utils.ts
- docs/guides/theming/ThemeStructure.tsx
- packages/core/src/components/Drawer/Drawer.tsx
- packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
- packages/core/src/components/InlineEditor/InlineEditor.tsx
- packages/core/src/components/Table/TableCell/TableCell.tsx
- packages/core/src/components/Table/TableRow/TableRow.tsx
- packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
- packages/core/src/utils/theme.ts
- moved the `getVarValue` function to a centralized place in the `styles` package (it was being defined differently in the `core` package and in the `app`).
- updated all uses of this function
- updated snapshots
> fix(InlineEditor): losing variant styles when in edit mode

- .eslintrc
- package-lock.json
- package.json
- packages/core/src/components/Dialog/Dialog.tsx
- packages/core/src/components/Input/Input.tsx
- move `setInputValue` inside function so that `window.` doesn't break SSR
- add `eslint-plugin-ssr-friendly` to catch these types of regressions
> fix(Input): unprotected window usage breaking SSR

- app/src/lib/routes.tsx
- app/src/pages/Icons.tsx
- packages/icons/src/IconBase.tsx
- packages/icons/src/svgToReact.ts
- packages/icons/src/utils/converter/generateComponent.ts
- hoist duplicated code in each icon component to `useIconSize` and `useIconColor` hooks
- add page to `app` to test out bundling
Looking at the `dist` folder, and the lazy-loaded Icons app route (that loads all icons) we get the following results:
|               | Before   | After    |
| ------------- | -------- | -------- |
| `dist/esm`    | `4.3M`   | `3.9M`   |
| `pages/Icons` | `478 kB` | `309 kB` |
> perf(Icons): move icon logic to hook to reduce size

- packages/lab/src/components/Wizard/WizardTitle/WizardTitle.tsx
While refactoring the wizard component I detected that the summary was not opening. This was fixed.
> fix(Wizard): summary not opening

- packages/core/src/components/Dialog/Actions/Actions.tsx
- packages/core/src/components/Dialog/Content/Content.tsx
- packages/core/src/components/Dialog/Dialog.stories.tsx
- packages/core/src/components/Dialog/Dialog.styles.tsx
- packages/core/src/components/Dialog/Dialog.tsx
- packages/core/src/components/Dialog/Title/Title.tsx
- `variant` prop added to `HvDialog` to show a status bar at the top of the dialog.
> feat(Dialog): variant prop added for dialog status bar

- packages/core/src/components/Typography/Typography.tsx
`label` should be used to label content. `<HvTypography variant="label">` is being mostly used as a bold variant of `"body"`, not to label content
Changed to `span`, as `p` comes with other associated default styles. `span` has the same default display as `label`
> fix(Typography): change label variant default to `span`

- app/src/generator/utils.ts
- docs/foundation/colors/Colors.tsx
- packages/core/src/utils/classes.ts
- Instead of `Object.hasOwn` we now use `Object.prototype.hasOwnProperty.call` since the former was only introduced in Chrome 93 and we support lower versions. I did not use `obj.hasOwnProperty(key)` since this was leading to a ESLint error.
- This fixes the pa11y tests. Nothing was being tested since it uses Chrome 91. 
💡 Maybe we should think about using the [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) to prevent using stuff that is not compatible with the browsers we support. I tested this plugin and it seems great but I decided not to add it since there's currently a [bug](https://github.com/amilajack/eslint-plugin-compat/issues/404) where nothing inside an if statement is reported as an error 😅
> refactor: use hasOwnProperty instead of hasOwn

- packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.styles.tsx
- packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.tsx
Fixes: https://github.com/lumada-design/hv-uikit-react/issues/3510
Before:
After:
> fix(VerticalNavigation): collapse/expand icon hidden when the label is long

- packages/lab/src/components/Wizard/WizardActions/WizardActions.styles.tsx
- packages/lab/src/components/Wizard/WizardActions/WizardActions.tsx
- packages/lab/src/components/Wizard/WizardTitle/WizardTitle.styles.tsx
- packages/lab/src/components/Wizard/WizardTitle/WizardTitle.tsx
- replace `HvGrid` usage in `HvWizard` with simpler `div`s, since there are no grid `item`s
- align styles (spacing)
> fix(Wizard): grid usage & styles

- packages/core/src/components/DropDownMenu/DropDownMenu.tsx
- packages/icons/src/utils/converter/generateComponent.ts
The [`name` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) should only be used in form elements. Our `div` icon components are adding the icon name to the `name` attribute.
Replaced `name` with `data-name` in case it's being used for testing, although this should probably be tested in a better way (select by label, role, or testid)
> fix(icons): replace name attribute with data-name

- packages/core/src/components/BaseDropdown/BaseDropdown.tsx
Fixes the accessibility problem with the dropdown menu: https://github.com/lumada-design/hv-uikit-react/issues/3537 
[The `aria-expanded` attribute was already defined on the custom button used on the dropdown menu.](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/components/DropDownMenu/DropDownMenu.tsx#L142) Thus, I decided to remove the `aria-expanded` attribute from the dropdown menu's root container as none of the [authorised roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#associated_roles) seemed appropriate. This was fixed on the base dropdown component by not setting the `aria-expanded` attribute if no role is provided.
> fix(DropdownMenu): aria expanded set if role exists in base dropdown

- .config/pa11yci.config.js
we already have `color-contrast` as an ignore rule on our pa11y config file. This adds the actual rule that is being vioated on our color contrast violations.
> fix: add color contrast ignore rule to the pa11y config

- packages/core/src/components/Table/stories/Table.stories.tsx
- packages/core/src/components/Table/stories/TableHooks/TableHooks.stories.tsx
- packages/core/src/components/Table/stories/TableSamples/TableSamples.stories.tsx
- packages/core/src/components/Table/stories/storiesUtils.tsx
- Improve typings DX and remove redundant types
- rename + document table data type to `AssetEvent` (`NewEntry` is confusing)
- feel free to suggest a better dummy data name 👍 
- add `id`s to row actions
- remove some redundant `key`'s - `react-table` should handle these
- for custom keys use `getRowId`
- make `useServerData` more realistic (`undefined` initial `data`, doesn't return `columns`)
```tsx
const data: MyType = useMemo(() => {/* ❌ no completions */}, [])
const data: = useMemo<MyType>(() => {/* ✅ good completions */}, [])
```
> docs(Table): improve samples & type

- packages/core/src/components/BulkActions/BulkActions.tsx
- packages/core/src/components/CheckBoxGroup/CheckBoxGroup.styles.tsx
- packages/core/src/components/DropDownMenu/DropDownMenu.styles.tsx
- packages/core/src/components/FilterGroup/RightPanel/RightPanel.styles.tsx
- packages/core/src/components/List/List.styles.tsx
- packages/core/src/components/RadioGroup/RadioGroup.styles.tsx
- packages/core/src/components/SelectionList/SelectionList.styles.tsx
- packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.styles.tsx
- packages/core/src/components/VerticalNavigation/TreeView/descendants.tsx
Remove remaining `.focus-within` and `.focus-visible` polyfill classes.
We don't support IE11 anymore. And even if we did, these class polyfills aren't being applied
> chore: remove unused ie11 polyfills

- packages/icons/README.md
- packages/icons/package.json
- move `svgo` optimizer out of `npm run convert` (to `npm run optimize`)
- improves performance (less stuff to "build")
- `svgo` rarely needs to be run (only when adding new icons)
- `svgo` changes need to be manually reviewed, as it changes source-code files
- improve icons package docs (file structure & adding icons)
> build(icons): split `svgo` optimizer from converter & improve docs

- app/src/components/common/Header/Header.tsx
- app/src/components/common/Tutorial/Step.tsx
- app/src/generator/CodeEditor/CodeEditor.tsx
- app/src/generator/Colors/Colors.tsx
- app/src/generator/Content.tsx
- app/src/generator/FontFamily/FontFamily.tsx
- app/src/generator/FontSizes/FontSizes.tsx
- app/src/generator/GeneratorContext.tsx
- app/src/generator/Radii/Radii.tsx
- app/src/generator/Sidebar/Sidebar.tsx
- app/src/generator/Sizes/Sizes.tsx
- app/src/generator/Spacing/Spacing.tsx
- app/src/generator/Typography/Typography.tsx
- app/src/generator/Zindices/Zindices.tsx
- app/src/pages/Instructions/Instructions.tsx
Updated the use of the context in the Theme Creator. Created a new hook that deals with validating if the context exists, allowing the `GeneratorContext` to be initialized as null instead of actually unnecessarily creating a new theme just for that purpose. The components that need to use the context use this custom hook instead of having to import `useContext` and `GeneratorContext` everytime.
> chore(ThemeCreator): refactor use of context

- packages/core/src/components/Header/Header.stories.tsx
- packages/core/src/components/Header/Navigation/MenuItem/MenuItem.tsx
- packages/core/src/components/Header/Navigation/Navigation.tsx
- packages/core/src/components/Header/Navigation/useSelectionPath.ts
This PR fixes https://github.com/lumada-design/hv-uikit-react/issues/3525:
- The `aria-current` is now set to `true` if the selected item has sub levels. Otherwise, it's set to `page`.
- The header has been limited to 2 levels since using more levels leads to weird behaviours and it's [not supported in DS](https://designsystem.hitachivantara.com/6c705d900/v/0/p/90fb01-navigation-system/b/07cb30).
- A new story was added to showcase how this can be used.
> fix(Header): aria-current set to true if item has sub levels

- packages/core/src/components/AppSwitcher/AppSwitcher.test.tsx
- packages/core/src/components/Avatar/Avatar.test.tsx
- packages/core/src/components/Badge/Badge.test.tsx
- packages/core/src/components/Forms/Adornment/Adornment.test.tsx
- packages/core/src/components/Kpi/Kpi.test.tsx
- packages/icons/lib/IconBase.tsx
- packages/icons/lib/IconSprite.tsx
- packages/icons/src/utils/converter/generateComponent.ts
- packages/icons/src/utils/size.ts
- pass a11y props to the `svg` element instead of the div container
- use `splitIconProps` function to do this
- also refactor focusable and size props to use `splitIconProps`
- fix tests using presentation role and label
> fix(Icons): fix aria-label set on the wrong element

- .config/pa11yci.config.js
- docs/overview/migration/MigrationV5.stories.mdx
- docs/overview/status/data.json
- packages/viz/src/components/BarChart/BarChart.tsx
- packages/viz/src/components/BaseChart/BaseChart.tsx
- packages/viz/src/components/ConfusionMatrix/ConfusionMatrix.stories.tsx
- packages/viz/src/components/ConfusionMatrix/ConfusionMatrix.styles.tsx
- packages/viz/src/components/ConfusionMatrix/ConfusionMatrix.tsx
- packages/viz/src/components/ConfusionMatrix/index.ts
- packages/viz/src/components/ConfusionMatrix/types.ts
- packages/viz/src/components/ConfusionMatrix/utils.ts
- packages/viz/src/components/DonutChart/DonutChart.stories.tsx
- packages/viz/src/components/DonutChart/DonutChart.tsx
- packages/viz/src/components/LineChart/LineChart.tsx
- packages/viz/src/components/index.ts
- packages/viz/src/hooks/index.ts
- packages/viz/src/hooks/tooltip/useTooltip.tsx
- packages/viz/src/hooks/useData.tsx
- packages/viz/src/hooks/useGrid.tsx
- packages/viz/src/hooks/useVisualMap.tsx
- packages/viz/src/hooks/useXAxis.tsx
- packages/viz/src/hooks/useYAxis.tsx
- packages/viz/src/types/axis.ts
- packages/viz/src/types/common.ts
- packages/viz/src/types/index.ts
- packages/viz/src/types/measures.ts
- packages/viz/src/types/tooltip.ts
- packages/viz/src/utils/registerTheme.ts
- Confusion matrix component created.
-  Formats available: `square` (default) or `landscape`.
-  The confusion matrix uses a default color scale but it can be overwritten. If it's a delta matrix, the `positive`/`negative` colors are used. 
- Leverages the visual roles to create the confusion matrix. 
- Should we enable users to provide the matrix and rows/columns values directly in the future?
- More customisations added to the charts: chart width and height, axis position, and axis name customisations.
> feat(ConfusionMatrix): confusion matrix added

- packages/core/src/components/DropDownMenu/DropDownMenu.tsx
- `role="presentation"` replaced by `aria-hidden` on the dropdown menu component to fix a bunch of these accessibility issues we have on various stories. `aria-hidden` seemed more appropriate since the icon is unimportant and not needed for the accessibility tree.
> fix(DropdownMenu): pa11y issues

- app/src/components/common/Loading/Loading.tsx
- app/src/components/listView/Kpi/Kpi.tsx
- app/src/lib/utils/assetInventory.tsx
- app/src/lib/utils/listView.tsx
- docs/guides/theming/ThemeSample.tsx
- packages/core/src/components/Box/Box.tsx
- packages/core/src/components/Card/Card.stories.tsx
- packages/core/src/components/Card/Card.tsx
- packages/core/src/components/Forms/Adornment/Adornment.stories.tsx
- packages/core/src/components/Forms/FormElement/FormElement.stories.tsx
- packages/core/src/components/Forms/WarningText/WarningText.tsx
- packages/core/src/components/Input/Input.tsx
- packages/core/src/components/Kpi/Kpi.stories.tsx
- packages/core/src/components/Stack/Stack.stories.tsx
- templates/AssetInventory/utils.tsx
- templates/ListView/Kpi/Kpi.tsx
- templates/ListView/utils.tsx
- Pa11y issues fixed on the card component.
- Consequently the Pa11y issues with the KPI and stack components were also fixed.
- `semantic` prop updated to `color` for icons since the former is deprecated.
> chore: fix pa11y issues on card, stack, and kpi

- packages/viz/src/components/BaseChart/BaseChart.tsx
- I simplified the chart width and height logic because we don't need all this code after all. Also, the following was detected on storybook when changing the theme on the line, bar and donut charts:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/042d1ce4-d3dd-44d7-b707-bdc6c46c3638
> fix(BaseChart): chart width and height

- packages/core/src/components/BaseDropdown/BaseDropdown.tsx
- packages/core/src/components/ColorPicker/ColorPicker.stories.tsx
- packages/core/src/components/ColorPicker/ColorPicker.tsx
- packages/core/src/components/ColorPicker/SavedColors/SavedColors.tsx
- packages/core/src/components/Tag/Tag.tsx
Color picker and base dropdown pa11y issues fixed:
- The base dropdown component was also fixed since it was leading to accessibility issues on the color picker component. The `aria-controls` was transferred to the base dropdown root. This also fixes some pa11y issues on other stories.
> fix: pa11y issues in color picker and base dropdown components

- .github/workflows/tests-applitools.yml
Going back to running applitools on a dev server since using a build leads to weird behaviours: missing CSS on baselines.
> ci(applitools): run applitools on dev server

- packages/core/src/components/FileUploader/DropZone/DropZone.styles.tsx
- packages/core/src/components/FileUploader/DropZone/DropZone.test.tsx
- packages/core/src/components/FileUploader/DropZone/DropZone.tsx
- packages/core/src/components/FileUploader/FileUploader.test.tsx
The accessibility issues for the file uploader component were fixed:
- All the logic from the `div` with `role="button"` was transferred to the `input` component to only have one interactive element. The tests were updated because of this change.
- The unnecessary `aria-label` from the label/description container was removed.
- I also made a small change to the styling in order for the text inside the file uploader to only take two lines like on DS.
> fix(FileUploader): fix a11y issues

- packages/core/src/components/Avatar/Avatar.tsx
- packages/core/src/components/Button/Button.tsx
- packages/core/src/components/Carousel/Carousel.stories.tsx
- packages/core/src/components/DropDownMenu/DropDownMenu.tsx
- packages/core/src/components/GlobalActions/GlobalActions.stories.tsx
- packages/core/src/components/Input/SearchBox.stories.tsx
- packages/core/src/components/OverflowTooltip/OverflowTooltip.stories.tsx
- packages/core/src/components/OverflowTooltip/OverflowTooltip.tsx
- packages/core/src/components/TextArea/TextArea.stories.tsx
- packages/core/src/components/Tooltip/Tooltip.stories.tsx
- packages/core/src/components/Tooltip/Tooltip.styles.tsx
HvTooltip (actually MuiTooltip) passes aria-label to the tooltip target We shouldn't be wrapping it around divs
- Explicitly remove `aria-label` from OverflowTooltip, as it's incorrect & redundant
- Add roles to elements in HvTooltip samples
- Also remove some redundant/incorrect `aria-labels`
> fix(a11y): tooltip labels

- packages/core/src/components/TimePicker/TimePicker.stories.tsx
- packages/core/src/components/TimePicker/TimePicker.tsx
- Missing `aria-labelledby` and `aria-describedby` added to the base dropdown on the time picker component. This was leading to accessibility issues on the query builder.
- I removed the `aria-label` from the time picker stories because since the `label` is set it shouldn't necessary to have both. They were previously added to fix the accessibility issues on the time picker stories. This PR fixes these previous issues without having the need to set both the `aria-label` and `label`.
> fix(TimePicker): fix a11y issues

- docs/guides/layout/Layout.stories.mdx
- docs/guides/layout/Layout.tsx
- packages/core/src/components/Container/Container.tsx
- packages/core/src/components/Grid/Grid.tsx
- packages/core/src/components/SimpleGrid/SimpleGrid.styles.tsx
- packages/core/src/components/SimpleGrid/SimpleGrid.tsx
- Layout page added to the docs.
- The grid docs page was updated because the wrong breakpoints values were used.
- `classes` prop extracted from the simple grid component because it was added to the root component.
> docs: layout page added

- docs/guides/theming/Spacing.tsx
- docs/guides/theming/Theming.stories.mdx
- docs/guides/theming/WhiteLabeling.tsx
- packages/code-editor/src/components/CodeEditor/CodeEditor.stories.tsx
- packages/core/src/components/AppSwitcher/AppSwitcher.styles.tsx
- packages/core/src/components/Banner/BannerContent/BannerContent.styles.tsx
- packages/core/src/components/Calendar/CalendarNavigation/ComposedNavigation/ComposedNavigation.styles.tsx
- packages/core/src/components/Carousel/Carousel.styles.ts
- packages/core/src/components/FilterGroup/FilterContent/FilterContent.styles.tsx
- packages/core/src/components/InlineEditor/InlineEditor.styles.tsx
- packages/core/src/components/Input/Input.stories.tsx
- packages/core/src/components/Pagination/Select.styles.tsx
- packages/core/src/components/Table/TableHeader/TableHeader.styles.tsx
- packages/core/src/components/TimeAgo/TimeAgo.stories.tsx
- packages/core/src/components/TimePicker/TimePicker.styles.ts
- packages/core/src/components/VerticalNavigation/VerticalNavigation.styles.tsx
- packages/styles/src/makeTheme.ts
- packages/styles/src/theme.ts
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/ds5.ts
- packages/styles/src/types.ts
- packages/styles/src/utils.ts
- packages/viz/src/components/BarChart/stories/customTooltip.ts
- packages/viz/src/components/ConfusionMatrix/ConfusionMatrix.styles.tsx
Our `theme.spacing` utility isn't consistent between a single `number` argument and array of `number`.
```ts
theme.spacing(2); // 16px (multiplies value by 8px base)
theme.spacing([2]) // 2px (converts to `px`)
```
This is confusing, and works differently from the previous v4 utility (and MUI's). Furthermore, having to use an array instead of extra arguments is unnecessary, and differs from our previous utility.
This PR:
- allows passing multiple args with behaviour same as passing a single argument
- adds TS completions for the breakpoints
`theme.spacing` with array argument is left as-is
```ts
theme.spacing(2, 4); // 16px 32px
theme.spacing(2, "md", "inherit"); // 16px 16px inherit
```
> feat(theme): improve theme.spacing

- packages/styles/src/themes/ds5.ts
DS3 theme has on the header-shadow property the shadow constant set while that same property on DS5 is set to "none" causing the header to not have a shadow as defined on DS mocks.
> fix(Theme): link shadow constant to theme header shadow property

- packages/core/src/components/GlobalActions/GlobalActions.stories.tsx
- packages/core/src/components/GlobalActions/GlobalActions.styles.tsx
`GlobalActions` grows according to the content, but its `::before` element which pushes the content down doesn't (has fixed width)
Example:
> fix(GlobalActions): empty space same as container

- packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.tsx
When the VerticalNavigation component is collapsed, the items with children would still have reference to an ID of the hvtreeview which doesn't exist since in this mode a popup is used instead.
`Invalid ARIA attribute value: aria-controls="hvtreeview3-8-group"`
> fix(VerticalNavigation): fix invalid 'aria-controls' attribute value

- packages/core/src/components/Drawer/Drawer.tsx
The close icon role was updated to `none` to fix a11y issue on the flow component.
> fix(Drawer): close icon role updated to none to fix a11y issue

- packages/core/src/components/Dropdown/Dropdown.test.tsx
- packages/core/src/components/Dropdown/List/List.tsx
- packages/core/src/components/FilterGroup/FilterGroup.test.tsx
- packages/core/src/components/List/List.tsx
Change `HvList` roles to be `list`+`listem` when selectors are enabled, avoiding nested interactible elements
Also aligns `HvList` items (had a random`5px` padding 🤷 )
> fix(Dropdown): role review & alignment

- .github/actions/install-dependencies/action.yml
- README.md
- bump internal CI usage to `node@18`
- updated README with support version
- everything seems to be working fine 👌
> ci: bump to node@18

- packages/core/src/components/Table/TableHeader/TableHeader.tsx
- packages/core/src/components/Table/hooks/useTable.ts
- packages/core/src/components/Table/stories/TableHooks/TableHooks.tsx
- packages/core/src/components/Table/stories/storiesUtils.tsx
- `id` added to the table headers
- `headers` added to the table cells
- Table headers that were rendered with `display: none` are no longer rendered because this breaks the relationship between table headers and cells:
- Because of this the `groupColumnMostRight` class was overridden to not remove the right border on the last child (which is added by default).
> fix(Table): a11y issues in grouped headers

- .storybook/manager-head.html
- package.json
- scripts/storybook-title/index.js
- This [PR](https://github.com/lumada-design/hv-uikit-react/pull/3702) was not able to fix the following problem:
- In this PR the title is changed directly on the `dist` folder by running a script after building the docs. I saw Fluent UI using this method to update their title. Unfortunately, from what I've seen, Storybook doesn't have a better way of doing this.
> docs: document title fixed

- .storybook/blocks/DocsContainer.tsx
- CONTRIBUTING.md
- docs/foundation/colors/Colors.stories.mdx
- docs/guides/layout/Layout.stories.mdx
- docs/guides/provider/Provider.stories.mdx
- docs/guides/styling/Customization.stories.mdx
- docs/guides/theming/WhiteLabeling.stories.mdx
- docs/guides/visualizations/Visualizations.stories.mdx
- docs/overview/GetStarted.stories.mdx
- docs/overview/migration/MigrationV3.stories.mdx
- docs/overview/migration/MigrationV4.stories.mdx
- docs/overview/migration/MigrationV5.stories.mdx
- docs/overview/status/ProjectStatus.stories.mdx
- packages/core/src/components/Table/stories/TableHooks/TableHooks.stories.mdx
- packages/core/src/components/Table/stories/TableRenderers/TableRenderers.stories.mdx
- "Simple Grid" sample in the layout page fixed: breakpoints were undefined
- "Packages" removed from the "Project Status" table of contents since this section doesn't exist
- Wrong URLs fixed
- Links fixed in the docs:
- Anchor links to navigate to a page section were opening a new iframe
- Links linking to other storybook pages were broken and leading to "Not found" pages
> fix: layout page and links fixed in docs

- .github/workflows/tests-a11y.yml
- scripts/a11y-report/index.js
- `http-server` replaced by `serve` because the workflow would get stuck on this step
- `a11y` script updated to copy CSS file inside a sub-folder
With these changes, the report is deployed as expected: https://lumada-design.github.io/uikit-a11y/
> chore: a11y workflow and script fixed

- packages/core/src/components/DatePicker/DatePicker.stories.tsx
- packages/core/src/components/DatePicker/DatePicker.tsx
- Adds `expanded` & `defaultExpanded` props to control DatePicker open/closed state
- prop names aligned with other dropdown-based components
- Improve typings
Closes #3677. Closes #3686
> feat(DatePicker): add controllable expanded props

- packages/lab/src/components/Flow/Flow.tsx
- packages/lab/src/components/Flow/FlowContext/FlowContext.tsx
- packages/lab/src/components/Flow/Node/Node.styles.tsx
- packages/lab/src/components/Flow/Node/Node.tsx
- packages/lab/src/components/Flow/stories/Flow.stories.tsx
- packages/lab/src/components/Flow/stories/Tron.tsx
Added node actions: 
- A flow can have default actions (set at the Flow level) that all nodes will have (delete, duplicate, ...)
- The default actions will appear above the node when it's hovered
- A node type can have extra actions defined at the node level
- It's possible to set the `maxVisibleActions` on each node
> feat(Flow): add Node actions

- packages/core/src/components/Dialog/Actions/Actions.tsx
- packages/core/src/components/Dialog/Dialog.tsx
- packages/core/src/components/Dialog/Title/Title.tsx
- packages/core/src/components/Dialog/context.ts
Simplifies Dialog internals:
- Remove `slots` overrides with seems to be adding nothing 🤷 and introduces a flicker when `onClose` isn't memoized
- the backdrop color override is done with `slotProps`
- Replace `withTooltip` with `HvTooltip`. `HvTooltip` already handles conditionally showing the tooltip
- Remove `wrappedClose` in favour of inline calls. There's fewer calls to `onClose`, and we weren't respecting the `onClose` API in `wrappedClose`
- Refactor `fullscreen` calls and passing it to children.
- We're injecting props into components that don't accept that prop (except for `HvDialogActions`) and then deleting it - refactored into a context. 
- Deprecated `fullscreen` in `HvDialogActions`
> refactor(Dialog): slots, tooltip usage, context

- package-lock.json
- package.json
- packages/lab/package.json
- packages/lab/src/components/Flow/DroppableFlow.tsx
- packages/lab/src/components/Flow/Flow.tsx
- packages/lab/src/components/Flow/Node/Node.tsx
- packages/lab/src/components/Flow/Sidebar/Sidebar.tsx
- packages/lab/src/components/Flow/Sidebar/SidebarGroup/SidebarGroup.tsx
- packages/lab/src/components/Flow/Sidebar/SidebarGroup/SidebarGroupItem/DraggableSidebarGroupItem.tsx
- packages/lab/src/components/Flow/Sidebar/utils.ts
- packages/lab/src/components/Flow/hooks/index.ts
- packages/lab/src/components/Flow/index.ts
- packages/lab/src/components/Flow/stories/Flow.stories.tsx
- packages/lab/src/components/Flow/stories/Usage.stories.mdx
- packages/lab/src/components/Flow/stories/Visualizations/Visualizations.tsx
This PR includes several fixes for the flow component:
- `useFlowNode` exported to be used externally by users
- the custom drag overlay for our sidebar was moved to the sidebar component in order to not appear when a custom sidebar is used
- unnecessary props (`outputs` and `inputs`) removed  from the `HvFlowNodeProps`
- when an unknown node type is dragged to the canvas, the node is not added to the flow and an error is thrown
- the node type is no longer set in the draggable item id and was moved to a specific property called `type`: this was leading to errors when different draggable items with the same node type were created
Other updates:
- `reactflow` package upgraded to the latest version
- docs styles deduped
- the order of the flow types was reversed: the most used types are …
> fix(Flow): several fixes 

- packages/lab/src/components/Flow/DroppableFlow.tsx
- packages/lab/src/components/Flow/Flow.tsx
- packages/lab/src/components/Flow/Sidebar/SidebarGroup/SidebarGroup.tsx
- packages/lab/src/components/Flow/Sidebar/SidebarGroup/SidebarGroupItem/DraggableSidebarGroupItem.tsx
- packages/lab/src/components/Flow/Sidebar/utils.ts
- packages/lab/src/components/Flow/types/flow.ts
In this PR, the `data` prop was added to the `HvFlowNode` metadata. This prop is then used to set the initial node `data` when the node is added to the flow.
> feat(Flow): data added to flow node metadata

- .github/workflows/static-checks.yml
- add `npm run build` to our checks
- parallelise Static tests, Unit tests, and Build
- checks take half as long (~9m > ~5m) 🚀
> ci: test build on PR/Nightly

- docs/overview/migration/MigrationV5.stories.mdx
- packages/core/src/components/QueryBuilder/Context.tsx
- packages/core/src/components/QueryBuilder/QueryBuilder.stories.tsx
- packages/core/src/components/QueryBuilder/QueryBuilder.tsx
- packages/core/src/components/QueryBuilder/index.ts
- packages/core/src/components/QueryBuilder/types.ts
Should we add the HV or HVQuerybuilder prefix to there subcomponents?
> fix(QueryBuilder): export types and default values

- packages/core/src/components/Forms/WarningText/WarningText.styles.tsx
- packages/core/src/components/Forms/WarningText/WarningText.tsx
- packages/styles/src/themes/ds3.ts
The warning text was aligned with DS 5.7:
- The text color was updated to `negative120` and the variant to `caption1`
- The icon container's size was updated to `24px`:
- Using Figma I concluded that I had to use the `XS` size for the icon but change the container's size to `24px` because [this icon size usually uses `32px` for the container according to DS](https://designsystem.hitachivantara.com/6c705d900/p/31e481-dawn-icons/t/28a0f9). I found this a bit strange since I had to override the default specs for the icons' sizes. 
- I did not update the border and icon color since they were already using `negative`. 
I also fixed the following:
- I removed the `paddingLeft` that was unnecessary for the `warningText`
- The `paddingTop` value for `topGutter` in DS3 was updated since the text …
> feat(WarningText): align with DS 5.7

- packages/lab/src/components/Flow/stories/Base/Dashboard.tsx
- packages/lab/src/components/Flow/stories/Base/KPI.tsx
- packages/lab/src/components/Flow/stories/Base/LineChart.tsx
- packages/lab/src/components/Flow/stories/Base/MLModelDetection.tsx
- packages/lab/src/components/Flow/stories/Base/MLModelPrediction.tsx
- packages/lab/src/components/Flow/stories/Base/Table.tsx
- packages/lab/src/components/Flow/stories/Base/Tron.tsx
- packages/lab/src/components/Flow/stories/Base/index.tsx
- packages/lab/src/components/Flow/stories/Flow.stories.tsx
- packages/lab/src/components/Flow/stories/InitialState/index.tsx
- packages/lab/src/components/Flow/stories/Main/index.tsx
- packages/lab/src/components/Flow/stories/Visualizations/BarChart.tsx
- packages/lab/src/components/Flow/stories/Visualizations/Filter.tsx
- packages/lab/src/components/Flow/stories/Visualizations/JsonInput.tsx
- packages/lab/src/components/Flow/stories/Visualizations/LineChart.tsx
- packages/lab/src/components/Flow/stories/Visualizations/index.tsx
- packages/lab/src/components/types/global.d.ts
The Flow samples were refactored because they were confusing for users and the available code was useless sometimes:
- Each sample has its own folder to reduce confusion
- The imports were updated to import from the `lab` package instead of an absolute path (when possible)
- The samples show the code in a `raw` format: the code samples are now more legible and useful
- Comments were added with a link to find the code for the values and components that can only be imported from absolute paths
> docs(Flow): refactor samples

- app/.eslintrc
- app/src/App.tsx
- app/src/components/assetInventory/CardView/CardView.tsx
- app/src/components/assetInventory/ListView/ListView.tsx
- app/src/components/common/Container/Container.tsx
- app/src/components/common/Header/Header.tsx
- app/src/components/common/Tutorial/Step.tsx
- app/src/components/common/index.ts
- app/src/components/detailsView/Table/Table.tsx
- app/src/components/listView/Kpi/Kpi.tsx
- app/src/components/listView/Table/Table.tsx
- app/src/generator/CodeEditor/CodeEditor.tsx
- app/src/generator/Colors/Colors.tsx
- app/src/generator/Content.tsx
- app/src/generator/FontFamily/FontFamily.tsx
- app/src/generator/FontSizes/FontSizes.tsx
- app/src/generator/Radii/Radii.tsx
- app/src/generator/Sidebar/Sidebar.tsx
- app/src/generator/Sizes/Sizes.tsx
- app/src/generator/Spacing/Spacing.tsx
- app/src/generator/Typography/Typography.tsx
- app/src/generator/Zindices/Zindices.tsx
- app/src/lib/context/NavigationContext.tsx
- app/src/lib/hooks/useNavigation.ts
- app/src/lib/routes.tsx
- app/src/pages/Components/Components.tsx
- app/src/pages/Instructions/Instructions.tsx
- app/tsconfig.json
- helps organising imports
- makes it clearer it's an internal import and not an external import
- most UI frameworks use this
> refactor(app): use `~/` prefix for package imports

- packages/lab/src/components/Flow/DroppableFlow.tsx
- packages/lab/src/components/Flow/Node/Node.styles.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/BarChart.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/LineChart.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/Precipitation.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/data.ts
- packages/lab/src/components/Flow/stories/CustomDrop/index.tsx
- packages/lab/src/components/Flow/stories/Dynamic/index.tsx
- packages/lab/src/components/Flow/stories/Flow.stories.tsx
In this PR, a new callback called `onDndDrop` was created to override our custom drop event:
- This callback is called when a node is dropped in the flow.
- When defined, the user is responsible for adding nodes to the flow.
- This callback is called when `HvFlowSidebar` is used or a custom sidebar was created using Dnd Kit. When a custom sidebar is created using the native HTML drag and drop API, the user should use the native `onDrop` callback.
- This is why I called it  `onDndDrop`. If you think this should be changed, let me know.  
- This callback returns the event and the node to be added to the flow.
> feat(Flow): customise drop event

- packages/core/src/components/DropDownMenu/DropDownMenu.stories.tsx
- packages/core/src/components/DropDownMenu/DropDownMenu.styles.tsx
- packages/core/src/components/DropDownMenu/DropDownMenu.tsx
DS 5.7 alignement for the `DropdownMenu`:
- Border color changed to `secondary`
- The rest was already updated in this [PR](https://github.com/lumada-design/hv-uikit-react/pull/3755)
> feat(DropdownMenu): align with DS 5.7

- packages/lab/src/components/Flow/Sidebar/Sidebar.tsx
- packages/lab/src/components/Flow/stories/Base/index.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/index.tsx
- packages/lab/src/components/Flow/stories/Dynamic/index.tsx
- packages/lab/src/components/Flow/stories/InitialState/index.tsx
- packages/lab/src/components/Flow/stories/Main/index.tsx
- packages/lab/src/components/Flow/stories/Visualizations/index.tsx
The drag overlay position was fixed on storybook docs mode:
- For this, a new `dragOverlayProps` prop was added to the `HvFlowSidebar`
> feat(FlowSidebar): drag overlay customisation and fix drag overlay position in docs

- packages/core/src/components/Dropdown/Dropdown.test.tsx
- packages/core/src/components/Dropdown/List/List.tsx
- disable "Apply" button in Dropdown when there are no changes to apply
- compares `selected` state in changed elements. uses `id` as comparator, falling back to `label` if one isn't defined
- addresses #3763
> fix(Dropdown): disable Apply button when no changes are made

- packages/lab/src/components/Flow/DroppableFlow.tsx
- packages/lab/src/components/Flow/Node/BaseNode.tsx
- packages/lab/src/components/Flow/Node/Node.tsx
- packages/lab/src/components/Flow/stories/Usage.stories.mdx
- packages/lab/src/components/Flow/types/flow.ts
The property `maxConnections` was added to the node's outputs and inputs to define the maximum number of connections allowed.
> feat(Flow): max connections

- packages/lab/src/components/Flow/Node/Node.tsx
- packages/lab/src/components/Flow/Sidebar/Sidebar.styles.tsx
- packages/lab/src/components/Flow/Sidebar/Sidebar.tsx
- packages/lab/src/components/Flow/Sidebar/SidebarGroup/SidebarGroup.tsx
- packages/lab/src/components/Flow/Sidebar/utils.ts
- packages/lab/src/components/Flow/stories/Base/NoGroup/LineChart.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/MLModelPrediction.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/Tron.tsx
- packages/lab/src/components/Flow/stories/Flow.stories.tsx
- packages/lab/src/components/Flow/stories/NoGroups/index.tsx
- packages/lab/src/components/Flow/stories/Usage.stories.mdx
- packages/lab/src/components/Flow/types/flow.ts
- Make groups optional in the Flow component
- If `nodeGroups` is provided any node that doesn't have a `groupId` will be placed on a "Default" group
- the "Default" group is customizable via the new `defaultGroupProps` on the `Sidebar` component
- If `nodeGroups`is not provided then all the nodes are listed ungrouped on the sidebar
- Since there are no groups to fetch data from (like the group name, group color, etc), a new `nodeDefaults` prop was added to the `Node` component that allows for passing this values
- Updated the Flow docs:
- Added relevant samples
- Moved the Flow `Usage` documentation to the `Guides` section
> feat(Flow): decouple flow from node groups

- packages/lab/src/components/Flow/Node/BaseNode.tsx
- packages/lab/src/components/Flow/Node/Parameters/Select.tsx
- packages/lab/src/components/Flow/Node/Parameters/Text.tsx
- packages/lab/src/components/Flow/stories/Base/Tron.tsx
The following fixes were implemented:
- [`nodrag`](https://reactflow.dev/api-reference/types/node-props#notes) class added to the text and select params to prevent dragging the node within the fields: because of this it wasn't possible to select the text inside the input for example.
- [`nowheel`](https://reactflow.dev/api-reference/types/node-props#notes) class added to the base node to disable the default canvas pan behaviour when scrolling inside the node: without this the canvas was zooming in or out when scrolling inside the node.
- `maxHeight` added to the select param to avoid having huge list.
This can be tested with the "Tron" node inside the "Main" sample.
> fix(Flow): prevent drag and zoom on nodes

- packages/styles/src/theme.ts
- packages/styles/src/utils.ts
The `spacing` util was using the `space` token. This means that in DS3 this util was always using the DS5 values. Also, if someone was providing custom `space` values to the theme, the `spacing` util  was not using them. This was fixed by using the CSS vars instead.
> fix(theme): spacing

- packages/lab/src/components/Flow/Node/Parameters/Select.tsx
- packages/lab/src/components/Flow/Node/Parameters/Text.tsx
- packages/lab/src/components/Flow/stories/Base/Dashboard.tsx
- packages/lab/src/components/Flow/stories/Base/KPI.tsx
- packages/lab/src/components/Flow/stories/Base/LineChart.tsx
- packages/lab/src/components/Flow/stories/Base/MLModelDetection.tsx
- packages/lab/src/components/Flow/stories/Base/MLModelPrediction.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/LineChart.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/MLModelPrediction.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/Tron.tsx
- packages/lab/src/components/Flow/stories/Base/Table.tsx
- packages/lab/src/components/Flow/stories/Base/Tron.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/BarChart.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/LineChart.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/Precipitation.tsx
- packages/lab/src/components/Flow/stories/Dynamic/utils.tsx
- packages/lab/src/components/Flow/stories/Visualizations/BarChart.tsx
- packages/lab/src/components/Flow/stories/Visualizations/Filter.tsx
- packages/lab/src/components/Flow/stories/Visualizations/JsonInput.tsx
- packages/lab/src/components/Flow/stories/Visualizations/LineChart.tsx
- packages/lab/src/components/Flow/types/flow.ts
- Multiple select param added by using the `multiple` prop:
- Prop `value` removed from `HvFlowNodeParam` since it wasn't used anywhere
- Visualisations styling Improved in the flow samples
- Missing `NodeProps` type added to nodes in samples
> feat(Flow): multiple select param

- packages/lab/src/components/Flow/Node/BaseNode.tsx
`uid` is used when creating a new node using the duplicate action to avoid having duplicated node ids:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/26357301-da11-4bab-888a-8b92913fec71
> fix(Flow): duplicate node id

- packages/core/src/components/Table/hooks/usePagination.ts
Add missing `useHvPagination` plugin order, which can lead to wrong filtering/sorting state
> fix(useHvPagination): add missing pluginOrder restrictions

- .config/applitools.config.js
The `protocolTimeout` was increased (defaults to 3min) to try to avoid these errors on Applitools:
`Error when reading stories: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.`
> chore: increase applitools timeout

- packages/core/src/components/Button/Button.tsx
- packages/core/src/components/Calendar/CalendarUtils.test.tsx
- packages/core/src/components/Calendar/utils.tsx
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Table/stories/TableSamples/TableCompleteSample.tsx
- packages/core/src/components/TreeView/internals/DescendantProvider.tsx
- packages/core/src/components/TreeView/internals/TreeViewProvider.tsx
- packages/core/src/components/Typography/utils.ts
- packages/core/src/components/VerticalNavigation/TreeView/descendants.tsx
- packages/core/src/env.d.ts
- packages/core/src/hooks/useControlled.ts
- packages/lab/src/components/Flow/DroppableFlow.tsx
- packages/lab/src/components/types/global.d.ts
- tsconfig.json
- add vite typing references
- use import.meta.env instead of process.env
- wrap missing console warnings
- remove unused `isValidLocale`
> chore: vite typings & use import.meta.env

- app/src/pages/Flow/DashboardPreview/Renderers/Renderer.tsx
- app/src/pages/Flow/DashboardPreview/Renderers/Table.tsx
- app/src/pages/Flow/DashboardPreview/utils.tsx
- app/src/pages/Flow/Flow.tsx
- app/src/pages/Flow/Nodes/Table.tsx
- app/src/pages/Flow/Nodes/index.ts
Added a `Table` node to the `Flow` in the app. I think it gives it a bit more variety and is useful to illustrate scenarios with tables in dashboards. The node itself has a filter for a specific field (that part could be improved, probably) that's used to filter what is shown on the table in the dashboard.
> chore: add Table node to the app flow

- packages/icons/lib/IconBase.tsx
- packages/icons/src/utils/converter/generateComponent.ts
- packages/icons/tsconfig.json
- ~add color completions~ there's issues with `dts` linking to styles packages
- reduce types size from 109kB to 38kB
- cleanup tsconfig
> chore(Icons): improve color types & generation

- packages/core/src/components/CheckBox/CheckBox.stories.tsx
- packages/core/src/components/ColorPicker/ColorPicker.stories.tsx
- packages/core/src/components/DatePicker/DatePicker.stories.tsx
- packages/core/src/components/Dropdown/Dropdown.stories.tsx
- packages/core/src/components/Input/Input.stories.tsx
- packages/core/src/components/Radio/Radio.stories.tsx
- packages/core/src/components/Switch/Switch.stories.tsx
- The color picker samples are no longer expanded by default because it was quite difficult to use this page when they were all expanded:
- Applitools opens the pickers before taking the screenshots
- Samples with form errors were uniformized and fixed:
- The checkbox sample was throwing an error
- Problems with the font color in dark mode
> docs: color picker samples not expanded

- app/src/pages/Flow/config.tsx
- packages/lab/src/components/Flow/Node/Parameters/Select.tsx
- When a select parameter with `multiple={false}` was used on a node and a value was selected, the value was added as an array on the node `data`. This doesn't make sense as it should be added as a string. This was a regression from this [PR](https://github.com/lumada-design/hv-uikit-react/pull/3801) when the multiple select was added.
> fix(Flow): set value as string if select is not multiple

- packages/core/src/components/Accordion/Accordion.stories.tsx
- packages/core/src/components/BreadCrumb/BreadCrumb.stories.tsx
- packages/core/src/components/BulkActions/BulkActions.stories.tsx
- packages/core/src/components/Card/Card.stories.tsx
- packages/core/src/components/CheckBoxGroup/CheckBoxGroup.stories.tsx
- packages/core/src/components/DatePicker/DatePicker.stories.tsx
- packages/core/src/components/FilterGroup/FilterGroup.stories.tsx
- packages/core/src/components/Input/SearchBox.stories.tsx
- packages/core/src/components/MultiButton/MultiButton.stories.tsx
- packages/core/src/components/Pagination/Pagination.stories.tsx
- packages/core/src/components/TagsInput/TagsInput.stories.tsx
- packages/core/src/components/TextArea/TextArea.stories.tsx
- packages/core/src/components/VerticalNavigation/VerticalNavigation.stories.tsx
- packages/lab/src/components/StepNavigation/StepNavigation.stories.tsx
- packages/viz/src/components/BarChart/stories/BarChart.stories.tsx
- packages/viz/src/components/DonutChart/DonutChart.stories.tsx
- packages/viz/src/components/LineChart/LineChart.stories.tsx
Duplicate `id`s in samples is leading to issues. In most cases, the `id`s are not necessary - this PR removes those ids.
> docs: remove duplicated & unnecessary ids

- packages/icons/lib/IconBase.tsx
- tsconfig.json
The `paths` defined in the global `tsconfig.json` file is leading to wrongly replaced imports (see https://github.com/lumada-design/hv-uikit-react/pull/3828#pullrequestreview-1739496099)
This error isn't happening in most cases, because each package has a `paths` override (which squashes those defined in the root `tsconfig.json`), but is happening in `shared` and `icons` package
We alternatively override (do `paths: {}`) for every package, but we'd be essentially overriding something that (probably) shouldn't be there in the first place.
Let me know if there's something global `paths` is being used for - according to our CI (and manual checks) it looks like it isn't
> build: remove paths override

- packages/core/src/components/QueryBuilder/Context.tsx
- packages/core/src/components/QueryBuilder/QueryBuilder.tsx
- packages/core/src/components/QueryBuilder/Rule/Attribute/Attribute.tsx
- packages/core/src/components/QueryBuilder/Rule/Operator/Operator.tsx
- packages/core/src/components/QueryBuilder/Rule/Rule.tsx
- packages/core/src/components/QueryBuilder/Rule/Value/BooleanValue/BooleanValue.tsx
- packages/core/src/components/QueryBuilder/Rule/Value/DateTimeValue/DateTimeValue.tsx
- packages/core/src/components/QueryBuilder/Rule/Value/NumericValue/NumericValue.tsx
- packages/core/src/components/QueryBuilder/Rule/Value/TextValue/TextValue.tsx
- packages/core/src/components/QueryBuilder/Rule/Value/Value.tsx
- packages/core/src/components/QueryBuilder/RuleGroup/RuleGroup.tsx
- packages/core/src/components/QueryBuilder/stories/InitialQuery.tsx
- packages/core/src/components/QueryBuilder/stories/QueryBuilder.stories.tsx
- `disableConfirmation` prop added to the `HvQueryBuilder` to be used when the user wants to opt-out of the confirmation dialogs shown before removing rules and rule groups:
- Defaults to `false` (current behaviour)
- "InitialQuery" sample updated to control the `disableConfirmation` prop
<s>➡️❓ Let me know if you think the prop should have another name.</s> => Updated to `disableConfirmation`
> feat(QueryBuilder): opt-out of confirmation dialogs

- app/src/pages/Flow/Nodes/BarChart.tsx
- app/src/pages/Flow/Nodes/Dashboard.tsx
- app/src/pages/Flow/Nodes/DonutChart.tsx
- app/src/pages/Flow/Nodes/Kpi.tsx
- app/src/pages/Flow/Nodes/LineChart.tsx
- app/src/pages/Flow/Nodes/Table.tsx
- app/src/pages/Flow/utils.tsx
- packages/lab/src/components/Flow/Node/Node.tsx
- packages/lab/src/components/Flow/stories/Base/Asset.tsx
- packages/lab/src/components/Flow/stories/Base/Dashboard.tsx
- packages/lab/src/components/Flow/stories/Base/KPI.tsx
- packages/lab/src/components/Flow/stories/Base/LineChart.tsx
- packages/lab/src/components/Flow/stories/Base/MLModelDetection.tsx
- packages/lab/src/components/Flow/stories/Base/MLModelPrediction.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/Asset.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/LineChart.tsx
- packages/lab/src/components/Flow/stories/Base/NoGroup/MLModelPrediction.tsx
- packages/lab/src/components/Flow/stories/Base/Table.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/BarChart.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/LineChart.tsx
- packages/lab/src/components/Flow/stories/CustomDrop/Precipitation.tsx
- packages/lab/src/components/Flow/stories/DynamicHandles/Asset.tsx
- packages/lab/src/components/Flow/stories/DynamicHandles/index.tsx
- packages/lab/src/components/Flow/stories/Flow.stories.tsx
- packages/lab/src/components/Flow/stories/Usage.stories.mdx
- packages/lab/src/components/Flow/stories/Visualizations/BarChart.tsx
- packages/lab/src/components/Flow/stories/Visualizations/Filter.tsx
- packages/lab/src/components/Flow/stories/Visualizations/JsonInput.tsx
- packages/lab/src/components/Flow/stories/Visualizations/LineChart.tsx
- packages/lab/src/components/Flow/types/flow.ts
- The node `inputs` and `outputs` were transferred to the component's props:
- They were previously added to `meta` because of the `isValidConnection` validation in the `HvDroppableFlow`. This is no longer needed since this [PR](https://github.com/lumada-design/hv-uikit-react/pull/3784).
- Making this change enables to create `inputs` and `outputs` dynamically. 
- The node type `meta` is now used only for the sidebar.
- Flow docs updated:
- Usage page
- Dynamic handles sample added
> fix(Flow): transfer node inputs/outputs to props

- .github/actions/build-artifacts/action.yml
- .github/workflows/nightly.yml
- .github/workflows/pr.yml
- .github/workflows/static-checks.yml
- .github/workflows/tests-a11y.yml
- .github/workflows/tests-applitools.yml
- scripts/a11y-report/index.js
- `a11y` tests added to the PR workflow:
- The report is not published: the report is archived on the workflow run and can be downloaded if needed
- The workflow breaks if any `a11y` errors are found
- The nightly did not change: the workflow doesn't break if issues are found and the report is published
> chore: a11y tests added to PR workflow

- packages/core/src/components/CheckBox/CheckBox.stories.tsx
- packages/core/src/components/DatePicker/DatePicker.stories.tsx
- packages/core/src/components/Dropdown/Dropdown.stories.tsx
- packages/core/src/components/Grid/Grid.tsx
- packages/core/src/components/Input/Input.stories.tsx
- packages/core/src/components/Radio/Radio.stories.tsx
- packages/core/src/components/Switch/Switch.stories.tsx
- When using `spacing`, `rowSpacing`, or `columnSpacing` as an object, a width is set (`xs`, `sm`, etc...), and the grid is a `container` as well as an `item`, the following MUI error is shown: `MUI: Expected spacing argument to be a number or a string, got [object Object].`. It seems that this is a [MUI limitation](https://github.com/mui/material-ui/issues/29349) and this was leading to unexpected grid behaviours.
- Since this [PR](https://github.com/lumada-design/hv-uikit-react/pull/3533), the error started to appear more frequently because, when `spacing` is set to `auto`, which is the default value, `spacing` is converted to an object (instead of a number like it previously was). I believe this was done to remove the need for `useWidth` and to avoid re-rendering the grid on width …
> fix(Grid): item container spacing

- scripts/a11y-report/index.js
The image was broken. This PR fixes this.
> chore: fix a11y report svg

- .github/workflows/pr-close.yml
- .github/workflows/pr.yml
- packages/core/src/OverflowTooltip/OverflowTooltip.js
- packages/core/src/OverflowTooltip/stories/OverflowTooltip.stories.js
- packages/core/src/OverflowTooltip/tests/tests/OverflowTooltip.test.js
- v3.x workflows fixed: the documentation was not deployed when opening a PR
- Backports part of [this fix](https://github.com/lumada-design/hv-uikit-react/pull/3820) to v3: `HvOverflowTooltip` fixed when `paragraphOverflow` is set to true: the tooltip was not showing.
- I didn't update the line clamp to 3 (instead 2) in this PR since I don't think it's needed. But let me know if you think otherwise.
> fix(OverflowTooltip): paragraph overflow

- packages/styles/src/makeTheme.ts
- packages/styles/src/types.ts
allow `createTheme` and theme types to define or infer the color modes
> chore(styles): infer theme color modes

- packages/core/src/components/Box/Box.tsx
- packages/core/src/components/Section/Section.tsx
- packages/core/src/types/generic.ts
Our polymorphic components weren't inferring the types for the event handlers as shown below. 
https://github.com/lumada-design/hv-uikit-react/assets/43220251/bba7f382-0d90-433f-b349-fe7d80a84395
The problem was in our `PolymorphicComponentRef` type when doing `Omit<React.ComponentPropsWithoutRef<C>, PropsToOmit<C, Props>>`. Using `Omit` in combination with `React.ComponentPropsWithoutRef<C>` was preventing TypeScript of inferring the events types. 
I tried several solutions but they didn't work. In the end, I found [this workaround](https://github.com/microsoft/TypeScript/issues/44596#issuecomment-1447648600) that solved the problem. 
https://github.com/lumada-design/hv-uikit-react/assets/43220251/b2094566-9c0e-4faf-8d97-ee8e0dc46ffd
> fix(types): polymorphic components

- packages/core/src/components/Drawer/Drawer.stories.tsx
- packages/core/src/components/Drawer/Drawer.tsx
I added a story to have a `Drawer` open on top of some content, namely the `GlobalActions` that might have some styles clash with the one's on the `Drawer`. I opted to leave that be checked by Storybook because it might be important to have that tested in case anything changes.
> fix(Drawer): fix incorrect usage of the backdrop

- packages/core/src/types/generic.ts
- packages/styles/src/utils.ts
Fixes:
- The components props were wrongly mapped to CSS vars. 
- Loop problem in the `DeepPartial` type:
> fix: remove components props from CSS vars

- app/src/pages/Flow/Nodes/Dashboard.tsx
- packages/lab/src/components/Flow/FlowContext/NodeMetaContext.tsx
- packages/lab/src/components/Flow/Minimap/Minimap.tsx
- packages/lab/src/components/Flow/Node/BaseNode.styles.tsx
- packages/lab/src/components/Flow/Node/Node.tsx
- packages/lab/src/components/Flow/Node/Parameters/ParamRenderer.tsx
- packages/lab/src/components/Flow/hooks/useFlowNode.ts
- add `useFlowInputNodes`/`useFlowOutputNodes`
- alternative to "parents" hook, that's triggers fewer re-renders
- remove duplicate `useNodeMeta` hook (this one isn't being exported)
- minor refactors/improvements in the typings and utils
> chore(Flow): minor improvements

- packages/core/src/components/QueryBuilder/index.ts
Types `HvQueryBuilderChangedQuery` and `HvQueryBuilderQueryGroup` exported.
> fix(QueryBuilder): export missing types

- docs/foundation/Icons/Sprites.stories.tsx
- docs/foundation/Icons/Usage.stories.tsx
- docs/tests/Icons.stories.tsx
- docs/tests/Uno.stories.tsx
- packages/uno-preset/src/index.ts
- packages/uno-preset/src/theme.ts
- fix UnoCSS plugin spacing units
- `presetRemToPx` must be applied after Uno & Theme presets
- add Storybook "Tests/*" folder for samples **only used** in visual testing
- Add UnoCSS test sample
- move IconLibraryTest samples
> fix(uno): fix spacing units & add Tests/* samples

- .eslintrc
- docs/overview/migration/MigrationV5.stories.mdx
- package-lock.json
- package.json
- Add missing `SemanticVariantTypes` type to types migration table
- sort migration table
- Add more code block in installation guide
- replace `latest` with `5.x` installs for future-proofing
- Add eslint-storybook plugin
> docs: update v5 migration guide

- examples/uikit-app-shell/package.json
Our App Shell example is broken:
- Since v0.18.x `@hitachivantara/app-shell-vite-plugin` has breaking changes. I opened [this PR](https://github.com/lumada-design/hv-uikit-react/pull/3911) to migrate App Shell but the team are still doing tests and don't recommend promoting this version yet. Because of this I fixed the package version.
> chore: fix app shell version in example

- app/src/App.tsx
- app/src/components/common/Container/Container.tsx
- app/src/lib/routes.tsx
- app/src/pages/Flow/DashboardPreview/DashboardPreview.tsx
- app/src/pages/layout/navigation.tsx
- app/src/pages/layout/root.tsx
- decouple generator/header from root element
- `DashboardPreview` doesn't need any of this (and possibly other routes eventually)
- header/content variable spacing
- extra spacing when 2 levels (templates)
- addresses [this issue](https://github.com/lumada-design/hv-uikit-react/pull/3905#pullrequestreview-1786310750)
- addresses excessive padding in some pages
- Add a root layout page (currently empty)
> chore(app): decouple generator/header & variable header height

- app/src/pages/Flow/Nodes/Dashboard.tsx
- packages/lab/src/Flow/index.ts
- packages/lab/src/Flow/nodes/DashboardNode.tsx
- packages/lab/src/Flow/nodes/index.ts
- packages/lab/src/Flow/stories/Base/Dashboard.tsx
- Add `HvDashboardNode`
- Extends `HvFlowNode` and adds the Dialog+Dashboard with a few defaults:
- Apply+Cancel buttons, Dashboard layout+margins, full screen dialog with title + label
- Dashboard preview is user-defined: `previewItems`
- Node content is user-defined: `children`
- Node Inputs/Outputs is user-defined
- Refactor dashboard nodes to use `HvDashboardNode`
> feat(DashboardNode): add node

- packages/core/src/QueryBuilder/Context.tsx
- packages/core/src/QueryBuilder/QueryBuilder.tsx
- packages/core/src/QueryBuilder/Rule/Operator/Operator.tsx
- packages/core/src/QueryBuilder/Rule/Rule.styles.tsx
- packages/core/src/QueryBuilder/Rule/Rule.tsx
- packages/core/src/QueryBuilder/Rule/Value/EmptyValue/EmptyValue.tsx
- packages/core/src/QueryBuilder/Rule/Value/EmptyValue/index.ts
- packages/core/src/QueryBuilder/Rule/Value/Value.tsx
- packages/core/src/QueryBuilder/stories/CustomRenderers.tsx
- packages/core/src/QueryBuilder/stories/QueryBuilder.stories.tsx
- packages/core/src/QueryBuilder/stories/Usage.stories.mdx
- packages/core/src/QueryBuilder/types.ts
- packages/lab/src/Flow/Flow.tsx
- Value renderers are now configurable per operator:
- Previously, if a custom renderer was passed for one of the default attribute types (`boolean`, `numeric`, `text`, `textarea`, and `dateandtime`), the renderer was not used. This was fixed since it should be possible to customise these attribute types.
- As discussed, the `DEFAULT` key can be used in the `renderers` prop to customise the value renderers at a more broad level.  
- ℹ️ I was not able to update the `type` and `operator` props in the `HvQueryBuilderAttribute` and `HvQueryBuilderQueryOperator` types, respectively, to accept all `string` except `DEFAULT`. I added a `console.error` in DEV mode because of this. ❓**Let me know if you know a solution for this.** 
- Previously, when defining a custom renderer for an attribute …
> feat(QueryBuilder): custom operator renderer

- packages/lab/src/Flow/stories/CustomDrop/BarChart.tsx
- packages/lab/src/Flow/stories/CustomDrop/LineChart.tsx
- packages/lab/src/Flow/stories/Visualizations/BarChart.tsx
- packages/lab/src/Flow/stories/Visualizations/Filter.tsx
- packages/lab/src/Flow/stories/Visualizations/JsonInput.tsx
- packages/lab/src/Flow/stories/Visualizations/LineChart.tsx
- The flow samples were refactored to use our internal hooks and simplify the code
- The `JsonInput` node from the "Visualizations" sample was fixed: when new json input nodes were added, the data was not linked to them.
> chore(Flow): samples refactored and simplified

- packages/core/src/QueryBuilder/QueryBuilder.styles.tsx
- packages/core/src/QueryBuilder/QueryBuilder.test.tsx
- packages/core/src/QueryBuilder/RuleGroup/RuleGroup.tsx
- packages/core/src/Typography/Typography.tsx
- New query builder tests added [as requested](https://github.com/lumada-design/hv-uikit-react/pull/3908#pullrequestreview-1789361870)
- Query builder tests updated
- 2 bugs fixed:
- In read only mode, some buttons were not disabled in the query builder
- The `disabled` prop was extracted and not passed down to the typography component
> fix(QueryBuilder): buttons not disabled in read only and tests updated

- packages/core/src/Calendar/Calendar.test.tsx
- The calendar tests started breaking with the new year: this was fixed and should no longer break when the year changes.
> test: fix calendar

- packages/core/src/VerticalNavigation/Header/Header.tsx
- I opted to simply remove the limitation we had on what open icon to use so now we can set an `openIcon` and a `closeIcon` to use in all cases
> feat(VerticalNavigation): allow passing icons to use when in collapsible mode

- packages/core/src/Slider/Slider.stories.tsx
- packages/core/src/Slider/Slider.tsx
- review Slider samples
- merge valid/invalid/readonly/disabled into Variants
- refactor Slider
- dedupe `isSingle` Sliders
- improve typings
- knobClassName no longer exists
- deprecate the (already deprecated) `onBeforeChange`/`onAfterChange`
Applitools changes are expected
> docs(Slider): review samples

- .config/vite.config.ts
- package.json
- packages/code-editor/package.json
- packages/core/package.json
- packages/icons/package.json
- packages/lab/package.json
- packages/shared/package.json
- packages/styles/package.json
- packages/uno-preset/package.json
- packages/viz/package.json
Our packages are CJS by default, but our `.js` files have ESM code. This leads to errors in ESM packages (`type: "module"` in the `package.json`)
Examples of this issue:
- [Minimal NodeJS package](https://stackblitz.com/edit/stackblitz-starters-vwjs5a?file=index.js)
- [App Shell vite configuration](https://stackblitz.com/edit/github-agjraf?file=vite.config.ts) (requires an ESM package)
This PR
- adds the `.mjs` to the ESM files
- adds top-level clean script
- useful to cleanup the `dist` & `package` folders
validated by publishing packages to verdaccio
> build: rename ESM files to `.mjs`

- packages/lab/src/Flow/DroppableFlow.tsx
- `project` replaced by `screenToFlowPosition` since it's now deprecated as mentioned [here](https://github.com/xyflow/xyflow/releases/tag/11.10.0)
> refactor(Flow): replace deprecated project for screenToFlowPosition

- packages/lab/src/Flow/Node/BaseNode.styles.tsx
- packages/lab/src/Flow/Node/BaseNode.tsx
- packages/lab/src/Flow/stories/Usage.stories.mdx
- Added the footer property to allow passing any content to the footer section of the `Node` component.
- Simplified the placing of the handles to remove unnecessary calculations to set it's positioning. 
- Updated docs
> feat(Flow): add footer section to the `BaseNode` component

- packages/core/src/Table/TableCell/TableCell.styles.tsx
- packages/styles/src/themes/ds3.ts
Addresses bug 2 of https://github.com/lumada-design/hv-uikit-react/issues/3933
After:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/28bee0a8-3d70-4d4b-84e4-447289ab1236
> fix(TableCell): transparent background for sorted sticky columns

- packages/core/src/Table/hooks/useResizeColumns.ts
Addresses bug #3 of https://github.com/lumada-design/hv-uikit-react/issues/3933
After:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/5dafac91-7250-4009-84a6-211e5e88a6e2
> fix(Table): stop propagation for resizer

- packages/core/src/Table/TableHeader/TableHeader.tsx
Addresses bug #1 of https://github.com/lumada-design/hv-uikit-react/issues/3933
After:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/5e6f2cbc-63f8-4834-b379-854ddf8eb8dd
> fix(TableHeader): keep header sticky when sticky and resizable

- packages/core/src/DatePicker/DatePicker.test.tsx
- packages/core/src/DatePicker/DatePicker.tsx
Addresses part of https://github.com/lumada-design/hv-uikit-react/issues/3935:
- `onChange` is no longer called when the picker is closed: there's no need to re-apply the changes when closing the picker
> fix(DatePicker): unnecessary onChange removed when closing picker

- apps/app/package.json
- package-lock.json
- packages/lab/package.json
- `@types/react-grid-layout` switched to the `dependencies` instead of `devDependencies` to resolve the types correctly (we do the same for the table types). Otherwise we get the following in production:
(1) several types are missing
(2) `layout` resolved to `any`
> fix(Dashboard): types

- package-lock.json
- packages/core/package.json
- packages/core/src/FileUploader/DropZone/DropZone.test.tsx
- packages/core/src/FileUploader/DropZone/DropZone.tsx
- packages/core/src/FileUploader/FileUploader.stories.tsx
- packages/core/src/FileUploader/FileUploader.test.tsx
- packages/core/src/FileUploader/FileUploader.tsx
`attr-accept` ESM build is producing CJS code, leading to runtime issues (see [this sandbox](https://stackblitz.com/edit/github-zugymp?file=src%2FApp.tsx%3AL9))
Furthermore, ~`attr-accept`'s implementation~our custom validation doesn't seem to be equivalent to the native one - see [this issue](https://github.com/lumada-design/hv-uikit-react/issues/3852)
This PR:
- Copies `attr-accept`'s code to our codebase
- we should evaluate removing this in favour of HTML's accept and allowing a custom validation
- Changes docs to align validation with native APIs
- Some minor refactors
> fix(FileUploader): validate function ESM import

- package-lock.json
- package.json
- `husky` is missing from `devDependencies` (it's being used in setup)
With this, tools like pr.new work out-of-the-box: https://pr.new/lumada-design/hv-uikit-react/pull/3954
> chore: add husky to devDependencies

- .config/vite.config.ts
- packages/code-editor/package.json
- packages/core/package.json
- packages/icons/package.json
- packages/lab/package.json
- packages/shared/package.json
- packages/viz/package.json
Reverts the https://github.com/lumada-design/hv-uikit-react/pull/3927 changes for the react pages:
- Only the `uikit-styles` and `uikit-uno-preset` require the fix
- Changes in React pages are exposing us unexpected issues:
- eg. `attr-accept` - see https://github.com/lumada-design/hv-uikit-react/pull/3942
Validated it resolves the `vitest` and `HvFileUploader` that arose
> build: revert `.mjs` change in react packages

- apps/app/src/pages/Flow/Nodes/Dashboard.tsx
- packages/lab/src/Flow/Node/Parameters/Select.tsx
- packages/lab/src/Flow/Node/Parameters/Slider.tsx
- packages/lab/src/Flow/Node/Parameters/Text.tsx
- packages/lab/src/Flow/nodes/DashboardNode.tsx
- packages/lab/src/Flow/stories/Usage.stories.mdx
- The node parameters were refactored to simplify the code: there was no need for `reactFlowInstance.getNodes()`
- `HvDashboardNode` updates:
- `Partial` added to `labels` to not make it mandatory to fill all the labels
- `title` and `description` removed from `labels` since they weren't used
- `children` only rendered when defined to avoid adding unnecessary space
- The `HvFlowNodeSharedParam` type was simplified in the docs
> chore(Flow): small refactors & type fix

- packages/core/src/Typography/Typography.stories.tsx
- packages/core/src/Typography/Typography.styles.ts
- packages/core/src/Typography/Typography.tsx
- showcase `link` prop usage in samples
- also now covered by Applitools (changes are expected)
- add pointer cursor to `link`
- deprecate `paragraph` prop in favour of `component="p"`:
- there are no styles or classes associated with this; current docs are wrong
- `p` is already the default component for most (non-title) variants
> docs(Typography): add link to samples

- packages/core/src/FilterGroup/Counter/Counter.tsx
- packages/core/src/FilterGroup/FilterGroup.test.tsx
- packages/core/src/FilterGroup/RightPanel/RightPanel.tsx
This PR fixes the following two bugs:
- When the filter group is empty and the “All” option is selected an error is thrown and the option can’t be selected. It’s only possible to select “All” after selecting another option: 
https://github.com/lumada-design/hv-uikit-react/assets/43220251/2e66556c-aba2-4cd2-be42-d2395d2340d6
- When fixing this bug I noticed the counter was not working as expected:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/84981b12-51ef-4645-8c6d-40af6fc1860c
> fix(FilerGroup): error when all option is selected & wrong counter

- packages/lab/src/Flow/DroppableFlow.tsx
- packages/lab/src/Flow/Node/BaseNode.tsx
When an `id` was provided for an input or output (ex: `outputs={[{ id: "output1", label: "Output 1", provides: "data" }]}`), `validateEdge` was not working properly and the connection was not established since it was assuming that the handle `ids` could only be an index.
- We now look for the input/output based on its `id`. To enable this, the `inputs`/`outputs` of a node are updated with the missing `id` before using `registerNode`.
> fix(Flow): set node handle id to correctly validate connections

- packages/core/src/TimePicker/TimePicker.stories.tsx
- packages/core/src/TimePicker/TimePicker.test.tsx
- packages/core/src/TimePicker/TimePicker.tsx
Allow passing `null` to `TimePicker`'s controlled state `value` to represent an "empty" controlled value
> fix(TimePicker): allow empty controlled value with null

- apps/app/src/pages/Flow/Nodes/Dashboard.tsx
- packages/lab/src/Flow/DroppableFlow.tsx
- packages/lab/src/Flow/Node/BaseNode.styles.tsx
- packages/lab/src/Flow/Node/BaseNode.tsx
- packages/lab/src/Flow/Node/Node.styles.tsx
- packages/lab/src/Flow/Node/Node.tsx
- packages/lab/src/Flow/Node/utils.ts
- packages/lab/src/Flow/hooks/useFlowNode.ts
- packages/lab/src/Flow/nodes/DashboardNode.styles.tsx
- packages/lab/src/Flow/nodes/DashboardNode.tsx
- packages/lab/src/Flow/stories/Base/Asset.tsx
- packages/lab/src/Flow/stories/Base/Dashboard.tsx
- packages/lab/src/Flow/stories/Usage.stories.mdx
- packages/lab/src/Flow/types/flow.ts
- Nodes accept groups of inputs and outputs
- Inputs and outputs labels are now `React.ReactNode` instead of `string`
- Docs updated
- Node data type added to `useFlowNodeUtils` 
- Fix: It was not possible to override the parents' nodes (`HvFlowNode` and `HvFlowBaseNode`) `classes` for `HvDashboardNode` and `HvFlowNode`
- The actions were moved to the footer for samples using `HvDashboardNode`
- Since the actions are in the footer now, I removed the unnecessary class that was wrapping `children` for this component
> feat(Flow): input and output groups

- packages/core/src/Table/renderers/DropdownColumnCell/DropdownColumnCell.tsx
- packages/core/src/Table/renderers/renderers.tsx
- packages/core/src/Table/stories/TableRenderers/DropDownColumnRenderer.test.tsx
- packages/core/src/Table/stories/TableRenderers/TableRenderers.tsx
- packages/core/src/Table/stories/storiesUtils.tsx
Addresses https://github.com/lumada-design/hv-uikit-react/issues/3975
- The table was crashing when the dropdown renderer didn't have any values for the dropdown
- The dropdown list was cut-off when there wasn't many rows in the table: `disablePortal` was removed to fix this. 
- Let me know if you think there's any problem removing `disablePortal` and it should be opt-out instead for backward compatibility purposes 
After:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/7bd65816-21e3-4014-9335-0a34a604db42
> fix(Table): dropdown renderer crashing & cut-off

- packages/core/src/Table/hooks/useFilters.ts
- packages/core/src/Table/hooks/useGlobalFilter.ts
- fixes `useFilters` and `useGlobalFilter`'s side-effects by cloning the hooks, instead of re-exporting & mutating `react-table`'s
https://www.unpkg.com/browse/@hitachivantara/uikit-react-core@5.44.8/dist/esm/index.js (lines 35-36)
> build(table): fix useHvTable pluginName side-effects

- packages/lab/src/Flow/DroppableFlow.tsx
- packages/lab/src/Flow/hooks/useFlowNode.ts
- Type fixed for `isValidConnection`
- Zustand's `shallow` equality function was added to our hooks when using `useStore` as mentioned [here](https://reactflow.dev/api-reference/hooks/use-store#equality-fn) to avoid unnecessary re-renders. Example with the `useFlowNodeInputEdges`:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/90930555-0392-4091-a6c4-d495e3fa767c
https://github.com/lumada-design/hv-uikit-react/assets/43220251/614c560b-3a69-4c4c-aedf-e26907ab0cb0
> perf(Flow): add equality function to useStore to avoid unnecessary re-renders

- .storybook/decorators/withThemeProvider.tsx
- packages/viz/src/BarChart/BarChart.tsx
- packages/viz/src/LineChart/LineChart.stories.tsx
- packages/viz/src/LineChart/LineChart.tsx
- packages/viz/src/hooks/useSeries.tsx
- Allow the use of `MarkLineComponent` on the `LineChart` and `BarChart` components
- Update the custom echart options sample for the `LineChart` component
> docs: update custom echarts options sample

- packages/core/src/Switch/Switch.stories.tsx
- simplify decorators & styling rendering (`styled()` and `SwitchLabel` util)
- improve `WithLabels` sample
- remove controlled/disabled logic (doesn't add value to the sample)
- switch to `HvBaseSwitch` as we we're not using any of `HvSwitch`'s features
- fix unused ids, link labels to input, use `label`s for "Off" and "On" "buttons"
> docs(Switch): improve sample rendering & docs

- .github/actions/build-artifacts/action.yml
- .github/actions/deploy-artifacts/action.yml
- .github/actions/install-dependencies/action.yml
- .github/workflows/documentation.yml
- .github/workflows/pr-close.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
- .github/workflows/static-checks.yml
- .github/workflows/tests-a11y.yml
- .github/workflows/tests-applitools.yml
Bump common actions to `@v4` to fix the extensive warnings we're getting
> ci: bump actions versions

- packages/core/src/ListContainer/ListContainer.stories.tsx
- packages/core/src/ListContainer/ListItem/ListItem.tsx
- packages/core/src/Panel/Panel.tsx
changes related to reusing these components in `HvSelect`:
- forwardRef `HvPanel`
- use `HvPanel` in List stories
- improve `HvListItem` reusability with external focus management
- allow `tabIndex` to be used
- allow `aria-disabled` & `aria-selected` to dictate disable/selection state
> feat(ListItem): improve reusability with external focus management

- packages/core/src/DropDownMenu/DropDownMenu.stories.tsx
- packages/core/src/DropDownMenu/DropDownMenu.tsx
It doesn't make much sense that this component has a prop categories while others have variants and the values are the same.
category was marked as deprecated and not remove to not cause breaking changes
> fix(DropdownMenu): add variant prop to be inline with other components

- packages/core/src/DropDownMenu/DropDownMenu.stories.tsx
- packages/core/src/ListContainer/ListContainer.stories.tsx
- packages/core/src/Panel/Panel.stories.tsx
- review opened/redudant DropDownMenu samples
- `iconSelectedColor` made no sense as there's no selection state, but something similar is needed for SB not to enter an infinite-loop 😞 
- merge disabled & icons samples
- they don't add much separately, and this way we visually test disabled icons
- review Panel samples
- use DS's padding instead of `20` override (Applitools changes are expected)
> docs: review DropDownMenu & Panel

- packages/core/src/BaseDropdown/BaseDropdown.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/DropDownMenu/DropDownMenu.tsx
- packages/core/src/Dropdown/Dropdown.styles.tsx
- packages/core/src/Dropdown/Dropdown.tsx
- packages/core/src/Table/stories/TableRenderers/DropdownColumnRenderer.tsx
`popperProps` are incorrectly inheriting from MUI instead of `react-popper`. keys such as `style` are not present
- replace MUI with react-popper types
- fix misuse of `popperProps`
- inherit types in `HvDropdown` (from `HvBaseDropdown` and `HvFormElement`)
> fix(BaseDropdown): popper types

- .eslintrc
- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/TimeAgo/TimeAgo.stories.tsx
- packages/core/src/TimeAgo/TimeAgo.tsx
- packages/core/src/TreeView/TreeView.stories.tsx
- packages/core/src/TreeView/TreeView.tsx
- packages/core/src/TreeView/stories/VerticalNavigation.tsx
- packages/core/src/Typography/Typography.stories.tsx
- packages/core/src/Typography/Typography.tsx
- packages/core/src/types/generic.ts
- fix `forwardRef` issues in our `forwardRef` + polymorphic/generic components that make us lose TSDoc definitions
- add `fixedForwardRef` to fix generics (fix based on [this article](https://www.totaltypescript.com/forwardref-with-generic-components#the-problem-with-forwardref))
> refactor: fix `forwardRef` type inference

- packages/core/src/ListContainer/ListContainer.stories.tsx
- packages/core/src/ListContainer/ListContainer.tsx
- packages/core/src/ListContainer/ListContext/ListContext.ts
- packages/core/src/ListContainer/ListItem/ListItem.tsx
Adds `selectable` prop (feel free to suggest a better name) to `HvListContainer` and `HvListItem` to enable visual selection. This is needed for when we can't use `interactive` because selection is managed externally.
> feat(List): add visually selectable prop

- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Button/Button.styles.ts
- packages/core/src/Button/Button.test.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/Pagination/Pagination.test.tsx
- packages/core/src/QueryBuilder/QueryBuilder.test.tsx
- packages/core/src/QueryBuilder/RuleGroup/RuleGroup.tsx
- packages/core/src/utils/IconButton/IconButton.test.tsx
- packages/core/src/utils/IconButton/IconButton.tsx
- packages/core/src/utils/IconButton/index.ts
Addresses https://github.com/lumada-design/hv-uikit-react/issues/4013
- We have an internal component called `IconButton` which uses a tooltip around a button. When the button is disabled, the error shown above is thrown. To solve this, a new [`focusableWhenDisabled`](https://mui.com/base-ui/react-button/#focus-on-disabled-buttons) property was added to the `HvButton` as proposed in the thread below. When using this property, the button is disabled only through  `aria-disabled` and not through `disabled` in order to be accessible by screen readers and the tooltip to show on hover. 
- Tests updated and new tests created
> fix: disabled button inside tooltip

- packages/core/src/GlobalActions/GlobalActions.stories.tsx
- packages/core/src/GlobalActions/GlobalActions.styles.tsx
- packages/core/src/GlobalActions/GlobalActions.tsx
- packages/styles/src/themes/ds3.ts
Align `GlobalActions` DS 5.9 specs:
- update padding
- `"section"` variant has only border-top and no background
- remove `lodash` usage
- deprecate `globalSectionArea`/`globalWrapperComplement`/`sectionName` classes in favour of selector classes, following our component guidelines
> feat(GlobalActions): align with new DS styles

- apps/app/src/lib/routes.tsx
- apps/app/src/pages/Components/Components.tsx
- apps/app/src/pages/Components/index.ts
- apps/app/src/pages/Flow/DashboardPreview/DashboardPreview.tsx
- apps/app/src/pages/Flow/DashboardPreview/index.ts
- apps/app/src/pages/Flow/Flow.tsx
- apps/app/src/pages/Flow/index.ts
- apps/app/src/pages/Instructions/Instructions.tsx
- apps/app/src/pages/Instructions/index.ts
- apps/app/src/pages/NotFound/NotFound.tsx
- apps/app/src/pages/NotFound/index.ts
- apps/app/src/pages/Root/Root.tsx
- apps/app/src/pages/Root/index.ts
- apps/app/src/pages/layout/navigation.tsx
- apps/app/src/pages/layout/root.tsx
Update the app router routes to better align with the latest & default react-router recommendations
- Leverage nested routing for templates
- use lazy route import
- use object (the default) instead of JSX definition
The goal of this change is to make it easier to compare with the App Shell's config spec
> refactor(app): move to routes object & lazy route loading

- package-lock.json
- packages/core/package.json
- packages/core/src/Select/Option.tsx
- packages/core/src/Select/OptionGroup.tsx
- packages/core/src/Select/Select.stories.tsx
- packages/core/src/Select/Select.styles.ts
- packages/core/src/Select/Select.test.tsx
- packages/core/src/Select/Select.tsx
- packages/core/src/Select/SelectButton.tsx
- packages/core/src/Select/index.ts
- packages/core/src/Select/stories/Controlled.tsx
- packages/core/src/Select/stories/Form.tsx
- packages/core/src/index.ts
- packages/styles/src/themes/ds3.ts
Add `HvSelect` component (and `HvOption`/`HvOptionGroup`)
- uses MUI's `useSelect` behind the scenes (handles multi-select/focus/navigation/search)
- uses `HvButton` for the "header component"
> feat(Select): add `HvSelect` component

- packages/core/src/providers/Provider.tsx
Allow passing a custom `EmotionCache` instance to `HvProvider`
This lets users configure the cache to their needs (injection order/mount point) and re-use the instance across multiple providers
> feat(Provider): allow passing a custom cache

- packages/core/src/Card/Card.tsx
- packages/styles/src/tokens/colors.ts
- Allow passing other colors to `HvCard`, making it more customisable and reducing the need to type casting
- Improve `HvColorAny` typings to include built-ins completions (eg. `"inherit"`, `"currentColor"`, etc.)
> feat(Card): allow more colors to be passed

- docs/overview/status/data.json
- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Button/Button.styles.ts
- packages/core/src/Button/Button.tsx
- packages/core/src/DropDownMenu/DropDownMenu.tsx
- packages/core/src/MultiButton/MultiButton.stories.tsx
- packages/core/src/MultiButton/MultiButton.styles.tsx
- packages/core/src/MultiButton/MultiButton.tsx
- packages/styles/src/themes/ds3.ts
- A style was removed from the `HvMultiButton` and added to `ds3` theme where the selected button would be slightly bigger then the others to match the ds5 specs. Applitools is expected to break because of it.
- Button sizes was added to `HvMultiButton`
- `HvMultiButton` variants style were added. The prop was already there but the styles didn't match ( there was no ds specification so I added the styles that made sense looking at the button variants specs)
- changed the `type` `css` selectors with classes for compatibility  with the `HvDropdownMenu` component (e.g. replaced `first-of-type` with the `firstButton` class)
- Added the `sizes` prop from the `HvButton` to the `HvDropdownMenu` component to create different size split buttons
- Added diferent icon sizes styles to `HvButton` …
> feat(SplitButton): add split button variant to `MultiButton` component

- packages/lab/src/Wizard/WizardActions/WizardActions.tsx
In the Digital Advisor, we need to use the Wizard but we need to do some HTTP requests to validate that the user can go to the next page. We added a callback function to the WizardActions to allow for that.
Note: This will only work when we use the Wizard with separate components, since we don't have the Context to change the page without it.
I also made a change to allow us to define the action labels as a ReactNode so that we can put a Loading while we are performing the HTTP request validation.
> feat: allow run custom validations on Wizard before going to next page. DIG-1348

- packages/styles/src/utils.ts
Prevent common CSS vars to be duplicated through all theme/mode pairs. 
- `theme / mode` contains only color related CSS vars
- `theme` contains the remaining theme level CSS vars (radii, spaces, sizes, etc).
> fix: css vars deduplication

- packages/core/src/Table/stories/TableSection/TableSettings.tsx
- Set the Table Settings popper to be open by default
- Set the appropriate `list` and `listitem` roles
- Applitools errors expected
> fix: table settings story a11y issues

- package-lock.json
- packages/lab/package.json
We're using `useDebounceCallback` which is only available from `usehooks-ts@2.12`
> fix: bump minimum lab `usehooks-ts` version

- docs/tests/Tags.stories.tsx
- package-lock.json
- package.json
- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/BulkActions/BulkActions.stories.tsx
- packages/core/src/DatePicker/DatePicker.stories.tsx
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Drawer/Drawer.stories.tsx
- packages/core/src/Dropdown/stories/Dropdown.stories.tsx
- packages/core/src/FilterGroup/stories/FilterGroup.stories.tsx
- packages/core/src/Select/Select.stories.tsx
- packages/core/src/Table/stories/TableHooks/TableHooks.stories.tsx
- packages/core/src/Table/stories/TableSection/TableSection.stories.tsx
- packages/core/src/TimePicker/TimePicker.stories.tsx
- packages/core/src/TreeView/stories/TreeView.stories.tsx
- packages/core/src/VerticalNavigation/VerticalNavigation.stories.tsx
- packages/lab/src/Flow/stories/Flow.stories.tsx
- packages/lab/src/Wizard/Wizard.stories.tsx
- Assertions were added to storybook play functions to try to fix the unstable stories (example [here](https://eyes.applitools.com/app/test-results/00000251690157190775/?accountId=NWMfIF0XfUeh3g9JqZjRrg~~) with the tree view component)
ℹ️ I initially added the Interactions addon to storybook to have a [UI tool for interactions](https://storybook.js.org/docs/writing-stories/play-function#setup-the-interactions-addon) but I had to remove it since Applitools was not able to run when used. Once we no longer depend on Applitools, we can add it back.
> chore: assertions added to storybook play

- packages/core/src/AvatarGroup/AvatarGroup.tsx
- packages/core/src/AvatarGroup/stories/AvatarGroup.stories.tsx
- adds the `highlight` feature: when set to `true` this allows the hovered avatar to be brought to the front and be fully displayed to the user.
> feat(AvatarGroup): add highlight feature

- .github/workflows/tests-visual.yml
- ❌ added in the Nightly when the Chromatic step fails
- Missing env url added to the Slack notification
> chore: fail Chromatic job & add missing env url to visual tests workflow

- .config/vite.config.ts
we're duplicating source maps in cjs and esm "bundles", leading to needlessly larger packages
> build: remove duplicated sourcemaps

- packages/core/src/Drawer/Drawer.test.tsx
- packages/core/src/Drawer/Drawer.tsx
It was reported in ui-kit channel that `onClose` was being triggered twice when clicking the backdrop. This code seems to me to be redundant and removing it fixed it.
> fix(Drawer): remove onclose trigger

- .storybook/preview.ts
- docs/tests/Header.stories.tsx
- packages/core/src/CheckBoxGroup/CheckBoxGroup.styles.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/FilterGroup/Counter/Counter.tsx
- packages/core/src/FilterGroup/LeftPanel/LeftPanel.tsx
- packages/core/src/FilterGroup/RightPanel/RightPanel.styles.tsx
- packages/core/src/FilterGroup/RightPanel/RightPanel.tsx
- packages/core/src/Header/Header.stories.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/Kpi/Kpi.stories.tsx
- packages/core/src/Kpi/stories/Selectable.tsx
- packages/core/src/List/List.tsx
- packages/core/src/ScrollTo/Horizontal/HorizontalScrollListItem/HorizontalScrollListItem.styles.tsx
- packages/core/src/ScrollTo/Horizontal/HorizontalScrollListItem/HorizontalScrollListItem.tsx
- packages/core/src/ScrollTo/Horizontal/ScrollToHorizontal.stories.tsx
- packages/core/src/ScrollTo/Horizontal/ScrollToHorizontal.styles.tsx
- packages/core/src/ScrollTo/Horizontal/ScrollToHorizontal.tsx
- packages/core/src/ScrollTo/Vertical/ScrollToVertical.tsx
- packages/core/src/ScrollTo/Vertical/VerticalScrollListItem/VerticalScrollListItem.styles.ts
- packages/core/src/ScrollTo/Vertical/VerticalScrollListItem/VerticalScrollListItem.tsx
- packages/core/src/ScrollTo/types.ts
- packages/core/src/Section/Section.stories.tsx
- packages/core/src/Select/Select.stories.tsx
- packages/core/src/Switch/Switch.stories.tsx
- packages/core/src/Table/stories/TableHooks/TableHooks.stories.tsx
- packages/lab/src/Dashboard/Dashboard.stories.tsx
- packages/lab/src/Flow/stories/Flow.stories.tsx
- packages/styles/src/themes/ds3.ts
- fix a11y issues found by new tool
- rename `aria-prohibited-attr` > `aria-allowed-attr`
- merge KPI Selectable stories & use `?raw` loader
- refactor `ScrollTo` to better address the tooltip + label issues
- move the tooltip logic to the `*ScrollListItem.tsx` & leverage `HvOverflowTooltip`
- move the "bullet" icon to `*ScrollListItem.tsx` to not include it in the tooltip
- always use a rounded div, instead of div + icon - simplifying the logic & making it easier to customise (no need for the `activeTheme` tokens anymore)
- small fixes in spacing (using DS5 units instead of DS3)
- refactor `HvList` to use `HvOverflowTooltip`
- fixes tooltip a11y issues in components using it
> fix(a11y): fix issues

- .config/chromatic.config.json
In [this run](https://github.com/lumada-design/hv-uikit-react/actions/runs/8600782230/job/23567189116), Chromatic failed due to turbo snap. After doing some [research](https://github.com/chromaui/chromatic-cli/issues/868), I found out that [vite-plugin-turbosnap](https://github.com/IanVS/vite-plugin-turbosnap) was needed. 
However, after more research ([here](https://github.com/chromaui/chromatic-cli/issues/731) and [here](https://www.chromatic.com/docs/setup-turbosnap/#compatibility)), it seems like turbo snap is not compatible with `pull_request` events on CI at the moment. 
Thus, I'm disabling turbo snap until it's compatible with `pull-request` or we decide to change our workflows (in case we really need turbo snap for some reason).
> chore: disable turbosnap for Chromatic

- packages/viz/src/BarChart/BarChart.tsx
- packages/viz/src/BarChart/stories/BarChart.stories.tsx
- packages/viz/src/BarChart/stories/CustomEchartsOptions.tsx
- packages/viz/src/BaseChart/BaseChart.tsx
- packages/viz/src/ConfusionMatrix/ConfusionMatrix.tsx
- packages/viz/src/DonutChart/DonutChart.tsx
- packages/viz/src/LineChart/LineChart.tsx
- packages/viz/src/types/common.ts
- `onEvents` added for the visualisations to trigger events when needed:
- ℹ️ I had to put `dispose` from `HvBaseChart` in another `useEffect` because having it in the same effect was preventing us from using `onEvents` (the callback was not triggered). 
-  Sample that triggers a tooltip when hovering a truncated y axis label added (based [on](https://github.com/apache/echarts/pull/16315))
> feat: onEvents added to visualisations & sample with tooltip for truncated labels added

- .config/chromatic.config.json
- .github/workflows/tests-visual.yml
As seen in [this run](https://github.com/lumada-design/hv-uikit-react/actions/runs/8610558629/job/23601518112), for some reason `forceRebuild` can't be used in the config file. To fix this, I'm adding it to the GitHub workflow.
> chore: fix Chromatic forceRebuild option

- packages/core/src/Avatar/Avatar.tsx
- packages/core/src/AvatarGroup/AvatarGroup.styles.tsx
- packages/core/src/AvatarGroup/AvatarGroup.tsx
- packages/core/src/AvatarGroup/AvatarGroupContext.tsx
- packages/core/src/AvatarGroup/stories/AvatarGroup.stories.tsx
- packages/core/src/AvatarGroup/stories/CustomOverflow.tsx
- packages/core/src/AvatarGroup/stories/WithTooltip.tsx
- packages/lab/src/StepNavigation/DefaultNavigation/Step/Step.tsx
This PR includes a refactor of the `HvAvatarGroup` component. It started just by allowing `HvAvatar` components  to be wrapped with an `HvTooltip` inside the avatar group and evolved to include a more profound refactor that removes legacy React APIs (`Children.map`, `cloneElement`). 
The Applitools errors are expected.
> refactor(AvatarGroup): refactor the component to remove legacy React APIs

- packages/core/src/providers/ThemeProvider.tsx
Add `disableRipple` to MUI theme overrides to disable the ripple effect in our components (eg. Tag)
> style: add disableRipple global default

- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/CheckBoxGroup/CheckBoxGroup.stories.tsx
- packages/core/src/Container/Container.stories.tsx
- packages/core/src/DatePicker/DatePicker.stories.tsx
- packages/core/src/FileUploader/Preview/Preview.styles.tsx
- packages/core/src/Kpi/Kpi.stories.tsx
- packages/core/src/RadioGroup/RadioGroup.stories.tsx
- packages/core/src/SelectionList/SelectionList.stories.tsx
- packages/core/src/Skeleton/Skeleton.styles.tsx
- packages/core/src/TagsInput/TagsInput.stories.tsx
- packages/core/src/TextArea/TextArea.stories.tsx
- packages/core/src/TimePicker/TimePicker.stories.tsx
- packages/viz/src/BarChart/stories/customTooltip.ts
- packages/viz/src/DonutChart/DonutChart.stories.tsx
remove usage of "inline" `{ [key: string]: CSSInterpolation }` typings object in favour of the [Emotion best-practices](https://emotion.sh/docs/best-practices#consider-defining-styles-outside-your-components)
> docs: use styles object according to Emotion best-practices

- packages/core/src/BulkActions/BulkActions.styles.tsx
Applitools was failing frequently because of the "Complete Table" story: [example](https://eyes.applitools.com/app/test-results/00000251688503375750/00000251688503202521/steps/1?accountId=NWMfIF0XfUeh3g9JqZjRrg~~&mode=step-editor). I tested the story locally and it was also happening sometimes. After looking at the code it seems that there's a clash between the `semantic` classe for the `HvBulkActions` and `HvBaseCheckBox` components. I removed some unneeded CSS for the `HvBulkActions` component to fix this (the main problem was with the `backgroundColor` property).
> fix(BulkActions): select all background color

- packages/core/src/Slider/Slider.test.tsx
- packages/core/src/Slider/Slider.tsx
Addresses: https://github.com/lumada-design/hv-uikit-react/issues/4164
- When the values are not between `maxPointValue` and `minPointValue`, the slider is invalid.
- Tests updated and new tests added.
> fix(Slider) - maxPointValue and minPointValue validation

- .storybook/blocks/DocsPage.tsx
- .storybook/preview.ts
restore `DocsPage` component ([copy of SB's](https://github.com/storybookjs/storybook/blob/v8.0.10/code/ui/blocks/src/blocks/DocsPage.tsx)), and add `includePrimary={false}` to `Stories` component
> docs: remove duplicated Main story

- .config/chromatic.config.json
- Instead of using a [test build](https://storybook.js.org/docs/api/main-config-build#test) for Chromatic, a production one is used as we now use the build created by Chromatic to review our PRs. Test builds are stripped-down versions of production builds, for instance they don't provide the components' page with all the stories listed ([example](https://66040297ad386b97be078cc9-gufatqkquj.chromatic.com)).
> chore: use production build for Chromatic

- packages/viz/src/hooks/useLegend.tsx
Fixes going from:
to:
when:
```
legend={{
position: {
x: "right",
},
}}
```
The legend orientation should have stayed horizontal and not vertical.
> fix: viz legend position

- packages/core/src/QueryBuilder/Context.tsx
- packages/core/src/QueryBuilder/QueryBuilder.test.tsx
- packages/core/src/QueryBuilder/QueryBuilder.tsx
- packages/core/src/QueryBuilder/RuleGroup/RuleGroup.tsx
- `allowRepeatedAttributes ` prop added to disable the default attribute validation
- From what I've tested, the validation only occurs at the UI level as shown in the video below (by changing the `status` of `HvDropdown`). Internally the query still updates.
https://github.com/lumada-design/hv-uikit-react/assets/43220251/3e339a44-2daf-4b3b-b75c-4b2945734afa
> feat(QueryBuilder): prop added to disable default attribute validation

- packages/viz/src/BarChart/BarChart.tsx
- packages/viz/src/ConfusionMatrix/ConfusionMatrix.tsx
- packages/viz/src/DonutChart/DonutChart.tsx
- packages/viz/src/LineChart/LineChart.stories.tsx
- packages/viz/src/LineChart/LineChart.tsx
- packages/viz/src/ScatterPlot/ScatterPlot.tsx
- packages/viz/src/hooks/tooltip/useTooltip.tsx
- packages/viz/src/hooks/useData.tsx
- packages/viz/src/hooks/useSeries.tsx
- packages/viz/src/utils/index.ts
- It's now possible to use measures with the same field but with different aggregation functions: pairs field/aggregation functions are now unique instead of only fields.
> fix: enable using measures with the same field but with different aggregation functions

- packages/styles/src/themes/pentahoPlus.ts
- Multi button styles fixed:
- Split button
- Hover
- Dark mode
https://github.com/lumada-design/hv-uikit-react/assets/43220251/d56fc1b6-3850-457c-ad8f-5a16b38f1c06
- Button styles fixed:
- Disabled in dark mode
> fix: multi button and button Pentaho theme styles

- packages/core/src/BaseDropdown/BaseDropdown.tsx
- packages/core/src/BaseDropdown/BaseDropdownContext/BaseDropdownContext.tsx
- packages/core/src/Button/Button.styles.ts
- packages/core/src/Button/Button.tsx
- packages/core/src/Calendar/SingleCalendar/SingleCalendar.styles.tsx
- packages/core/src/ColorPicker/ColorPicker.styles.tsx
- packages/core/src/DropDownMenu/DropDownMenu.styles.tsx
- packages/core/src/DropDownMenu/DropDownMenu.tsx
- packages/core/src/Dropdown/List/List.tsx
- packages/core/src/MultiButton/MultiButton.styles.tsx
- packages/core/src/TimePicker/TimePicker.styles.ts
- packages/styles/src/themes/pentahoPlus.ts
The following styling problems with the Pentaho theme were fixed:
- **Select**: wrong border radius when expanded
- **Split button**: problems with split container when hovered (disappearing)
- **Multi button**: `variant` prop not working properly
- **Dropdown menu**: wrong border radius when expanded
- **Dropdown menu, color picker, date picker and time picker**: background color overflowing rounded corners
Also:
- `HvBaseDropdown` was refactored in order to wrap the root component with the provider: this change was needed for `HvDropdownButton` to know the placement
ℹ️ The multi button looks still a bit weird, but since we don't have specs it's normal.
> fix: dropdown menu, split/multi button, and select for Pentaho theme

- .github/actions/build-artifacts/action.yml
- .github/workflows/documentation.yml
- .github/workflows/nightly.yml
- .github/workflows/pr-close.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
- .github/workflows/tests-playwright.yml
- .github/workflows/tests.yml
- Fix [PR-Close workflow failing](https://github.com/lumada-design/hv-uikit-react/actions/workflows/pr-close.yml) trying to clean directories that might not exist
- Enable Storybook deployments, as we can't always rely on Chromatic deployments
- Disable Nextra deployment, (for now) as development is on-hold indefinitely
- Disable Playwright tests (just `HvFlow` for now) in flaky `webkit` and redundant (chrome-like) `msedge` and `chromium`
- Rename `static-tests` to `tests` as many aren't static tests
- Misc alignments
- use `node@18`
- sort Chromatic PR run to the top
> ci: fix pr-close, disable nextra, enable SB, rename tests workflow

- .github/workflows/release.yml
- Add [npm package provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) check
- Re-use `security.yml` workflow in actions
> ci(security): add npm provenance & reuse workflow

- packages/lab/src/Flow/Node/BaseNode.tsx
- packages/lab/src/Flow/hooks/index.ts
- packages/lab/src/Flow/hooks/useNode.tsx
- packages/lab/src/Flow/stories/BaseHook/IconEdge.tsx
- packages/lab/src/Flow/stories/BaseHook/Node.tsx
- packages/lab/src/Flow/stories/BaseHook/index.tsx
- packages/lab/src/Flow/stories/Flow.stories.tsx
A useBaseNode hook (in lack of a better name) was created with the logic parts of `BaseNode` and `Node` leaving the visual implementation to the components that use it. 
To exemplify this some nodes were added and are present in the `Base Hook` story in the documentation:
A simpler `WebttleNode` that uses the `useBaseNode` hook and has a different visual (similar to the webttle use case).
A `DANode` that uses the `useBaseNode` hook instead of the `BaseNode` and `Node` components but keeps the same api.
A `AssetDA` and `MLModelDA` that use the `DANode` component to implement the `Asset` and `MLModel` nodes.
A `AssetWorkbench`  a node that uses the `useBaseNode` to implement a `Asset` node.
`AssetDA` and `AssetWorkbench` were created to compare the different approaches of using the hook. …
> feat: add useBaseNode hook and demo nodes

- apps/app/src/pages/Flow/DashboardPreview/Renderers/Table.tsx
- packages/lab/src/Canvas/Toolbar/Toolbar.styles.tsx
- packages/lab/src/Flow/stories/Dynamic/index.tsx
- packages/lab/src/Flow/stories/NoGroups/index.tsx
[`auto` hides unnecessary scrollbars](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#auto)
> chore: replace overflow scroll with auto

- packages/cli/src/baselines/app-shell/vite/src/providers/Provider.tsx
- packages/cli/src/baselines/vite/src/components/common/Loading/Loading.tsx
- packages/core/src/Select/Select.tsx
- packages/core/src/Slider/Slider.tsx
- packages/core/src/Tooltip/Tooltip.tsx
- packages/core/src/providers/Provider.tsx
- packages/core/src/providers/ThemeProvider.tsx
- packages/core/src/utils/theme.ts
- packages/lab/src/Blade/Blade.tsx
- packages/lab/src/Blades/Blades.tsx
- packages/lab/src/Wizard/Wizard.tsx
- packages/lab/src/Wizard/WizardContainer/WizardContainer.tsx
- packages/lab/src/Wizard/WizardContext/WizardContext.tsx
- optimize `ThemeProvider` rendering
- remove unused `React` imports
Opening App + switching Theme to `wicked` and then `dawn`:
- Before: 19 renders & more noticeable theme flickering 
https://github.com/lumada-design/hv-uikit-react/assets/638946/84534317-170a-46fd-9f00-8810d722aa6c
- Now: 11 renders & less noticeable theme flickering
https://github.com/lumada-design/hv-uikit-react/assets/638946/c6e4a624-3427-4ff6-83e3-26ffea4f59af
> perf(ThemeProvider): optimize rendering

- .github/workflows/release.yml
- packages/cli/package.json
- packages/pentaho/package.json
- packages/uno-preset/package.json
- align and fix publish > build > clean scripts
- `uno-preset` was missing a `clean`
- update `release.yml` workflow to fail if there are no artifacts to release for better visibility
> build: fix publish/build/clean scripts & update release

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- Change releases to run automatically mondays & thursdays at 05:00
- We might want to eventually change this to weekly + manual, but let's run with this for now
- The Nightly workflow doesn't make much sense anymore (all checks run on PR). We might want to eventually disable or rework it
> ci(release): change to bi-weekly releases

- packages/cli/src/templates/Canvas/TreeView.tsx
- packages/core/src/TreeView/TreeItem/TreeItem.tsx
In [this PR](https://github.com/lumada-design/hv-uikit-react/pull/4227), the Canvas template was created. However, drag and drop with keyboard was not implemented for the tree view panel as it wasn’t working OOTB. This PR implements the missing drag and drop keyboard feature for the template.
> fix: drag and drop with keyboard for tree view panel in canvas template

- docs/templates/Canvas.stories.tsx
- docs/tests/BottomPanel.stories.tsx
- packages/cli/src/templates/Canvas/Table.tsx
- packages/cli/src/templates/Canvas/index.tsx
- packages/cli/src/templates/Canvas/styles.tsx
- packages/pentaho/src/Canvas/BottomPanel/BottomPanel.spec.tsx
- packages/pentaho/src/Canvas/BottomPanel/BottomPanel.stories.tsx
- packages/pentaho/src/Canvas/BottomPanel/BottomPanel.styles.tsx
- packages/pentaho/src/Canvas/BottomPanel/BottomPanel.test.tsx
- packages/pentaho/src/Canvas/BottomPanel/BottomPanel.tsx
- `HvCanvasBottomPanel` component updates:
- tabs title layout improved when content is overflowing (video below): `overflowActions` prop added
- tests updated
- `tab` prop renamed to `selectedTabId` (for consistency with the new toolbar tabs)
- Canvas template added to visual tests: to visually test the toolbar and side panel
https://github.com/user-attachments/assets/bd9f22ec-9dfe-4dab-8147-f472fdc79d38
> fix(BottomPanel): tab title overflow

- .config/vite.config.ts
- .prettierrc
- package-lock.json
- package.json
- packages/code-editor/package.json
- packages/core/package.json
- packages/icons/package.json
- packages/icons/scripts/svgToReact.ts
- packages/icons/scripts/svgToSprite.ts
- packages/lab/package.json
- packages/pentaho/package.json
- packages/shared/package.json
- packages/styles/package.json
- packages/uno-preset/package.json
- packages/viz/package.json
- scripts/flow-styles.js
- scripts/storybook-title.js
- chore(deps): align ts versions (prettier plugin, app, docs)
- build(icons): remove icons CLI behaviour & `yargs` dependency
- move project from CJS to ESM (add `type: "module"`), as [Vite CJS build is deprecated](https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated)
- `type` is removed by `clean-publish` so this change has no effect on users
```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```
> chore: move to ESM packages

- packages/core/src/types/generic.ts
Using `React.ReactNode` in `typescript@4` will break, as `undefined` isn't a valid JSX element in v4:
> fix: `fixedForwardRef` types in typescript@4

- packages/core/src/Carousel/Carousel.stories.tsx
- Some broken images link were replaced in the carousel stories: Chromatic was failing because of this.
> docs: replace broken carousel images

- packages/core/src/TagsInput/TagsInput.test.tsx
- packages/core/src/TagsInput/TagsInput.tsx
`HvTagsInput` is spreading its `...others` props to `HvInput`, but not extending it in TS.
This extends `HvInputProps` & removes duplicated types
> fix(TagsInput): inherit types from `HvInput`

- packages/core/src/InlineEditor/InlineEditor.stories.tsx
- packages/core/src/InlineEditor/InlineEditor.tsx
previously when using `HvInlineEditor` the spread attributes were not correctly recognized correctly so attributes of `HvInput` like `disableClear` would show as error with typescript. This intends to fix it even when you change the component.
> fix(HvInlineEditor): typescript attribute recognition

- .github/actions/install-dependencies/action.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
- lerna.json
Add custom GitHub Releases using [changelogithub](https://github.com/antfu/changelogithub)
- Disable `lerna` GitHub Releases generation (`createRelease`)
- Generate GitHub releases with [changelogithub](https://github.com/antfu/changelogithub)
- version is picked up from core package
- example:
> ci(release): add custom GitHub releases

- .github/workflows/release.yml
- Add `NEW_VERSION` output to `publish` job on release workflow
- Equals to the new core version, or empty/null otherwise
- Use `NEW_VERSION` to conditionally trigger the Tab + GitHub Release + Slack message steps/jobs
> ci: fix release pulling latest tag

- apps/app/src/assets/HitachiLogo.tsx
- packages/cli/src/baselines/vite/src/assets/HitachiLogo.tsx
- packages/cli/src/baselines/vite/src/components/common/Header/Header.tsx
- packages/core/src/AppSwitcher/Action/Action.styles.tsx
- packages/core/src/AppSwitcher/Action/Action.tsx
- packages/core/src/AppSwitcher/AppSwitcher.styles.tsx
- packages/core/src/AppSwitcher/AppSwitcher.tsx
- packages/core/src/AvatarGroup/AvatarGroup.tsx
- packages/core/src/BaseDropdown/BaseDropdown.styles.tsx
- packages/core/src/BaseDropdown/BaseDropdown.tsx
- packages/core/src/Card/Card.styles.tsx
- packages/core/src/Card/Card.tsx
- packages/core/src/CheckBoxGroup/CheckBoxGroup.styles.tsx
- packages/core/src/DatePicker/DatePicker.styles.tsx
- packages/core/src/DatePicker/DatePicker.tsx
- packages/core/src/DotPagination/DotPagination.styles.tsx
- packages/core/src/DropdownButton/DropdownButton.styles.tsx
- packages/core/src/FilterGroup/FilterContent/FilterContent.styles.tsx
- packages/core/src/Header/Header.styles.tsx
- packages/core/src/Header/assets/HitachiLogo.tsx
- packages/core/src/ListContainer/ListContainer.styles.tsx
- packages/core/src/LoadingContainer/LoadingContainer.tsx
- packages/core/src/RadioGroup/RadioGroup.styles.tsx
- packages/core/src/Slider/SliderInput/SliderInput.tsx
- packages/core/src/VerticalNavigation/TreeView/TreeViewItem.tsx
- packages/core/src/utils/classes.ts
- packages/lab/src/Flow/Sidebar/Sidebar.styles.tsx
Fixes some styles inconsistencies in components, found by https://github.com/lumada-design/hv-uikit-react/pull/4192
- disabled/subtle text colors: components using BaseDropdown, FlowSidebar, etc.
- add `style` + CSS var utility
- `HitachiLogo` coloring
- ListContainer spacing & outline overflow
> fix: styles across components

- packages/core/src/QueryBuilder/QueryBuilder.test.tsx
- packages/core/src/QueryBuilder/Rule/Value/NumericValue/NumericValue.tsx
It wasn't possible to use decimal numbers in the numeric input. This PR fixes this bug. 
- Typing `.55` worked but not `0.55` because `Number()` was removing the `.` when typing `0.`
> fix(QueryBuilder): decimal values for numeric value

- .storybook/vite.config.ts
- package-lock.json
- packages/code-editor/package.json
- packages/code-editor/src/CodeEditor/CodeEditor.stories.tsx
- packages/code-editor/src/CodeEditor/CodeEditor.tsx
- packages/code-editor/src/CodeEditor/languages/xml.ts
- packages/code-editor/src/CodeEditor/plugins.ts
- packages/code-editor/src/CodeEditor/stories/Main.tsx
- packages/code-editor/src/CodeEditor/stories/Xml/Xml.tsx
- packages/code-editor/src/CodeEditor/stories/Xml/index.ts
- packages/code-editor/src/CodeEditor/stories/Xml/utils.tsx
- IntelliSense support for XML added:
- When the code editor is empty, a suggestion to add the root element appears when clicking on CTRL + SPACE. Clicking on it will add the root element.
-  The code editor auto-completes a tag when closing it: for example, writing `>` after `<root` will automatically add `</root>`.
- The XML code is validated against the schema and the errors are highlighted:
- The schema is provided through the `xsdSchema` property.
- The `xmllint-wasm` package is used for validation. In Vite we need to exclude it from `optimizeDeps`.
- When the user types `<`, suggestions are shown with the possible tags. Clicking on a tag will add it.
- Clicking on CTRL + SPACE inside an opened tag will show suggestions with the possible attributes for the tag. Clicking on an …
> feat(CodeEditor): IntelliSense support for XML

- .github/CONTRIBUTING.md
- README.md
- apps/docs/pages/docs/get-started.mdx
- docs/overview/GetStarted.mdx
- docs/overview/community/Contributing.mdx
- Fix broken & outdated links in docs
- Simplify CONTRIBUTING and put in under `.github` for a cleaner root directory 😎 @francisco-guilherme
> docs: fix broken links & move CONTRIBUTING

- packages/code-editor/package.json
- packages/core/package.json
- packages/icons/package.json
- packages/lab/package.json
- packages/pentaho/package.json
- packages/shared/package.json
- packages/styles/package.json
- packages/uno-preset/package.json
- packages/utils/package.json
- packages/viz/package.json
Currently, we're only declaring our types via the (old) `types` option. The modern way is to use (which we do) the [_official_](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing) [`exports.types`](https://nodejs.org/api/packages.html#community-conditions-definitions) key instead. (we should keep `types` for backwards compatibility for now)
> fix(types): add exports types declaration

- packages/pentaho/src/Canvas/SidePanel/SidePanel.styles.tsx
- packages/styles/src/theme.ts
- packages/styles/src/utils.ts
Leverage CSS `color-mix` for the `theme.alpha` utility. We're already using this utility in some places, and [browser support is good](https://caniuse.com/mdn-css_types_color_color-mix)
> perf(theme): use color-mix for theme.alpha coloring

- packages/lab/src/Flow/base.ts
- packages/lab/src/Flow/hooks/useFlowNode.ts
- packages/lab/src/Flow/hooks/useNode.tsx
- packages/lab/src/Flow/stories/Flow.stories.tsx
- packages/lab/src/Flow/stories/SubFlow/Level.tsx
- packages/lab/src/Flow/stories/SubFlow/Node.tsx
- packages/lab/src/Flow/stories/SubFlow/NodeGroup.tsx
- packages/lab/src/Flow/stories/SubFlow/index.tsx
I tried creating some hooks in `useHvNode` so that the you wouldn't need to implement it in every node, like a onDragEnd event but was unsuccessful as it would always trigger to many re-renders. If you have an idea to remove some logic from the `Node` or `NodeGroup` let me know.
I also noted that we use the type property of the `reactflow` nodes in order to choose which component to use in a node, (i.e.: the Dimension Table node is of type: "dimensionTable"), but in order to create a group this property has to be 'group' creating multiple types of groups would have to be done some other way.
> feat(Flow): add groups to subflow sample

- packages/core/src/BaseSwitch/BaseSwitch.tsx
- packages/core/src/Switch/Switch.test.tsx
- packages/core/src/Switch/Switch.tsx
Narrow down `onChange` to be of `HTMLInputElement`, so that `event` can be used without casting
> fix(Switch): improve onChange types

- packages/core/src/Button/Button.tsx
- packages/core/src/Carousel/Carousel.tsx
- packages/core/src/Typography/Typography.tsx
- packages/core/src/Typography/utils.ts
- packages/styles/src/types.ts
- use `theme.base` instead of `theme.name` in components
- make `theme.base` output required (already is always present)
> fix(theme): theme.base required & usage in components

- packages/core/src/Calendar/CalendarHeader/CalendarHeader.styles.tsx
- packages/core/src/Calendar/CalendarNavigation/ComposedNavigation/ComposedNavigation.styles.tsx
- packages/core/src/Calendar/SingleCalendar/SingleCalendar.styles.tsx
- packages/core/src/Calendar/SingleCalendar/SingleCalendar.tsx
- packages/core/src/DatePicker/DatePicker.stories.tsx
- packages/styles/src/themes/ds3.ts
Related to #4290 but does not resolve it.
`HvDatePicker` requires lots of vertical height to be fully visible in `rangeMode` or when actions are present. After inspection, I noticed it's occupying more space than it needs to, due to:
- excessive padding of CalendarHeader input (`md` instead of `sm`)
- additive padding between CalendarHeader input and ComposedNavigation
- fixed heights and widths instead of dynamic according to content
also fixed DS3's `HvButton` `minWidth` specificity, which was causing issues
> fix(DatePicker): calendar spacing

- package-lock.json
mark `micromatch` as dev dependency while [CVE-2024-4067](https://nvd.nist.gov/vuln/detail/CVE-2024-4067) isn't addressed
this library is effectively a "dev" dependency of the cli package
> chore(security): mark micromatch as dev

- package-lock.json
- packages/styles/src/themes/pentahoPlus.ts
Changes to improve the multi button component for the Pentaho+ theme while we don't have specs:
- Border radius only for the first and last buttons. The border radius was also decreased.
- Shadow removed from the buttons when not selected to better distinct selected and unselected items.
- ℹ️I didn't add borders like the previous specs or change the background colors to follow the look and feel of the Pentaho theme. 
ℹ️ Let me know if you think that more changes are needed.
> fix(MultiButton): pentaho theme

- packages/cli/src/templates/Canvas/Node.tsx
- packages/core/src/Header/Actions/Actions.styles.tsx
- packages/core/src/Header/Brand/Brand.styles.tsx
- packages/core/src/Header/Header.styles.tsx
- packages/core/src/Header/Header.tsx
- packages/core/src/Header/Navigation/MenuBar/Bar.styles.tsx
- packages/core/src/Header/Navigation/MenuItem/MenuItem.styles.tsx
- packages/core/src/Header/Navigation/Navigation.styles.tsx
- packages/core/src/TreeView/stories/VerticalNavigation.tsx
- packages/core/src/VerticalNavigation/TreeView/TreeViewItem.tsx
- packages/core/src/VerticalNavigation/stories/Custom.tsx
- packages/lab/package.json
- packages/lab/src/Flow/Node/BaseNode.tsx
- packages/lab/src/Flow/stories/BaseHook/Node.tsx
- packages/styles/src/themes/pentahoPlus.ts
- Duplicated shadow removed from header
- Header style updated for Pentaho theme
- The `ts-ignore` added to ignore errors when creating CSS vars inside the `style` prop were removed to use type assertion instead.
> feat(header): pentaho theme updates and duplicated shadow removed

- packages/utils/package.json
Align `@hitachivantara/uikit-react-utils` to be CJS (not having `type: "module"`) like other UI Kit packages.
This is leading to issues when importing CJS modules `@hitachivantara/uikit-react-shared` in some cases (`vitest`):
```
Named export 'useEmotionCache' not found. The requested module '@hitachivantara/uikit-react-shared' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from '@hitachivantara/uikit-react-shared';
const { useEmotionCache } = pkg;
file:///.../node_modules/@hitachivantara/uikit-react-utils/dist/esm/hooks/useCss.js:5
import { useEmotionCache } from "@hitachivantara/uikit-react-shared";
^^^^^^^^^^^^^^^
SyntaxError: Named export 'useEmotionCache' …
```
> fix(utils): CJS by default to align with other UI Kit packages

- .config/license-compliancerc.js
- .github/workflows/tests.yml
- replace `license-checker-rseidelsohn` (has [a bug](https://github.com/lumada-design/hv-uikit-react/actions/runs/10636622443/job/29488809093?pr=4304#step:4:9)) with `license-compliance`
- it has better maintenance & supports a configuration file
- added config in `.config`  (thanks [cosmicconfig](https://github.com/cosmiconfig/cosmiconfig)) & explained exclusions with comments
> ci: replace licenses script

- packages/core/src/TimePicker/TimePicker.stories.tsx
- packages/core/src/TimePicker/TimePicker.tsx
- allow hiding seconds via the `showSeconds` prop (currently unused)
Addresses #4301
> feat(TimePicker): allow hiding seconds

- docs/foundation/Icons/Icons.stories.tsx
- packages/cli/src/templates/Canvas/index.tsx
- packages/cli/src/templates/Canvas/styles.tsx
- packages/core/src/DropdownButton/DropdownButton.styles.tsx
- packages/core/src/DropdownButton/DropdownButton.tsx
- packages/icons/src/IconBase.tsx
- packages/icons/src/IconSprite.tsx
- packages/icons/src/utils.ts
- add rotation transition to icons, as it's often used
- add `size` prop to replace `iconSize`, which is already deprecated without replacement
- accepts any `number`, `HvSize` (`"xs"`, `"sm"`, etc.), and `IconSize` (for backwards compatibility)
- svg container (`div`) grows dynamically according to the set svg size (eg. 120px svg -> 128px container)
- if the `size` prop is used, the colors are inherited by default (for forwards compatibility)
> [!IMPORTANT]
> Please don't squash the commits when merging
> feat(icons): add rotate animation & size prop

- packages/core/src/SimpleGrid/SimpleGrid.stories.tsx
- packages/core/src/SimpleGrid/SimpleGrid.styles.tsx
- packages/core/src/SimpleGrid/SimpleGrid.tsx
- packages/core/src/SimpleGrid/index.ts
- packages/core/src/SimpleGrid/types.ts
I noticed the `HvSimpleBreakpoint` was off by 1 pixel compared to the `HvGrid`'s breakpoints. After taking a look, I also noticed that `breakpoint.spacing` was not being used respected (fallback always to `spacing` prop)
- fix off-by-1 breakpoints
- fix custom `breakpoint.spacing` being ignored
- leverage CSS var for number of colums `--cols`, reducing dynamic styles & overall style injection
- add `xs` breakpoint - aligning with `HvBreakpoints`
- type docs & warnings regarding the names
> fix(SimpleGrid): breakpoints spacing

- packages/core/src/TreeView/TreeItem/useHvTreeItem.ts
when overriding the DefaultContent, users might want to pass `handleExpansion`/`handleSelection` to button or other elements.
> fix(TreeView): widen useHvTreeView handler types

- packages/core/src/Pagination/Pagination.tsx
- `Hidden` component from [MUI was deprecated so it was replaced](https://mui.com/material-ui/migration/v5-component-changes/#hidden)
> chore: remove deprecated mui hidden component

- packages/pentaho/src/Canvas/Toolbar/stories/Custom.tsx
we can't the title's value because it's controlled
> docs(Canvas): fix toolbar InlineEditor

- packages/core/src/TimeAgo/TimeAgo.stories.tsx
- packages/core/src/TimeAgo/TimeAgo.test.tsx
- packages/core/src/TimeAgo/TimeAgo.tsx
- packages/core/src/TimeAgo/formatUtils.ts
- packages/core/src/TimeAgo/useTimeAgo.ts
- This PRs addresses an issue where the locale was not being respected in specific scenarios. 
- This also removes the usage of `dayjs` and uses the native [`Intl.RelativeTimeFormat` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat)
- Updated some of the docs
- Updated tests
> fix(TimeAgo): respect locale and allow setting 12 or 24 hour format

- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Button/Button.tsx
- packages/styles/src/themes/pentahoPlus.ts
- packages/styles/src/tokens/colors.ts
- packages/styles/src/tokens/colorsPalette.ts
- added `primaryStrong` and `primarySubtle` tokens
- also exporting the `amber` colors as those were not being exported.
> feat(Button): review `HvButton` styles according to latest PD specs

- docs/tests/Pentaho.stories.tsx
- packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.spec.ts
- packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.stories.tsx
- packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.styles.tsx
- packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.test.tsx
- packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.tsx
- `hideCreateNew` property added and default to `false`: hides the "Create new" button if needed
- `fixed` property added at the tab level and default to `false`: prevents delete for specific tabs if needed
- `allowTabEdit` renamed to `disableTabEdit` for more of a "opt-in" behaviour: the prop defaults to `false` instead of `true`
- test updated/added
> feat(ToolbarTabs): create new and remove tab optional

- packages/code-editor/src/CodeEditor/CodeEditor.stories.tsx
- packages/code-editor/src/CodeEditor/CodeEditor.tsx
- packages/code-editor/src/CodeEditor/index.ts
- packages/code-editor/src/CodeEditor/languages/index.ts
- packages/code-editor/src/CodeEditor/languages/xml.ts
- packages/code-editor/src/CodeEditor/plugins.ts
- packages/code-editor/src/CodeEditor/stories/Xml/Xml.tsx
- packages/code-editor/src/CodeEditor/stories/Xml/utils.tsx
- `hvXmlFormatter` exported in case users may need it: the formatter only works if there are no errors in the code (not using XSD validation) because the formatter was removing unclosed tags, etc
- `disableAutoFormat` property added to disable auto format if needed
- Auto format triggered on mount
- XML story updated to show the new features and to show how to get the validation state
> feat: export xml code formatter and optional auto format

- docs/tests/Components.stories.tsx
- package-lock.json
- packages/core/src/Accordion/Accordion.styles.tsx
- packages/core/src/Accordion/Accordion.tsx
- packages/core/src/Banner/BannerContent/ActionContainer/ActionContainer.tsx
- packages/core/src/ButtonBase/ButtonBase.styles.ts
- packages/core/src/ButtonBase/ButtonBase.test.tsx
- packages/core/src/ButtonBase/ButtonBase.tsx
- packages/core/src/ButtonBase/index.ts
- packages/core/src/Calendar/CalendarNavigation/MonthSelector/MonthSelector.styles.tsx
- packages/core/src/Calendar/CalendarNavigation/MonthSelector/MonthSelector.tsx
- packages/core/src/Calendar/SingleCalendar/CalendarCell.styles.tsx
- packages/core/src/Calendar/SingleCalendar/CalendarCell.tsx
- packages/core/src/ColorPicker/SavedColors/SavedColors.tsx
- packages/core/src/Section/Section.stories.tsx
- packages/core/src/Section/Section.tsx
- packages/core/src/hooks/useExpandable.ts
- packages/core/src/index.ts
- add `HvButtonBase` component
- to use whenever we need an unstyled button with the outline/hover styles, and correct disabled/`type`/etc
- `HvButton` doesn't use it yet to avoid duplicated classes & issues with polymorphic `ref`s
- add `useAccordion`
- simple refactor based on [react-aria](https://www.npmjs.com/package/@react-aria/accordion?activeTab=code)'s
- fixes missing roles/`id`s
- use `HvButtonBase` & `useAccordion` in components
- various consistency & visual issues in DatePicker resolved
UI changes include Accordion & DatePicker buttons being consistent with other buttons/list items.
Changes accepted in Chromatic
> feat: add ButtonBase component & useAccordion

- packages/core/src/Loading/Loading.stories.tsx
- packages/core/src/Loading/Loading.styles.tsx
- packages/core/src/Loading/Loading.tsx
- packages/core/src/LoadingContainer/LoadingContainer.stories.tsx
- packages/core/src/LoadingContainer/LoadingContainer.styles.ts
- packages/core/src/LoadingContainer/LoadingContainer.tsx
- fix `HvLoadingContainer` opacity
- add Chromatic test
- add better custom color Loading support (eg. "inherit")
- refactor animations to use CSS vars, reducing code complexity
- fix Loading text margin
- improve `LoadingButton` samples
- simplify code
- use `"inherit"` color which works well multi-theme
> fix(Loading): custom colors & LoadingContainer opacity

- .github/actions/install-dependencies/action.yml
- .storybook/test-runner.ts
- .storybook/types.ts
- docs/tests/Components.stories.tsx
- docs/tests/Lab.stories.tsx
- docs/tests/Pentaho.stories.tsx
- docs/tests/Widgets.stories.tsx
- docs/tests/utils.ts
- nx.json
- package-lock.json
- package.json
- packages/code-editor/package.json
- packages/core/package.json
- packages/lab/package.json
- packages/pentaho/package.json
- packages/shared/package.json
- packages/styles/package.json
- packages/uno-preset/package.json
- packages/utils/package.json
- packages/utils/src/hooks/useCss.ts
- packages/utils/src/utils/classes.ts
- packages/viz/package.json
- tsconfig.build.json
- add CSF `parameters` (partial) typings
- improve `typecheck` script; we were basically running the script `N` times (for each package)
- now it's much faster, with better coverage (whole repo), and errors aren't duplicated
- improve `classes` type inference
- use built-in `setup-node`'s install cache
> chore: typescript improvements in docs & build

- packages/code-editor/src/CodeEditor/languages/xml.ts
Fixes:
- When typing `>` after a `/` when closing a self closing tag, the autocomplete was adding the closing tag of the element:
https://github.com/user-attachments/assets/8b4c7ac5-bdbc-4389-9b30-30993eb75e2d
With this fix, the closing tag is only added if the element is not self closing.
> fix(CodeEditor): xml autocomplete closing self closing tag

- packages/core/src/Badge/Badge.stories.tsx
- packages/core/src/Badge/Badge.styles.tsx
- packages/core/src/Badge/Badge.test.tsx
- packages/core/src/Badge/Badge.tsx
- packages/styles/src/themes/pentahoPlus.ts
- add missing `forwardRef`
- extend `label` to support any `ReactNode` instead of only string
- also handles numeric values (same as `count`). deprecate `count` as it's now redundant
- refactor styles so they're easier to override
- add Pentaho+ styles
> feat(Badge): label prop supports ReactNode & handles numbers

- packages/core/src/InlineEditor/InlineEditor.stories.tsx
- packages/core/src/InlineEditor/InlineEditor.test.tsx
- packages/core/src/InlineEditor/InlineEditor.tsx
When controlling the inline editor, the "Escape" functionality was not working: pressing Escape was not returning the cached value to the user in order for them to update the inline editor accordingly
> fix(InlineEditor): value not updated on escape when controlled

- packages/code-editor/src/CodeEditor/languages/xml.ts
Fixes the following:
https://github.com/user-attachments/assets/c8a57d53-a2b0-45b1-8499-ce18435e3d3b
- The tag shouldn't be automatically closed since `>` was written inside an opened attribute.
After:
https://github.com/user-attachments/assets/4796501e-35d6-4750-9655-1bbdae29c665
> fix(CodeEditor): not autoclosing tag if attributes are opened

- packages/core/src/Forms/Suggestions/Suggestions.styles.tsx
- packages/core/src/Forms/Suggestions/Suggestions.tsx
- packages/core/src/Input/Input.test.tsx
- packages/core/src/Input/Input.tsx
- `enablePortal` property added to the input and suggestions components to enable portal for the popper
- `suggestOnFocus` property added to the input component to enable triggering the suggestions when focusing on the input
> feat(Input): enable portal for suggestions and suggest on focus

- packages/core/src/Loading/Loading.stories.tsx
- packages/core/src/Loading/Loading.styles.tsx
- packages/styles/src/themes/pentahoPlus.ts
- added the color override for the color token `brand` in the P+ theme
- I needed to change the animation a bit: because we were using `scale` to change the height of each bar, now that it has a rounded border the change in scale changes the rounded borders as the element grows and shrinks. I opted to animate the height instead.
> feat(Loading): update to PD 0.2 specs

- packages/styles/src/themes/pentahoPlus.ts
Add CSS font fallbacks for `Inter` font
I found this nice fallback strategy, but currently there isn't a simple way to include this per-theme: https://developer.chrome.com/blog/framework-tools-font-fallback
> style(theme): add Inter font fallbacks to Pentaho+ theme

- packages/core/src/Table/TableCell/TableCell.styles.tsx
- packages/core/src/Table/TableHeader/TableHeader.styles.tsx
- packages/core/src/Table/TableRow/TableRow.styles.tsx
- packages/core/src/Table/stories/TableSamples/GroupedRows.tsx
- add `alignContent` styles to support non-table displays (eg. when using custom table components or `useBlockLayout`)
- fix GroupedRows sample
> fix(Table): add alignContent to support non-table displays

- packages/core/src/MultiButton/MultiButton.styles.tsx
- packages/core/src/MultiButton/MultiButton.tsx
- packages/styles/src/themes/pentahoPlus.ts
change `HvMultiButton` `split` separator to use `::after` instead of HMTL elements, which inherits button's color, height, etc. (+disabled) - making it easier to style and simplifies DOM
Visual changes:
- the 0.5/1px changes are expected
- indirectly fixes the "split separator" when `disabled` in Pentaho+ theme
> style(MultiButton): change split to use ::after

- packages/core/src/Tooltip/Tooltip.stories.tsx
- packages/core/src/Tooltip/Tooltip.styles.tsx
- packages/core/src/Tooltip/Tooltip.tsx
- fix Tooltip padding styles
- deprecate tooltip "custom" classes
- we have lots of `HvTooltip` built-in classes that are unused in the component. they're there to be used in a sample ☠️
> fix(Tooltip): align styles & deprecate external classes

- packages/core/src/Table/hooks/useRowExpand.tsx
- the expansion icon direction is flipped
- improve types & safety
> fix(Table): row expansion arrow direction & types

- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Button/Button.styles.ts
- packages/core/src/Button/Button.test.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/Button/types.ts
- packages/core/src/DropDownMenu/DropDownMenu.tsx
- packages/core/src/MultiButton/MultiButton.tsx
- packages/core/src/index.ts
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/ds5.ts
- packages/styles/src/themes/pentahoPlus.ts
- packages/styles/src/tokens/radii.ts
Changes:
- deprecate `HvButtonRadius`, `HvButtonSize` in favor or global `HvRadius` & `HvSize`
- refactor/improve Button styles.
- reduce specificity with `:where`
- reduce style overrides with `contained` class
- add `color` prop to allow overriding button color & adapt button styles to support it
- add `:hover` & `:active` styles based on `color`
- ~add text color being inferred from `color-constrast`~
- Hoist NEXT "semantic" button styles to the theme
- Add new Pentaho+ styles
- Align P+ `HvSelect`'s outline with the new "softer" `subtle` button outline
Expected visual changes:
- NEXT disabled state styles update
- P+ button
- size always `32px` size due to border always existing (aligned with NEXT)
- styles update (primarily on the `subtle` variants)
> feat(Button): better color handling & Pentaho+ styles

- apps/docs/src/pages/components/Playground.tsx
- apps/docs/src/pages/components/_meta.ts
- apps/docs/src/pages/components/avatar.mdx
- apps/docs/src/pages/components/badge.mdx
- apps/docs/src/pages/components/banner.mdx
- apps/docs/src/pages/components/button.mdx
- add the possibility of overriding the custom control for enums (`Select`) with a `Slider` or a `RadioGroup`
- also add the `Banner` page
> docs: add slider and radio control renderers

- packages/core/src/BaseCheckBox/BaseCheckBox.tsx
- packages/core/src/BaseRadio/BaseRadio.tsx
- packages/core/src/BaseSwitch/BaseSwitch.tsx
- packages/core/src/Tab/Tab.styles.tsx
- packages/core/src/Tab/Tab.tsx
- packages/core/src/Tabs/Tabs.stories.tsx
- packages/core/src/Tabs/Tabs.styles.tsx
- packages/core/src/Tabs/Tabs.tsx
- packages/core/src/providers/ThemeProvider.tsx
- packages/styles/src/themes/ds5.ts
- packages/styles/src/themes/pentahoPlus.ts
- fix disabled icon colors
- simplify styles overrides in `Tab` (inherited to `primary` color) & align DS5 color
- cleanup `disableRipple` instances already set in `HvProvider`
> fix(Tabs): disabled icon color & simplify styles overrides

- packages/styles/src/themes/pentahoPlus.ts
updated the floating variant to use the underlying tab selected indicator animation to keep consistency with remaining tabs
> chore: add animation to tab change in floating mode

- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Button/Button.styles.ts
- packages/styles/src/themes/pentahoPlus.ts
- fix radius override in Pentaho+ theme
- fix semantic styles
- improve visual test sample
- add radius
- remove (redundant) `disabled` samples
- add icons & ghost variant in custom colors
- use `warning` colore more frequently in samples, as it's the most "complex" color (in terms of overrides & contrast)
> fix(Button): radius override & semantic styles

- apps/docs/src/components/Description.tsx
- apps/docs/src/components/Props.tsx
- apps/docs/src/components/code/Live.tsx
- apps/docs/src/pages/components/Playground.tsx
- apps/docs/src/pages/components/_meta.ts
- apps/docs/src/pages/components/avatar.mdx
- apps/docs/src/pages/components/badge.mdx
- apps/docs/src/pages/components/banner.mdx
- apps/docs/src/pages/components/button.mdx
- apps/docs/src/pages/components/card.mdx
- apps/docs/src/pages/components/checkBox.mdx
- apps/docs/src/pages/components/loading.mdx
- apps/docs/src/pages/components/loadingContainer.mdx
- apps/docs/src/pages/globals.css
- apps/docs/src/utils/utils.ts
- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Loading/Loading.stories.tsx
- Add props tables for sub-components
- Prop search works for all tables in the page
- If the component has sub-components then the description portion of the page will list them
- Added doc page for the `Loading` and `LoadingContainer` components
- Refactor the control renderer generation functionality
> docs: add subcomponents props tables

- packages/core/src/Panel/Panel.styles.tsx
- packages/core/src/Section/Section.styles.tsx
- packages/core/src/Section/Section.tsx
- packages/core/src/Snackbar/Snackbar.tsx
- packages/core/src/Table/TableCell/TableCell.tsx
- packages/core/src/Table/TableHeader/TableHeader.tsx
- packages/core/src/TableSection/TableSection.styles.tsx
- packages/core/src/utils/helpers.ts
- packages/styles/src/utils.ts
- change `HvPanel` to inherit `borderRadius`
- fix `HvSection` actions alignment (right padding, `absolute` > `flex`)
- also rename `spaceTop` > `hasHeader`
- improve `theme.spacing` calc for `0` case value (`0` instead of `calc(0 * var(--theme-space-unit))`)
- improve `capitalize` value inference, to get rid of some `as` casts
> fix: Section actions alignment & Panel borderRadius

- .github/scripts/changelog.js
- .github/workflows/release.yml
- Change Slack release notification to be similar to [`/releases`](https://github.com/lumada-design/hv-uikit-react/releases)'s
- improve CI docs/logs on exiting early because:
- no packages were published (no changes made)
- no new `core` release (hence no `/release` + notification)
> ci(release): improve release slack release message

- .gitignore
- packages/core/src/Button/Button.styles.ts
- packages/core/src/Card/Card.tsx
- packages/core/src/Forms/Adornment/Adornment.tsx
- packages/core/src/Input/Input.styles.tsx
- packages/core/src/Input/Input.test.tsx
Fix for:
```
MUI: You are providing a disabled `button` child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.
```
(leverages `HvButtonBase` +  `focusableWhenDisabled`)
Also adds
- missing `useDefaultProps`
- missing `HvCard` `ref`
> fix(Input): adornment tooltip when disabled

- packages/core/src/Button/Button.tsx
- packages/core/src/TimePicker/TimePicker.stories.tsx
- packages/core/src/TimePicker/Unit/Unit.tsx
- packages/core/src/ToggleButton/ToggleButton.tsx
- allow `aria-pressed=false` in `HvButton` & reuse it in `HvToggleButton`
- refactor `TimePicker`
- use `HvButton` instead of `HvToggleButton` (`aria-pressed` doesn't make sense)
- use `HvBaseInput` instead of `HvInput` (we don't need `HvInput`'s features)
- update deprecated `state.validationState` API
> fix: ToggleButton usage

- packages/core/src/DropDownMenu/DropDownMenu.tsx
- packages/utils/src/utils/classes.ts
- move `getPrevNextFocus` inside the block where it's needed, for SSR support & performance reasons; as it uses `document.querySelectorAll` every render
- memo `classes`
> fix(DropDownMenu): move getPrevNextFocus for perf & ssr support

- packages/pentaho/src/Canvas/SidePanel/SidePanel.styles.tsx
alignment is to the top of the button (like `align: "start"`), so there's less chance of button overlap
> fix(Canvas): panel button position

- apps/docs/src/components/code/Controls.tsx
- apps/docs/src/components/code/Playground.tsx
- improve codeblock in Playground sample
- fix types (boolean values, custom objects)
- split props by `\n`
- indent children
> docs: improve Playground code

- tsconfig.json
This isn't needed as the packages are "installed" under the root `node_modules`, which our monorepo (packages/*, apps/*) and storybook understands
Follow up to https://github.com/lumada-design/hv-uikit-react/pull/4453, but this doesn't seem to be enough to made IDE's not suggest `packages/*/src` imports - see ([baseUrl](https://www.typescriptlang.org/tsconfig/#baseUrl))
> chore: remove package path alias & baseUrl

- apps/docs/src/components/code/Playground.tsx
- apps/docs/src/pages/components/overflow-tooltip.mdx
- This also adds the possibility of passing a decorator to the playground to be used around the component
> docs: add `OverflowTooltip` documentation

- packages/cli/src/templates/DetailsView/Table.tsx
- packages/core/src/Table/stories/TableSection/CompleteTableSection.tsx
- packages/core/src/TableSection/TableSection.styles.tsx
- fix missing borderRadius in `HvTableSection` when `HvLoadingContainer` is present
> fix(TableSection): border-radius

- packages/core/src/ColorPicker/Fields/Fields.tsx
value of 0 was being interpreted as `false`
> fix(ColorPicker): unable to set R/G/B components as 0

- apps/docs/src/components/code/Playground.tsx
- apps/docs/src/pages/components/accordion.mdx
- apps/docs/src/pages/components/input.mdx
- apps/docs/src/pages/components/loading-container.mdx
- apps/docs/src/pages/components/section.mdx
- apps/docs/src/pages/components/select.mdx
- apps/docs/src/pages/components/tooltip.mdx
- fixes `children` rendering in `Playground`
- we should use actual `children`, not `children={}` (requires fragments)
- this also seems to fix the `"No Display Name"` in children components
> docs(Playground): fix children rendering & component name

- packages/core/src/Calendar/Calendar.tsx
- packages/core/src/Calendar/CalendarHeader/CalendarHeader.tsx
- packages/core/src/Calendar/CalendarUtils.test.tsx
- packages/core/src/Calendar/SingleCalendar/SingleCalendar.tsx
- packages/core/src/Calendar/utils.tsx
- packages/core/src/DatePicker/DatePicker.stories.tsx
- packages/core/src/DatePicker/DatePicker.test.tsx
- packages/core/src/DatePicker/DatePicker.tsx
- packages/core/src/DatePicker/utils.tsx
- packages/core/src/TimeAgo/TimeAgo.tsx
- packages/core/src/TimePicker/TimePicker.test.tsx
- packages/core/src/TimePicker/TimePicker.tsx
- align DatePicker/Calendar input & label values
- fix forced locale format
- remove `dayjs` dependency in favour on `Intl` in DatePicker/Calendar
- reuse `DEFAULT_LOCALE`
- dedupe type definitions in `HvCalendar` sub-components
- improve typings
> fix(DatePicker): input locale & align input/label values

- .eslintrc.json
- apps/docs/src/pages/components/loading.mdx
- apps/docs/src/pages/components/skeleton.mdx
- apps/docs/src/pages/components/tooltip.mdx
- packages/core/src/Drawer/Drawer.test.tsx
- packages/core/src/TimeAgo/TimeAgo.test.tsx
- packages/viz/src/utils/index.ts
- fix `loading-container` & `overflow-tooltip` links (missing `-`)
- disallow parent barrel file imports (for performance & circular dependency imports)
> docs: fix component urls

- packages/core/src/BaseInput/BaseInput.tsx
- packages/core/src/ColorPicker/ColorPicker.test.tsx
- packages/core/src/ColorPicker/Fields/Fields.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/TextArea/TextArea.tsx
- align `HvInput` & `HvBaseInput` types
- and align them with the underlying `<input>` (eg. `value`/`defaultValue`)
- add `HvInput` generics so we can specify when it's a `textarea` (when needed)
- `HvBaseInput` extends from MUI's `InputBase`
> fix(Input): extend HvBaseInput types

- packages/core/src/ColorPicker/ColorPicker.stories.tsx
- packages/core/src/ColorPicker/ColorPicker.styles.tsx
- packages/core/src/ColorPicker/ColorPicker.tsx
- fix `HvColorPicker` when in `flex` container, so that the "header" doesn't jump around depending on the HEX value (eg. _#AAAAAA_ is much wider than _#111111_)
- refactor to not use `Checkbox`
- remove dynamic `css()` styles in components
> fix(ColorPicker): color value width in flex containers

- apps/docs/src/components/code/Controls.tsx
- apps/docs/src/components/code/Playground.tsx
- apps/docs/src/pages/components/accordion.mdx
- apps/docs/src/pages/components/avatar.mdx
- apps/docs/src/pages/components/badge.mdx
- apps/docs/src/pages/components/banner.mdx
- apps/docs/src/pages/components/button.mdx
- apps/docs/src/pages/components/card.mdx
- apps/docs/src/pages/components/checkbox.mdx
- apps/docs/src/pages/components/date-picker.mdx
- apps/docs/src/pages/components/form-element.mdx
- apps/docs/src/pages/components/input.mdx
- apps/docs/src/pages/components/loading-container.mdx
- apps/docs/src/pages/components/loading.mdx
- apps/docs/src/pages/components/overflow-tooltip.mdx
- apps/docs/src/pages/components/radio-group.mdx
- apps/docs/src/pages/components/radio.mdx
- apps/docs/src/pages/components/section.mdx
- apps/docs/src/pages/components/select.mdx
- apps/docs/src/pages/components/skeleton.mdx
- apps/docs/src/pages/components/tag.mdx
- apps/docs/src/pages/components/textarea.mdx
- apps/docs/src/pages/components/time-picker.mdx
- apps/docs/src/pages/components/tooltip.mdx
uniformize samples
- remove hanging `theme`, which is always unused
- always use tsx syntax
- meta shorthand
> docs: improve number control/rendering

- apps/docs/src/pages/components/select.mdx
- packages/core/src/Select/Select.test.tsx
- packages/core/src/Select/Select.tsx
- packages/core/src/Select/stories/Form.tsx
The `options` object was already part of the API, but it wasn't implemented or tested for
`HvOptionGroup` also wasn't being documented
> feat(Select): allow passing the options array

- packages/core/src/Select/Option.tsx
- packages/core/src/Select/Select.test.tsx
The `...others` spread in `HvOption` is squashing the internal `useOption` event handlers
> fix(Select): merge HvOption events

- packages/core/src/FormElement/Suggestions/Suggestions.styles.tsx
- packages/core/src/FormElement/Suggestions/Suggestions.tsx
- packages/core/src/ListContainer/ListItem/ListItem.tsx
- packages/core/src/Select/Select.styles.ts
- packages/core/src/Select/Select.tsx
- packages/styles/src/themes/pentahoPlus.ts
- Align `HvSuggestions` border with other form Input elements.
- Align `HvSelect` with `HvSuggestions` padding
> fix(Suggestions): align border with dropdown components

- apps/docs/src/components/code/Controls.tsx
- apps/docs/src/pages/components/file-uploader.mdx
- packages/core/src/FileUploader/DropZone/DropZone.styles.tsx
- packages/core/src/FileUploader/DropZone/DropZone.tsx
- packages/core/src/FileUploader/FileUploader.stories.tsx
- packages/core/src/FileUploader/FileUploader.styles.ts
- packages/core/src/FileUploader/FileUploader.test.tsx
- packages/core/src/FileUploader/FileUploader.tsx
- packages/core/src/FileUploader/stories/simulators.ts
- packages/core/src/FileUploader/utils.ts
- align `label` with other form elements
- align `acceptedFiles` with the native `accept` attribute
- add missing `classes` and `fileUploaderClasses`
- refactor DropZone styles & classes
- add docs, using new `label` & `accept` props
> feat(FileUploader): add classes, label, accept props

- packages/code-editor/src/CodeEditor/languages/sql.ts
Table name added in front of the column name for more context:
https://github.com/user-attachments/assets/7924083b-18c7-4e44-b5b0-e004365e3da0
> feat: add table to column in SQL autocomplete

- packages/code-editor/src/CodeEditor/languages/sql.ts
Sometimes the wrong suggestions are showing because instead of getting the text up until the cursor we are getting all the text in the code editor:
https://github.com/user-attachments/assets/33d6309f-8787-4cee-9942-c928e379a0c7
- In the video above, the suggestions given at the end are wrong. The tables are shown and not the columns because the code is taking into account the `FROM` keyword and not `SELECT`.
> fix: get text until cursor and not all text in SQL autocomplete

- .config/test.setup.tsx
- package-lock.json
- packages/code-editor/package.json
- packages/code-editor/src/CodeEditor/languages/sql.test.tsx
- packages/code-editor/src/CodeEditor/languages/sql.ts
- packages/core/src/Banner/Banner.stories.tsx
- packages/core/src/Card/Card.stories.tsx
- packages/core/src/Carousel/Carousel.stories.tsx
- packages/core/src/CheckBox/CheckBox.stories.tsx
- packages/core/src/Controls/Controls.stories.tsx
- packages/core/src/DatePicker/DatePicker.stories.tsx
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dropdown/stories/Dropdown.stories.tsx
- packages/core/src/FileUploader/FileUploader.stories.tsx
- packages/core/src/Header/Header.stories.tsx
- packages/core/src/Input/Input.stories.tsx
- packages/core/src/ListContainer/ListContainer.stories.tsx
- packages/core/src/Radio/Radio.stories.tsx
- packages/core/src/Select/Select.stories.tsx
- packages/core/src/Snackbar/Snackbar.stories.tsx
- packages/core/src/Switch/Switch.stories.tsx
- packages/core/src/Tabs/Tabs.stories.tsx
- packages/core/src/TreeView/stories/TreeView.stories.tsx
- packages/core/src/VerticalNavigation/VerticalNavigation.stories.tsx
The Sql suggestions were not taking into account that the tables and columns names can be enclosed in delimiters when they contain special characters. The possible delimiters are double quotes, backticks and square brackets depending on the database.
> fix(CodeEditor): account for special characters inside tables and columns names

- packages/code-editor/src/CodeEditor/languages/sql.ts
- The available columns are shown when the last keyword is `WHEN`
- The suggestions are shown when writing SQL expressions in lower case
> fix(CodeEditor): make SQL suggestions case insensitive and show columns for WHEN keyword

- apps/docs/src/pages/components/badge.mdx
- packages/core/src/Badge/Badge.stories.tsx
- packages/core/src/Badge/Badge.tsx
- add support `children` prop (already in typings)
- deprecate `text`/`textVariant` props
> feat(Badge): support children prop

- apps/docs/src/components/code/Controls.tsx
- apps/docs/src/pages/components/dropdown-menu.mdx
Includes a small fix to the `Controls` of the `Playground` component.
> docs: add `DropdownMenu` documentation

- apps/docs/src/pages/components/dialog.mdx
- packages/core/src/Dialog/Actions/Actions.styles.tsx
- packages/core/src/Dialog/Actions/Actions.tsx
- packages/core/src/Dialog/Content/Content.styles.tsx
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styles.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/Dialog/Title/Title.styles.tsx
- packages/core/src/Dialog/Title/Title.tsx
- packages/core/src/Dialog/context.ts
- packages/core/src/Dialog/stories/FormStory.tsx
- packages/core/src/Section/Section.stories.tsx
- packages/core/src/Section/Section.styles.tsx
- packages/core/src/Section/Section.tsx
- packages/core/src/TableSection/TableSection.styles.tsx
- packages/lab/src/Flow/Node/Node.tsx
- packages/lab/src/Flow/Sidebar/SidebarGroup/SidebarGroup.tsx
- packages/lab/src/Wizard/WizardContainer/WizardContainer.styles.tsx
- packages/lab/src/Wizard/WizardContainer/WizardContainer.tsx
- packages/lab/src/Wizard/WizardTitle/WizardTitle.styles.tsx
- packages/lab/src/Wizard/WizardTitle/WizardTitle.tsx
- add `fullHeight` prop to make it easier to build full-height Dialogs
- very useful to prevent layout shifts in "complex" dialogs
- currently user has to do `classes={{paper: "w-full"}}`, which is a bit obscure
- fix styles when `HvDialog` is larger/100%
- Title/Actions is flexing, instead of content
- fix Title styles when custom `children` content
- make `HvDialogActions` using `HvDialog`'s `backgroundColor`
- apply new props/fixes to the `Form` example & use it in Chromatic
- align chevron icon usage (`Down` -> `DropDownXS`)
- fix section border
> feat(Dialog): add `fullHeight` & fix styles on large heights

- apps/docs/src/components/Main.tsx
- apps/docs/src/components/code/Controls.tsx
- apps/docs/src/pages/components/avatar.mdx
- packages/core/src/Avatar/Avatar.stories.tsx
- Add custom Emotion cache to the `HvProvider` on the documentation to ensure proper styles order
- Fix Avatar samples
- Tweak Slider control styles on the playground to make better use of space
> docs: ensure styles order on documentation

- apps/docs/src/pages/components/radio-group.mdx
- apps/docs/src/pages/components/select.mdx
- apps/docs/src/pages/components/snackbar-provider.mdx
- packages/core/src/CheckBox/CheckBox.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/Radio/Radio.tsx
- packages/core/src/RadioGroup/RadioGroup.tsx
- packages/core/src/Snackbar/Snackbar.tsx
- packages/core/src/SnackbarProvider/SnackbarProvider.tsx
- packages/core/src/Switch/Switch.tsx
- packages/core/src/Tag/Tag.tsx
- packages/core/src/ToggleButton/ToggleButton.tsx
- packages/core/src/TreeView/TreeView.tsx
- packages/lab/src/StepNavigation/StepNavigation.tsx
- convert component docs from HTML to MD (ie. `<b>` -> `**`)
- add JSDoc to (documented) components without them
- minor doc reviews
> docs: review components' JSDoc

- .github/actions/install-dependencies/action.yml
- README.md
- extend node version support to `16+` instead of explicitly `16` or `18`
- this is just in docs, we actually don't enforce any node version in packages
- use `node@22` in CI
> ci: bump to node@22

- packages/core/src/BulkActions/BulkActions.test.tsx
- packages/core/src/BulkActions/BulkActions.tsx
- packages/core/src/CheckBoxGroup/CheckBoxGroup.test.tsx
- packages/core/src/CheckBoxGroup/CheckBoxGroup.tsx
- packages/core/src/FilterGroup/FilterGroup.test.tsx
- packages/core/src/FilterGroup/RightPanel/RightPanel.tsx
- packages/core/src/utils/CounterLabel.tsx
- update "Select All" checkbox label `All (X)` to `0 / X`
- add CounterLabel utility to reuse in various components that use this
> fix: update align select all checkbox labels

- package-lock.json
- packages/core/src/BaseInput/BaseInput.styles.tsx
- packages/core/src/BaseInput/BaseInput.tsx
- packages/core/src/Calendar/CalendarHeader/CalendarHeader.styles.tsx
- packages/core/src/Calendar/CalendarHeader/CalendarHeader.tsx
- packages/core/src/InlineEditor/InlineEditor.styles.tsx
- packages/core/src/InlineEditor/InlineEditor.tsx
- packages/core/src/Input/Input.styles.tsx
- packages/core/src/Input/Input.test.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/Select/Select.styles.ts
- packages/core/src/TagsInput/TagsInput.styles.tsx
- packages/core/src/TextArea/TextArea.styles.tsx
- packages/core/src/TimePicker/Unit/Unit.styles.ts
- packages/core/src/TimePicker/Unit/Unit.tsx
- packages/styles/src/CssBaseline.ts
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/pentahoPlus.ts
- remove `Global` styles in favour of `classes.root` usage
- merge the 2 redundant `HvBaseInput` "containers"
- now there's only a container and the `input` (coming from MUI)
- remove the bloated `ds3` `inputBorderContainer` logic, in favour of `::after` overrides
> fix(BaseInput): simplify structure

- packages/core/src/BaseInput/validations.ts
- packages/core/src/FormElement/Adornment/Adornment.styles.tsx
- packages/core/src/FormElement/Adornment/Adornment.test.tsx
- packages/core/src/FormElement/Adornment/Adornment.tsx
- packages/core/src/Input/Input.styles.tsx
- packages/core/src/Input/Input.test.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/Input/SearchBox.stories.tsx
- packages/core/src/TextArea/TextArea.tsx
- remove `useControlled` logic from `HvInput` (`HvInputBase` already has it)
- this allows for native uncontrolled behaviour (like form reset) to work
- fix `endAdornment` not allowing non `ReactElement` values
- add support for focusable `HvAdornment`
- fix showPassword toggle not being focusable
fixes HVUIKIT-7060
> fix(Input): support native uncontrolled behaviours & text adornment

- packages/core/src/BaseInput/BaseInput.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/Tag/Tag.tsx
- packages/core/src/TagsInput/TagsInput.styles.tsx
- packages/core/src/TagsInput/TagsInput.tsx
- packages/core/src/hooks/useFocus.ts
- packages/core/src/utils/focusUtils.ts
- packages/styles/src/themes/ds3.ts
- overhauls `HvTagsInput` by simplifying DOM structure (removed `HvListContainer`/`HvListItem`/`HvInput`) and leveraging flex features (fixes #4553)
- fix label<->input id mapping
- review focus & internal state management
- make input uncontrolled & use native focus `previousElementSibling`
- remove internal state & `useEffects`
> fix(TagsInput): focus management & input size issues

- packages/core/src/BaseInput/BaseInput.styles.tsx
Safari visual tests already cover this padding scenario
> fix(input): internal padding when autofilling

- package-lock.json
- tsconfig.build.json
types rollup (`vite-plugin-dts`) is crashing for module: "preserve"
> build: fix rollup types error

- .github/workflows/pr.yml
- Chromatic already has its own Storybook PR deployment
- this is also our slowest workflow step
> ci: disable storybook PR deployment

- apps/docs/src/pages/components/tags-input.mdx
- packages/core/src/Tag/stories/Tag.stories.tsx
- packages/core/src/TagsInput/TagsInput.stories.tsx
- packages/core/src/TagsInput/TagsInput.styles.tsx
- ensure input isn't inlined along with label (`clear: "both"`)
- update `HvTagsInput` docs to reflect that `resizable` is opt-in
- update docs
issue:
> fix(TagsInput): ensure input isn't inlined along with label

- packages/core/src/ActionsGeneric/ActionsGeneric.tsx
- packages/core/src/AppSwitcher/Action/Action.styles.tsx
- packages/core/src/Button/Button.styles.ts
- packages/core/src/Button/Button.tsx
- packages/core/src/DotPagination/DotPagination.styles.tsx
- packages/core/src/FormElement/Adornment/Adornment.styles.tsx
- packages/core/src/ListContainer/ListItem/ListItem.styles.tsx
- packages/core/src/Tabs/Tab/Tab.styles.tsx
- packages/core/src/VerticalNavigation/NavigationSlider/NavigationSlider.styles.tsx
- packages/core/src/VerticalNavigation/TreeView/TreeViewItem.styles.tsx
- packages/core/src/VerticalNavigation/stories/Custom.tsx
- packages/icons/scripts/utils.ts
- packages/icons/src/IconBase.tsx
- packages/pentaho/src/Canvas/PanelTab/PanelTab.styles.tsx
- templates/Canvas/StatusEdge.tsx
- let NEXT icons inherit icon color for the the "default" (single `secondary` color) case
- remove (now) redundant overrides
- fixes some icon issues (readOnly, disabled `HvAppSwitcherAction`)
> feat(icons): inherit icon color

- packages/core/src/AppSwitcher/Action/Action.styles.tsx
- packages/core/src/BaseDropdown/BaseDropdown.styles.tsx
- packages/core/src/Loading/Loading.styles.tsx
- packages/core/src/Loading/Loading.tsx
- packages/core/src/Typography/Typography.styles.ts
- packages/core/src/VerticalNavigation/TreeView/TreeViewItem.styles.tsx
- packages/styles/src/types.ts
adds `"inherit"` to `HvTypography`
opened because https://github.com/lumada-design/hv-uikit-react/pull/4575 found a few coloring issues in icons, so doing the same for the Typography
UPDATE: issues were found in disabled/readOnly states
> feat(Typography): inherit text color

- apps/docs/src/components/Examples.tsx
- apps/docs/src/examples/charts/LineChartStreaming.tsx
- apps/docs/src/pages/charts/bar-chart.mdx
- apps/docs/src/pages/charts/line-chart.mdx
- apps/docs/src/pages/examples/_meta.ts
- apps/docs/src/pages/examples/charts.mdx
- adds documentation for the `LineChart` component
- adds new `charts` examples section with one example
- also added the `UI Kit Charts` collection to the [UI Kit StackBlitz collections](https://stackblitz.com/orgs/github/lumada-design/collections) with a sample of a chart that loads Arrow data
> docs: add `LineChart` documentation

- apps/docs/src/pages/charts/_meta.ts
- apps/docs/src/pages/charts/bar-chart.mdx
- apps/docs/src/pages/charts/get-started.mdx
- apps/docs/src/pages/charts/scatter-plot.mdx
- apps/docs/src/pages/documentation/_meta.ts
⚠️ This PR also moves the visualizations guide to a "Get Started" section on the `charts` section. I believe this is more useful as it keeps all information on visualizations in one place. [Mantine also does the same thing](https://mantine.dev/charts/getting-started/).
> docs: add `ScatterPlot` documentation

- apps/docs/src/pages/charts/confusion-matrix.mdx
- packages/viz/src/ConfusionMatrix/ConfusionMatrix.tsx
- packages/viz/src/ConfusionMatrix/utils.ts
⚠️ There's a small change to one of the types used in the `ConfusionMatrix` component to change the type of a color prop from `string` to `HvColorAny`
> docs: add `ConfusionMatrix` documentation

- packages/core/src/Table/hooks/useHvRowExpand.tsx
fix checking for custom `Cell` renderer when deciding whether to "inline" the ExpandButton
> fix(table): expander column when custom Cell

- packages/core/src/ActionsGeneric/ActionsGeneric.test.tsx
- packages/core/src/Avatar/Avatar.test.tsx
- packages/core/src/AvatarGroup/AvatarGroup.test.tsx
- packages/core/src/Badge/Badge.test.tsx
- packages/core/src/BulkActions/BulkActions.test.tsx
- packages/core/src/Button/Button.test.tsx
- packages/core/src/IconButton/IconButton.test.tsx
- packages/core/src/Input/Input.test.tsx
- packages/core/src/Kpi/Kpi.test.tsx
- packages/core/src/MultiButton/MultiButton.test.tsx
- packages/core/src/Snackbar/Snackbar.test.tsx
- packages/core/src/ToggleButton/ToggleButton.test.tsx
- packages/core/src/VerticalNavigation/Actions/Actions.test.tsx
- packages/core/src/VerticalNavigation/Header/Header.test.tsx
- packages/core/src/VerticalNavigation/TreeView/TreeView.test.tsx
- packages/core/src/VerticalNavigation/VerticalNavigation.test.tsx
- packages/lab/src/Flow/Flow.test.tsx
- packages/pentaho/src/Canvas/BottomPanel/BottomPanel.test.tsx
using UI Kit icons is unnecessary to testing the components
this should also (theoretically) improve test performance and reliability
> test: remove icons dependency

- apps/docs/src/pages/components/tag.mdx
- packages/core/src/Table/stories/TableRenderers/utils.tsx
- packages/core/src/Tag/Tag.styles.tsx
- packages/core/src/Tag/Tag.tsx
- packages/core/src/Tag/stories/Tag.stories.tsx
- packages/styles/src/theme.ts
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/ds5.ts
- packages/styles/src/themes/pentahoPlus.ts
- update `HvTag` to the new Pentaho+ styles
- current P+ semantic tags need to be updated (eg. `positive_20` -> `positive`)
- support any custom color in Pentaho+ theme (similar to `HvButton`)
- recover `variant` prop from `Chip` (deprecated)
- add `size` prop
- add `showSelectIcon` to allow disabling checkbox icon (hidden in P+ theme)
> feat(Tag): update P+ styles

- apps/docs/src/pages/components/card.mdx
- apps/docs/src/pages/components/header.mdx
- apps/docs/src/pages/components/vertical-navigation.mdx
- docs/guides/styling/UtilityClasses.stories.tsx
- packages/core/src/Accordion/Accordion.tsx
- packages/core/src/Avatar/Avatar.stories.tsx
- packages/core/src/Button/Button.stories.tsx
- packages/core/src/DatePicker/DatePicker.tsx
- packages/core/src/Header/Header.stories.tsx
- packages/core/src/InlineEditor/InlineEditor.tsx
- packages/core/src/Table/TableHeader/TableHeader.tsx
- packages/core/src/TreeView/stories/VerticalNavigation.tsx
- packages/core/src/VerticalNavigation/NavigationSlider/NavigationSlider.tsx
- packages/core/src/VerticalNavigation/TreeView/TreeViewItem.tsx
- packages/core/src/VerticalNavigation/stories/Custom.tsx
- packages/core/src/utils/Callout.tsx
- packages/lab/src/Flow/Node/BaseNode.tsx
- packages/lab/src/Flow/Node/Node.tsx
- packages/lab/src/Flow/stories/BaseHook/Node.tsx
- packages/lab/src/StepNavigation/DefaultNavigation/Step/Step.tsx
- packages/lab/src/StepNavigation/SimpleNavigation/Dot/Dot.tsx
such as
- `HvBadge` `color` -> `label`
- icons `iconSize` -> `size`
- remove `overrideIconColors`
- other unnecessary `inherit`/`currentColor` overrides
> chore: cleanup unused/deprecated properties

- packages/styles/src/themes/pentahoPlus.ts
leverage new tokens instead of custom overrides
currently, only `inputColors.bg` needs to leverage the `light-dark` strategy, as other component tokens link to another available token, or don't vary (can use palette directly)
> feat(theme): update pentahoPlus theme

- apps/docs/src/components/code/Controls.tsx
- apps/docs/src/pages/components/button.mdx
- apps/docs/src/pages/components/tag.mdx
This is just a simple customization of the color picker used on the docs to allow a better experience on props of type `HvColorAny`. It will allow entering colors from the UI Kit theme (`positive`, `primary`, etc.), CSS color names (`gold`, `coral`, etc.) or HEX/RGB values.
Also updated the default button radius on the docs to be `full`
> docs: customize color picker to better represent `HvColorAny`

- packages/core/src/Avatar/Avatar.tsx
- packages/core/src/BaseCheckBox/BaseCheckBox.tsx
- packages/core/src/BaseRadio/BaseRadio.tsx
- packages/core/src/Button/Button.styles.ts
- packages/core/src/ColorPicker/SavedColors/SavedColors.tsx
- packages/core/src/DotPagination/DotPagination.styles.tsx
- packages/core/src/DotPagination/DotPagination.tsx
- packages/core/src/FileUploader/File/File.styles.tsx
- packages/core/src/FileUploader/File/File.tsx
- packages/core/src/FileUploader/FileList/FileList.styles.tsx
- packages/core/src/FileUploader/FileList/FileList.tsx
- packages/core/src/InlineEditor/InlineEditor.styles.tsx
- packages/core/src/MultiButton/MultiButton.styles.tsx
- packages/core/src/QueryBuilder/QueryBuilder.styles.tsx
- packages/core/src/Slider/SliderInput/SliderInput.styles.tsx
- packages/core/src/Slider/SliderInput/SliderInput.tsx
- packages/core/src/VerticalNavigation/TreeView/TreeViewItem.styles.tsx
- packages/lab/src/StepNavigation/DefaultNavigation/Step/Step.styles.tsx
- packages/lab/src/StepNavigation/DefaultNavigation/Step/Step.tsx
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/pentahoPlus.ts
- minor icon usage & spacing fixes found in #4487
- improve support for external icons, but ensuring `<HvButton icon>`
- follows defined (`var(--HvButton-height)`) `height`
- replace `HvSlider` dash  dot icons with inline `-`
- replace & `HvDotPagination` with styled div
- improve touch-target size (should be [24x24](https://www.levelaccess.com/blog/designer-tips-improving-button-accessibility/) or more)
> style: cleanup styles for custom icons

- packages/core/src/BaseInput/BaseInput.styles.tsx
Removes our `:-webkit-autofill` color overrides:
> style(input): remove autofill override

- packages/core/src/BaseCheckBox/BaseCheckBox.styles.ts
- packages/core/src/BaseCheckBox/CheckBoxIcon.tsx
- packages/core/src/CheckBox/CheckBox.styles.tsx
- packages/core/src/CheckBox/CheckBox.tsx
- packages/core/src/Dropdown/List/List.styles.tsx
- packages/core/src/Dropdown/List/List.tsx
- packages/core/src/Dropdown/utils.tsx
- packages/core/src/Radio/Radio.stories.tsx
- packages/core/src/Radio/Radio.styles.tsx
- packages/core/src/stories/Components.test.stories.tsx
- packages/styles/src/themes/pentahoPlus.ts
- remove dead code (`& div > svg`)
- hoist `borderRadius`
- leverage `HvWarningText`'s error border in `HvCheckbox`
- add more Radio tests & make input tests more compact
fixes:
> fix(Selection): align Checkbox/Radio styles

- .github/workflows/release.yml
- package-lock.json
Change release cron to weekly (on thursdays), so that we have more _meaningful_ [releases](https://github.com/lumada-design/hv-uikit-react/releases)
The goal is to reduce releases [like](https://github.com/lumada-design/hv-uikit-react/releases/tag/v5.91.1) [these](https://github.com/lumada-design/hv-uikit-react/releases/tag/v5.87.1) (little to no changelog), and [more](https://github.com/lumada-design/hv-uikit-react/releases/tag/v5.88.0) [like](https://github.com/lumada-design/hv-uikit-react/releases/tag/v5.89.0) [these](https://github.com/lumada-design/hv-uikit-react/releases/tag/v5.90.0)
> ci(release): change cron to weekly

- packages/core/src/Tag/stories/Tag.stories.tsx
> chore: update default color on `Tag` main story

- packages/styles/src/themes/pentahoPlus.ts
- change `HvTag` default size to `sm` in Pentaho+
- adjust `HvTagsInput` to ensure its 32px height
- update `HvTag` outline offset
> fix(Tag): change default P+ size to sm

- packages/core/src/Badge/Badge.styles.tsx
- packages/core/src/Button/Button.stories.tsx
- packages/core/src/Button/Button.styles.ts
- packages/core/src/DotPagination/DotPagination.stories.tsx
- packages/core/src/InlineEditor/InlineEditor.styles.tsx
- packages/core/src/InlineEditor/InlineEditor.tsx
- packages/core/src/QueryBuilder/RuleGroup/RuleGroup.tsx
- packages/core/src/VerticalNavigation/Actions/Action.styles.tsx
- packages/core/src/VerticalNavigation/Actions/Action.tsx
- packages/icons/src/IconBase.tsx
- packages/icons/src/IconContainer.tsx
- packages/icons/src/utils.ts
- packages/lab/src/StepNavigation/DefaultNavigation/Step/Step.styles.tsx
- packages/lab/src/StepNavigation/DefaultNavigation/Step/Step.tsx
- packages/lab/src/Wizard/WizardTitle/WizardTitle.styles.tsx
Add support for external icons (that don't have a container box) to `HvButton` (and `HvAvatar`/`HvBadge`), by removing the icon internal padding & adding the correct padding in the components:
- rename internal `HvIconContainer` container sizing CSS variable to `--icsize` to avoid collisions
- change `--icsize` in button to "auto"
- make `<HvButton icon>` follow the icon sizes
> feat(Button): support external icons

- packages/styles/src/themes/pentahoPlus.ts
Change `HvDropdownMenu` radius to use `calc(var(--HvButton-height) / 2)`. `theme.radii.full` or `50%` won't work, because the adjacent radius don't match.
If we set `border-top-left-radius: 0`, the following is happening (before):
After:
> style(DropdownMenu): borderRadius

- packages/styles/src/themes/pentahoPlus.ts
> style(Tabs): add proper background color to floating tabs

- packages/core/src/CheckBoxGroup/CheckBoxGroup.tsx
- packages/core/src/ColorPicker/ColorPicker.tsx
- packages/core/src/DatePicker/DatePicker.tsx
- packages/core/src/Dropdown/Dropdown.tsx
- packages/core/src/FileUploader/DropZone/DropZone.tsx
- packages/core/src/FilterGroup/FilterGroup.tsx
- packages/core/src/FormElement/LabelContainer.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/RadioGroup/RadioGroup.tsx
- packages/core/src/Select/Select.tsx
- packages/core/src/Slider/Slider.tsx
- packages/core/src/TagsInput/TagsInput.tsx
- packages/core/src/TextArea/TextArea.tsx
- packages/core/src/TimePicker/TimePicker.tsx
Change `HvLabelContainer` API so it's more strict, fixing inconsistencies between form components, such as
- `labelContainer` always shown (even if empty)
- `label == null` vs `label === ""` behaviour
> refactor(LabelContainer): align components' labels

- packages/core/src/Button/Button.styles.ts
changes it so `icon`-only buttons don't shrink (when there's lack of available "flex space")
> fix(Button): icon shrinking

- packages/core/src/Input/Input.stories.tsx
- packages/core/src/Input/Input.test.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/TextArea/TextArea.test.tsx
- packages/core/src/TextArea/TextArea.tsx
- add new `infoMessage` prop to `HvInput` and `HvTextArea`: an additional "label" that shows in the place of the error message when there isn't one
- switch `description` <-> `infoMessage` positions when in pentahoPlus theme
> feat(Input): add `infoMessage` prop

- packages/core/src/Card/Card.styles.tsx
- packages/core/src/Card/Card.tsx
- packages/core/src/Card/Header/Header.styles.tsx
- packages/core/src/Card/stories/KPICards.tsx
- packages/core/src/Card/stories/Variants.tsx
- packages/core/src/Skeleton/Skeleton.stories.tsx
- packages/styles/src/themes/pentahoPlus.ts
- templates/AssetInventory/CardView.tsx
- revert P+ Cards to be "KPI-like" when a semantic variant (`statusColor`) is chosen
- show top semantic border/icon & review radius
- optimize CSS vars usage, only adding overrides when non-default values are set
- improve docs samples
> fix(Card): semantic card overrides

- packages/core/src/Table/stories/TableHooks/TableHooks.mdx
I found some links in table hook links that were not working properly. I couldn't launch the storybook locally due to an error (`SB_CORE-SERVER_0005 (MainFileESMOnlyImportError): Storybook failed to load .storybook/main.ts`) to verify the fix but it should be it.
> docs: fix broken links

- .config/vite.config.ts
app-shell packages are generating `.mjs` file extensions, instead `.js`
> fix(app-shell): packages export extension

- lerna.json
- package-lock.json
bump `lerna` & remove old `npmClientArgs`, which fixes the lockfile issues we've been having (eg. #4671)
it seems to be caused by the `--legacy-peer-deps`, which we're not longer using (nor [lerna](https://github.com/lerna/lerna/releases/tag/v8.2.2)).
> chore(release): remove old args & bump lerna

- apps/docs/src/components/Examples.tsx
- apps/docs/src/components/home/CardsSection.tsx
- apps/docs/src/components/home/cards/ActiveUsers.tsx
- apps/docs/src/components/home/cards/Card.tsx
- apps/docs/src/components/home/cards/DataConfig.tsx
- apps/docs/src/components/home/cards/StorageOverview.tsx
- apps/docs/src/pages/globals.css
This adds or fixes a few small things:
- Selected tab on the docs header had the incorrect color (not visible in dark mode)
- Added an icon to the KPIs card on the examples home page
- Added a banner and a KPI to the docs home page to showcase a couple more UI Kit components
> chore: several fixes

- packages/app-shell-events/src/types/notifications.ts
- packages/app-shell-events/src/types/theming.ts
dedupe types from `app-shell-events`, `extend` from core instead (also improves docs as core's properties are documented)
this PR is primarily meant for the `app-shell-events` package to be bumped, as it didn't yet get the https://github.com/lumada-design/hv-uikit-react/pull/4678 fix
> fix(app-shell-events): inherit types & docs from core

- packages/core/src/Avatar/Avatar.styles.tsx
Fixes the container height of the `Avatar` to adapt to its content.
Before:
After:
> fix(Avatar): fix container height

- apps/docs/src/components/code/DocsProvider.tsx
- apps/docs/src/components/code/ExpandableLayout.tsx
- apps/docs/src/components/code/Playground.tsx
- apps/docs/src/components/code/PopupLayout.tsx
- apps/docs/src/components/code/ToggableLayout.tsx
- add `DocsContainer` to dedupe layout container styles & `react-live` `error` & `element` management
- fix `ExpandableLayout` container styles (border color & radius)
> docs: add DocsContainer utility

- packages/core/src/Banner/BannerContent/BannerContent.styles.tsx
- packages/core/src/utils/Callout.tsx
- packages/styles/src/themes/ds3.ts
- packages/styles/src/themes/ds5.ts
- packages/styles/src/themes/pentahoPlus.ts
fix Notifications (`HvBanner`/`HvSnackbar`) in all themes
- remove extra border in `ds3`
- align `ds5` & `pentahoPlus` borders. both use `radii.round`, except for `ds5` `HvBanner`, which has none
> fix(notifications): borderRadius

- packages/core/src/Select/Select.styles.ts
- `HvSelect` didn't have a red border when invalid.
Before:
After:
> fix(Select): invalid border color

- packages/core/src/IconContainer/IconContainer.stories.tsx
- packages/core/src/IconContainer/IconContainer.tsx
numeric `size` (eg. `size={100}`) was being ignored
> fix(IconContainer): numeric `size` being ignored

- apps/docs/src/components/Examples.tsx
- apps/docs/src/components/home/cards/DataConfig.tsx
- change home `HvBanner` for `HvBannerContent` (hide close icon that does nothing)
- fix`/examples`'s icons (`div` inside `p` validation).
- also updates icons to use Phosphor Icons
> docs: home BannerContent & examples icons

- apps/docs/src/components/color/ColorPalette.tsx
- apps/docs/src/components/color/ColorTokens.tsx
- apps/docs/src/components/color/utils.ts
- add `id`s for anchor links in color groups (eg [/color-tokens#negative](https://lumada-design.github.io/uikit-docs/master/docs/color-tokens#negative))
- `/color-palette`:
- change to a more condensed look
- `/color-tokens`:
- add `<code>` to color keys
- hide "weird"/alias token values (that don't start with `#`)
- add _hidden_ compatibility tokens (eg. `primary_20`) in non-`pentahoPlus` themes
> docs: review colors pages

- apps/docs/src/components/code/PopupLayout.tsx
- apps/docs/src/examples/inputs/TagsSuggestions.tsx
- apps/docs/src/examples/inputs/TagsSuggestionsEmpty.tsx
- apps/docs/src/pages/examples/inputs.mdx
- packages/core/src/TagsInput/TagsInput.test.tsx
- packages/core/src/TagsInput/TagsInput.tsx
- Add a start adornment to the `TagsInput` component (it will be needed in the future and we already support an end adornment
- Add a new example that illustrates how to keep the tags input empty while adding tags (based on the real use case scenario from PD)
- Small fixes to samples layout
- Revert inputs samples layout because the Examples index page counts the number of `<CodeBlock>` elements to tell the number of samples
> fix(TagsInput): add start adornment

- apps/docs/src/pages/components/avatar.mdx
- packages/core/src/Avatar/Avatar.styles.tsx
- packages/core/src/Avatar/Avatar.tsx
- packages/styles/src/themes/ds5.ts
- fix the `variant` classes (`square`, `circular`) not being applied in the appropriate element and thus not having effect when users wanted to override the styles of each specific variant.
- Update to NEXT 5.9.5 specs
> fix(Avatar): fix border radius styles

- packages/uno-preset/src/Uno.stories.tsx
- packages/uno-preset/src/rules.ts
- packages/uno-preset/src/theme.ts
workaround for `gap-xxs` being interpreted as `gap-x-xs` (same for padding/margin)
also recover uno tests (removed by mistake in #4744)
> fix(uno): spacing for xxs token

- package-lock.json
- packages/app-shell-vite-plugin/package.json
- packages/app-shell-vite-plugin/src/nodeModule.ts
- packages/app-shell-vite-plugin/src/vite-configuration-processor-plugin.ts
- packages/app-shell-vite-plugin/src/vite-plugin.ts
fix `app-shell-vite-plugin` error on `vite-plugin-static-copy` on Windows:
```
[vite-plugin-static-copy] Error: No file was found to copy on C:\...\node_modules\es-module-shims\package.jso\dist\* src.
[vite-plugin-static-copy] No items found.
```
- replace `slice` at `/` for cross-platform `path.dirname`
- simplify `resolveModule` by leveraging `path.join`:
- remove `find-up-simple` in favor of using package entrypoint + `../` (when necessary)
- merge `resolveModule` &. `getModulePath`
- bump `vite-plugin-static-copy`
> fix(app-shell-vite-plugin): cross-platform module resolution

- package-lock.json
- packages/core/package.json
- packages/core/src/SnackbarProvider/SnackbarProvider.tsx
- migrate `notistack` used in `HvSnackbarProvider` to v3
- https://notistack.com/migration (`resumeHideDuration`, `onEntering`, `onExisting` removed)
> feat(deps): bump notistack to v3

- packages/cli/src/baselines/app-shell/vite/public/locales/en/example.json
- packages/cli/src/baselines/app-shell/vite/src/pages/Example/index.tsx
- packages/cli/src/baselines/vite/public/locales/en/home.json
- packages/cli/src/baselines/vite/src/App.tsx
- packages/cli/src/baselines/vite/src/pages/Home/index.tsx
- packages/cli/src/baselines/vite/src/routes.tsx
- packages/cli/src/contents.js
- packages/cli/src/plop-templates/component.tsx.hbs
- packages/cli/src/plop-templates/locale.json.hbs
- packages/cli/src/plopfile.js
- templates/Canvas/dependencies.json
- templates/DetailsView/KPIs.tsx
- templates/KanbanBoard/dependencies.json
1. Fallback route in App Shell (`pages/Project.tsx`) had issues (see first commit)
2. Add static `Example.tsx` and `Home.tsx` pages, instead of relying on the plop script, which can easily hide potential problems (`baselines/*` is also more readable now)
3. add missing `dependencies.json` in some templates, fixing the "dependencies not found" issue
> fix(cli): add fallback `Project`/`Home` routes

- packages/config/package.json
- packages/config/tsconfig.json
- tsconfig.build.json
- add `tsconfig.json` to the `config` package - heavily inspired in our current config, which itself is inspired on [`@total-typescript/tsconfig`](https://github.com/total-typescript/tsconfig/blob/main/bundler/dom.json)
- dedupe configs
> feat(config): add `tsconfig.json` to config package

- packages/core/src/TagsInput/TagsInput.styles.tsx
- packages/core/src/themes/pentahoPlus.ts
- I fixed some styling discrepancies for the Tags Input (when besides another input, you could see the Tags Input was different):
- Border color for the Pentaho+ theme
- Disabled background and border colors for the Pentaho+ theme
- Placeholder text style
ℹ️ I think I found more stuff but I only fixed the styles: the placeholder disappears when read only or disabled is true; it looks like in Pentaho+ the description should be under the input.
> fix(TagsInput): input styles

- .github/workflows/build.yml
- packages/app-shell-vite-plugin/src/nodeModule.ts
- packages/app-shell-vite-plugin/src/vite-plugin.ts
- fix App Shell build in windows (`es-module-shims` [static copy](https://github.com/sapphi-red/vite-plugin-static-copy?tab=readme-ov-file#usage))
- enable (Nightly only) build test in Windows
> fix(AppShell): vite plugin windows build

- apps/docs/src/content/components/section.mdx
- packages/core/src/Section/Section.stories.tsx
- packages/core/src/Section/Section.styles.tsx
- packages/core/src/Section/Section.test.tsx
- packages/core/src/Section/Section.tsx
- packages/core/src/Table/TableSection/TableSection.styles.tsx
- packages/core/src/themes/pentahoPlus.ts
add opt-in `expandableHeader` prop, allowing the whole header to be clickable, to support the new Pentaho+ behaviour
implementation is a bit of a hack (hence the a11y disables) since we [can't have buttons inside buttons](https://accessibilityinsights.io/info-examples/web/nested-interactive/), the "header" is a11y-hidden, and clicking it triggers a click on the accessible expand toggle button
> feat(Section): add expandableHeader

- packages/styles/src/types.ts
- packages/styles/src/utils.ts
- remove `icons` & `base` from injected CSS vars
- use `interface` instead of `type` in theme base so they can be more easily extended
> chore(styles): remove excessive vars & use interfaces

- packages/core/src/Dialog/Content/Content.styles.tsx
- packages/core/src/Dialog/Content/Content.tsx
- packages/core/src/Dialog/Dialog.styles.tsx
- packages/core/src/Dialog/Title/Title.tsx
- packages/core/src/Dialog/stories/FormStory.tsx
- packages/core/src/Dialog/stories/MainStory.tsx
- packages/core/src/Dialog/stories/SemanticVariantsStory.tsx
- packages/core/src/Drawer/Drawer.stories.tsx
- packages/core/src/FileUploader/FileUploader.stories.tsx
- packages/core/src/QueryBuilder/ConfirmationDialog/ConfirmationDialog.tsx
- packages/core/src/themes/ds3.ts
- packages/core/src/themes/ds5.ts
- packages/core/src/themes/pentahoPlus.ts
- packages/lab/src/Wizard/WizardTitle/WizardTitle.tsx
Notable changes Dialog component in this PR:
- no more semantic bar on the top of the semantic dialogs
- use HvStatusIcon on the dialog title
- no more top border on the dialog actions bar
- updated border radius on the dialogs
- fixed border radius on the fullscreen dialog (some unwanted border radius was showing)
- changed order of buttons on sample stories to adhere to PD norms
> feat(Dialog): update Dialog according to P+ specs

- .oxlintrc.json
- apps/app/src/generator/FontFamily.tsx
- apps/docs/src/app/examples/inputs/TagsSuggestions.tsx
- apps/docs/src/app/examples/inputs/TagsSuggestionsEmpty.tsx
- apps/docs/src/app/examples/login/LoginFull.tsx
- apps/docs/src/app/examples/login/LoginShort.tsx
- apps/docs/src/components/code/utils.ts
- packages/app-shell-ui/src/components/hoc/withClickAwayListener.tsx
- packages/app-shell-ui/src/components/layout/Header/HeaderActions/InternalActions/AppSwitcherToggle/AppSwitcherToggle.tsx
- packages/app-shell-ui/src/providers/NavigationProvider.test.tsx
- packages/app-shell-ui/src/providers/NavigationProvider.tsx
- packages/config/oxlint/base.json
- packages/core/src/Dialog/Content/Content.tsx
- packages/core/src/Dialog/stories/SemanticVariantsStory.tsx
- packages/core/src/NumberInput/NumberInput.tsx
- packages/core/src/Pagination/Pagination.tsx
- change `unused-vars` to error, but relax rule a bit
- since this was only `warn`, we'd start accumulating these
- forbid root `@mui/material` imports (for bundling/dev performance reasons)
> chore(lint): error on unused vars & forbid root @mui/material import

- packages/core/src/Accordion/Accordion.test.tsx
- packages/core/src/Accordion/Accordion.tsx
- packages/core/src/TimeAgo/useTimeAgo.ts
- packages/core/src/hooks/useExpandable.ts
- remove `disableEventHandling` (make it default)
- remove problematic `useTimeAgo` seconds to milliseconds conversions
> fix(Accordion): default disableEventHandling

- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.test.tsx
- packages/core/src/Dialog/Title/Title.tsx
- packages/core/src/Dialog/stories/LongContentStory.tsx
- renders the `HvDialogTitle` icon only when a `customIcon` or a `variant` is defined
- add unit tests & Chromatic test
> fix(DialogTitle): render icon when `customIcon` or `variant` is defined

- .storybook/addons/mode-selector/ModeSelector.tsx
- .storybook/addons/mode-selector/utils.ts
- .storybook/blocks/DocsContainer.tsx
- .storybook/decorators/utils.ts
- .storybook/decorators/withThemeDecorator.decorator.tsx
- .storybook/theme/index.ts
- apps/default-app/app-shell.config.ts
- apps/default-app/src/pages/Theming/Theming.tsx
- apps/docs/src/components/Main.tsx
- apps/docs/src/components/code/DocsProvider.tsx
- apps/docs/src/content/app-shell/configuration.mdx
- apps/docs/src/content/docs/theming.mdx
- examples/uikit-vite-ts/src/Container.tsx
- packages/app-shell-shared/src/types/Config.ts
- packages/app-shell-ui/src/components/AppShellProvider/AppShellProvider.test.tsx
- packages/app-shell-ui/src/components/AppShellProvider/AppShellProvider.tsx
- packages/app-shell-ui/src/hooks/useThemeEventListener.test.tsx
- packages/core/src/providers/Provider.test.tsx
- packages/core/src/providers/Provider.tsx
- packages/core/src/providers/ThemeProvider.tsx
- packages/core/src/types/generic.ts
- packages/core/src/utils/theme.ts
- packages/internal/src/utils.ts
- packages/shared/src/context/ThemeContext.ts
- packages/styles/src/makeTheme.ts
- packages/styles/src/types.ts
- packages/styles/src/utils.ts
- packages/uno-preset/src/theme.ts
- packages/utils/src/hooks/useTheme.ts
- packages/viz/src/utils/registerTheme.ts
Change theme to allow only light/dark modes (instead of arbitrary number of color modes), easing integration with light/dark theme toggles
from
```tsx
colors: {
modes: Record<string, HvThemeColors>
}
```
to:
```tsx
colors: {
light: HvThemeColors;
dark: HvThemeColors;
}
```
> feat(theme): support only light/dark color modes

- packages/core/src/Tag/Tag.tsx
maps `HvTag`'s semantic `_20` colors to the suffix-less color in Pentaho theme, so that migration (eg. `positive_20` > `positive`) isn't required
> fix(Tag): map semantic _20 colors in Pentaho theme

- packages/core/src/themes/ds3.ts
- packages/core/src/themes/ds5.ts
- packages/core/src/themes/pentahoPlus.ts
- packages/core/src/themes/utils.ts
add type completions to `theme.components`'s props. useful to ensure there are no typos, deprecated, or removed props & classes
> chore: typings on themes' components

- packages/core/src/Input/Input.tsx
In React 19 + Next.js 15, we are facing a problem submitting a form using `HvInput` and pressing the return ` ↵` key.
```
TypeError: Cannot read properties of undefined (reading 'target')
at onInputBlurHandler (Input.js:200:1)
at InputBase.InputBase.useEffect (InputBase.js:294:9)
at Object.react_stack_bottom_frame (react-dom-client.development.js:23953:1)
at runWithFiberInDEV (react-dom-client.development.js:1519:1)
at commitHookEffectListMount (react-dom-client.development.js:11905:1)
at commitHookPassiveMountEffects (react-dom-client.development.js:12026:1)
at commitPassiveMountOnFiber (react-dom-client.development.js:13841:1)
at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:13815:1)
at commitPassiveMountOnFiber (react-dom-client.development.js:13834:1)
at …
```
> fix(input): optional chaining for input blur event

- apps/default-app/src/pages/ServicesDemo/ServicesDemo.tsx
- packages/app-shell-services/src/types/async.ts
In my previous [PR](https://github.com/lumada-design/hv-uikit-react/pull/4895) I missed the typecheck error on the actions and this PR follows to fix them.
These errors were "hidden" on the IDE by other error like explained below:
-> the default-app makes use of the **app-shell-services** package and imports it like `import { useService, useServices } from "@hitachivantara/app-shell-services";` on the ServicesDemo.tsx page.
However, because the this package doesn't have the following config `"main": "./src/index.ts",` on its package.json file, it complains with:
```
TS2307: Cannot find module @hitachivantara/app-shell-services or its corresponding type declarations.
There are types at
/.../hv-uikit-react/node_modules/@hitachivantara/app-shell-services/src/index.ts
, but this result could …
```
> fix(AppShell): address typecheck errors

- .config/vite.config.ts
- Add preserveModulesRoot: "src" to both ESM and CJS output configurations
- Fixes Vite import analysis error for @hitachivantara/uikit-react-core
- Ensures build output structure matches package.json exports paths
> chore: add preserveModulesRoot to fix package exports resolution

- packages/core/src/StatusIcon/StatusIcon.tsx
- Change icon imports from @phosphor-icons/react/IconName to @phosphor-icons/react/dist/csr/IconName
- Improves build consistency and explicit dependency resolution
> refactor(StatusIcon): update Phosphor imports to use explicit CSR paths

- apps/default-app/vite.config.ts
- apps/docs/src/content/app-shell/configuration.mdx
- packages/app-shell-vite-plugin/src/vite-plugin.ts
In a [previous PR](https://github.com/lumada-design/hv-uikit-react/pull/4930), a breaking change was introduced and, to not make it disruptive nor provoke a major release (since we are anticipating more features around the `apps` property), this PR introduces a feature flag around the functionality, keeping the previous behavior while enabling the new.
> feat(AppShell): add vite plugin parameter to control importmap normalization [PPUC-199]
