packages/core/src/AssetInventory/AssetInventory.js, packages/core/src/AssetInventory/CardView/CardView.js
Fix for issue [#2652](url=https://github.com/lumada-design/hv-uikit-react/issues/2652)
=> fix(AssetInventory): fixed undefined emptyComponent on the CardView causing app crash

packages/core/src/GlobalActions/styles.js
style(global-actions): added new blur effect on backdrop
=> style: added new blur effect on backdrop

packages/core/src/VerticalNavigation/styles.js
style(VerticalNavigation): added a shadow outside container
=> style(VerticalNavigation): added a shadow outside container

packages/lab/src/DotPagination/DotPagination.d.ts, packages/lab/src/DotPagination/DotPagination.js, packages/lab/src/DotPagination/stories/DotPagination.stories.js, packages/lab/src/DotPagination/tests/DotPagination.test.js, packages/lab/src/DotPagination/tests/__snapshots__/DotPagination.test.js.snap
=> fix(dotPagination): added missing typescript definition and description.

.github/ISSUE_TEMPLATE/2.feature.yml
=> chore(template): correct feature.yml syntax error

packages/lab/src/Table/Table.d.ts, packages/lab/src/Table/Table.js, packages/lab/src/Table/TableBody/TableBody.js, packages/lab/src/Table/TableBody/styles.js, packages/lab/src/Table/TableCell/TableCell.d.ts, packages/lab/src/Table/TableCell/TableCell.js, packages/lab/src/Table/TableCell/styles.js, packages/lab/src/Table/TableHeader/TableHeader.d.ts, packages/lab/src/Table/TableHeader/TableHeader.js, packages/lab/src/Table/TableHeader/styles.js, packages/lab/src/Table/TableRow/TableRow.d.ts, packages/lab/src/Table/TableRow/TableRow.js, packages/lab/src/Table/TableRow/styles.js, packages/lab/src/Table/stories/Table.stories.js, packages/lab/src/Table/styles.js, packages/lab/src/Table/tests/Table.test.js, packages/lab/src/Table/tests/__snapshots__/Table.test.js.snap, packages/lab/src/Table/tests/table.spec.ts
This is branch is not meant to be merged, it is only to demonstrate the application of box shadows acting as border styles in the table.
=> feat(Table): added table list row variant to table

packages/lab/package-lock.json, packages/lab/package.json, packages/lab/src/Slider/tests/__snapshots__/slider.test.js.snap
=> fix(Slider): update rc-tooltip version. #2807

packages/core/src/Table/Table.d.ts, packages/core/src/Table/Table.js, packages/lab/src/Table/TableBody/TableBody.d.ts
=> fix(table): fixed HvTable and HvTableBody type definition properties

packages/core/src/BaseInput/styles.js, packages/core/src/BaseInput/tests/__snapshots__/baseinput.test.js.snap, packages/core/src/Forms/Suggestions/tests/__snapshots__/Suggestions.test.js.snap, packages/core/src/Input/tests/__snapshots__/input.test.js.snap
=> fix(baseInput): override default dotted border bottom when disabled.

packages/viz/src/Barchart/Barchart.js
=> fix(barchart): fixed classes prop declaration

packages/core/src/components/Loading/Loading.Styles.tsx
replaced possibly unsafe `nth-child` pseudo class with `nth-of-type`.
=> fix(Loading): fix css nth-child pseudo class

packages/core/src/components/ActionBar/ActionBar.tsx, packages/core/src/components/Badge/Badge.tsx, packages/core/src/components/Box/Box.tsx, packages/core/src/components/EmptyState/EmptyState.tsx, packages/core/src/components/Footer/Footer.tsx, packages/core/src/components/Grid/Grid.tsx, packages/core/src/components/Header/Actions/Actions.tsx, packages/core/src/components/Header/Brand/Brand.tsx, packages/core/src/components/Header/Header.tsx, packages/core/src/components/Header/Navigation/MenuBar/MenuBar.tsx, packages/core/src/components/Header/Navigation/MenuItem/MenuItem.tsx, packages/core/src/components/Header/Navigation/Navigation.tsx, packages/core/src/components/Link/Link.tsx, packages/core/src/components/Loading/Loading.tsx, packages/core/src/components/MultiButton/MultiButton.tsx, packages/core/src/components/ProgressBar/ProgressBar.tsx, packages/core/src/components/ToggleButton/ToggleButton.tsx, packages/core/src/components/Typography/Typography.tsx, packages/core/src/types/index.ts
- Change components' props interfaces to types
- Change `BaseProps` name to `HvBaseProps`
=> fix: base props type

packages/core/src/components/Tabs/Tabs.stories.tsx, packages/core/src/components/Tabs/Tabs.styles.tsx, packages/core/src/components/Tabs/Tabs.test.tsx, packages/core/src/components/Tabs/Tabs.tsx, packages/core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, packages/core/src/components/Tabs/index.ts, packages/core/src/components/index.ts
- I did not add [this top border](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/Tabs/styles.js#L19) since it didn't seem to be applied in DS3 and `atmo6` is not a valid color.
=> feat(Tabs): add Tabs component

packages/core/src/components/Forms/Adornment/Adornment.test.tsx, packages/core/src/components/Forms/InfoMessage/InfoMessage.test.tsx, packages/core/src/components/Forms/Label/Label.test.tsx, packages/core/src/components/Forms/Suggestions/Suggestions.stories.tsx, packages/core/src/components/Forms/Suggestions/Suggestions.styles.tsx, packages/core/src/components/Forms/Suggestions/Suggestions.test.tsx, packages/core/src/components/Forms/Suggestions/Suggestions.tsx, packages/core/src/components/Forms/Suggestions/__snapshots__/Suggestions.test.tsx.snap, packages/core/src/components/Forms/Suggestions/index.ts, packages/core/src/components/Forms/WarningText/WarningText.test.tsx, packages/core/src/components/ListContainer/ListItem/ListItem.tsx, packages/core/src/components/index.ts
All the Storybook stories for the Forms components will be done when their dependencies are completed so none were included here.
There are a few comments that remain in the code that will be removed when the stories are done.
=> feat(Forms): add Suggestions component

packages/core/src/components/ActionsGeneric/ActionsGeneric.styles.tsx, packages/core/src/components/ActionsGeneric/ActionsGeneric.test.tsx, packages/core/src/components/ActionsGeneric/ActionsGeneric.tsx, packages/core/src/components/ActionsGeneric/__snapshots__/ActionsGeneric.test.tsx.snap, packages/core/src/components/ActionsGeneric/actionsGenericClasses.ts, packages/core/src/components/ActionsGeneric/index.ts, packages/core/src/components/index.ts
This includes no Storybook stories because it's more of an internal component.
=> feat(ActionsGeneric): add ActionsGeneric component

app/src/components/Cards/Cards.tsx, packages/core/src/components/ActionsGeneric/ActionsGeneric.tsx, packages/core/src/components/ActionsGeneric/__snapshots__/ActionsGeneric.test.tsx.snap, packages/core/src/components/Card/Card.stories.tsx, packages/core/src/components/Card/Card.styles.tsx, packages/core/src/components/Card/Card.tsx, packages/core/src/components/Card/Media/Media.tsx, packages/core/src/components/Kpi/Kpi.stories.tsx, packages/core/src/components/Stack/Stack.stories.tsx
Besides adding the missing stories, I changed the `bgColor` prop on the `Card` component to `bgcolor` to maintain compability with v4.
=> chore: add Card stories

packages/lab/src/VerticalNavigation/VerticalNavigation.js, packages/lab/src/VerticalNavigation/stories/VerticalNavigation.stories.js, packages/lab/src/VerticalNavigation/stories/multiLevelNavigationData.js, packages/lab/src/VerticalNavigation/styles.js, packages/lab/src/VerticalNavigation/tests/VerticalNavigation.test.js, packages/lab/src/VerticalNavigation/tests/__snapshots__/VerticalNavigation.test.js.snap, packages/lab/src/VerticalNavigation/utils.js
- Collapsed mode will only display top level items
- Switched collapse / expand button to the top
=> feat(VerticalNavigation): fixed collapsed panel with sub menu entries

packages/core/src/components/ActionsGeneric/__snapshots__/ActionsGeneric.test.tsx.snap, packages/core/src/components/Banner/__snapshots__/Banner.test.tsx.snap, packages/core/src/components/BulkActions/BulkActions.test.tsx, packages/core/src/components/BulkActions/__snapshots__/BulkActions.test.tsx.snap, packages/core/src/components/Button/Button.stories.tsx, packages/core/src/components/Button/Button.styles.ts, packages/core/src/components/Button/Button.tsx, packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/core/src/components/DropDownMenu/__snapshots__/DropDownMenu.test.tsx.snap, packages/core/src/components/FileUploader/File/__snapshots__/File.test.tsx.snap, packages/core/src/components/FileUploader/FileList/__snapshots__/FileList.test.tsx.snap, packages/core/src/components/FileUploader/__snapshots__/FileUploader.test.tsx.snap, packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap, packages/core/src/components/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap, packages/styles/src/theme.ts, packages/styles/src/themes/ds3.ts, packages/styles/src/themes/ds5.ts, packages/styles/src/tokens/typography.ts, packages/styles/src/types.ts
- reviewed the typography tokens and converted them to `px` units
- removed default button size
=> fix: review Button component. #HVUIKIT-6598

packages/core/src/components/AppSwitcher/Action/Action.tsx, packages/core/src/components/Card/Card.stories.tsx, packages/core/src/components/Card/Card.test.tsx, packages/core/src/components/Forms/Label/Label.tsx, packages/core/src/components/Header/Header.stories.tsx, packages/core/src/components/Header/Navigation/MenuItem/MenuItem.tsx, packages/core/src/components/Header/Navigation/utils/FocusContext.tsx, packages/core/src/components/ListContainer/ListContainer.stories.tsx, packages/core/src/components/Table/stories/TableHooks.stories.tsx, packages/core/src/components/Table/stories/TableRenderers.stories.tsx, packages/core/src/components/Tag/Tag.tsx, packages/core/src/components/ToggleButton/ToggleButton.stories.tsx, packages/core/src/components/ToggleButton/ToggleButton.tsx, packages/core/src/components/Typography/Typography.tsx
Left just a few `@ts-ignore` on a couple of stories as they're not really relevant to our code base.
=> chore: remove @ts-ignore. #HVUIKIT-6606

packages/core/src/components/BreadCrumb/Page/Page.tsx, packages/core/src/components/BreadCrumb/__snapshots__/BreadCrumb.test.tsx.snap, packages/core/src/components/Typography/Typography.tsx, packages/core/src/components/Typography/utils.ts
- improved typings of the `Typography` component
- removed unused code
=> chore: improve Typography typings

app/src/customTheme.ts, docs/theme/Colors/Colors.tsx, packages/core/src/components/ActionsGeneric/__snapshots__/ActionsGeneric.test.tsx.snap, packages/core/src/components/Banner/__snapshots__/Banner.test.tsx.snap, packages/core/src/components/BulkActions/__snapshots__/BulkActions.test.tsx.snap, packages/core/src/components/Button/Button.tsx, packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/core/src/components/Button/buttonClasses.ts, packages/core/src/components/Controls/__snapshots__/Controls.test.tsx.snap, packages/core/src/components/DropDownMenu/__snapshots__/DropDownMenu.test.tsx.snap, packages/core/src/components/FileUploader/File/__snapshots__/File.test.tsx.snap, packages/core/src/components/FileUploader/FileList/__snapshots__/FileList.test.tsx.snap, packages/core/src/components/FileUploader/__snapshots__/FileUploader.test.tsx.snap, packages/core/src/components/Header/Actions/Actions.styles.tsx, packages/core/src/components/Header/Header.styles.tsx, packages/core/src/components/Header/Navigation/MenuBar/MenuBar.styles.tsx, packages/core/src/components/Header/Navigation/MenuItem/MenuItem.styles.tsx, packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap, packages/core/src/components/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap, packages/styles/src/theme.ts, packages/styles/src/themes/ds3.ts, packages/styles/src/themes/ds5.ts, packages/styles/src/types.ts
- added more styling customization options to the `Header` component;
- also added the `root` class to the `Button` component;
- minor update to the `Colors` documentation page;
=> chore: add more styling capabilities to the Header component

app/src/generator/Colors/Colors.tsx, packages/core/src/components/BreadCrumb/Page/Page.styles.tsx, packages/core/src/components/BreadCrumb/__snapshots__/BreadCrumb.test.tsx.snap
- removed fixed color on the BreadCrumb (should use the Typography variant color instead)
=> fix(BreadCrumb): remove color

packages/core/src/components/Dialog/Dialog.styles.tsx
According to the specs:
https://designsystem.hitachivantara.com/6c705d900/p/142b46-dialog/b/732fc8
we should have a min-width of 4/12 columns and max-width of 10/12 columns.
=> fix(Dialog): fix the width of the Dialog component

packages/core/src/components/Controls/Controls.stories.tsx, packages/core/src/components/Controls/RightControl/RightControl.tsx, packages/core/src/components/Controls/__snapshots__/Controls.test.tsx.snap
- The controls component was fixed: the right control was not rendering its children.
- Missing sliders added to the controls stories.
=> fix: missing children in right control

packages/core/src/components/VerticalNavigation/Actions/Action.styles.tsx, packages/core/src/components/VerticalNavigation/Actions/__snapshots__/Actions.test.tsx.snap, packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.styles.tsx, packages/core/src/components/VerticalNavigation/TreeView/__snapshots__/TreeView.test.tsx.snap, packages/core/src/components/VerticalNavigation/__snapshots__/VerticalNavigation.test.tsx.snap
- Since updating the `primary_20` color, the hover on the vertical navigation was not working as expected. This was fixed.
=> fix: vertical navigation hover color

package-lock.json, package.json, packages/core/package.json, packages/core/src/components/Forms/Suggestions/Suggestions.styles.tsx, packages/lab/package.json
Was trying out https://github.com/lumada-design/hv-uikit-cli. It's breaking OOTB because of the recent MUI bump. This fixes it
- Bumps`@mui/material` peer to ensure latest `@mui/base`
- Fix `@mui/base` import name
=> fix: `@mui/base` import breaking change

.config/test.setup.ts, packages/core/src/components/BreadCrumb/BreadCrumb.test.tsx, packages/core/src/components/OverflowTooltip/OverflowTooltip.test.tsx, packages/core/src/components/Table/Table.test.tsx
- add some missing jsdom mocks
- [matchMedia](https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)
- [ResizeObserver](https://github.com/jsdom/jsdom/issues/3368)
- remove [unnecessary cleanup ](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-cleanup)
=> test: improve test setup

packages/core/src/components/VerticalNavigation/Header/Header.tsx, packages/core/src/components/VerticalNavigation/VerticalNavigation.stories.tsx
Fix ESLint errors from recently merged code
=> chore: fix failing `eslint` rules

packages/core/src/components/Dialog/Dialog.stories.tsx, packages/core/src/components/Dialog/Dialog.tsx
- allow native `autoFocus` to be used
- don't implicitly focus first element with outline
- improve docs (add form sample)
=> feat(dialog): improve focus logic

packages/core/src/components/BulkActions/__snapshots__/BulkActions.test.tsx.snap, packages/core/src/components/DropDownMenu/DropDownMenu.styles.tsx, packages/core/src/components/DropDownMenu/DropDownMenu.tsx, packages/core/src/components/DropDownMenu/__snapshots__/DropDownMenu.test.tsx.snap, packages/core/src/components/DropDownMenu/dropDownMenuClasses.ts, packages/core/src/components/Table/TableCell/TableCell.styles.tsx
- Fixes issue: https://github.com/lumada-design/hv-uikit-react/issues/3375
=> fix(Table): no scrollbar added when column has actions

packages/core/src/components/BaseInput/BaseInput.tsx, packages/core/src/components/Calendar/CalendarHeader/CalendarHeader.styles.tsx, packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap, packages/core/src/components/Pagination/Pagination.styles.tsx, packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
dedupe code in other components that need it
=> refactor(Input): remove arrows in numeric inputs

packages/core/src/components/BreadCrumb/BreadCrumb.stories.tsx, packages/core/src/components/BreadCrumb/BreadCrumb.tsx, packages/core/src/components/BreadCrumb/Page/Page.styles.tsx, packages/core/src/components/BreadCrumb/Page/Page.tsx, packages/core/src/components/BreadCrumb/__snapshots__/BreadCrumb.test.tsx.snap
- allow custom `component` to be passed
- add sample for it
=> fix(BreadCrumb): allow custom component

packages/core/src/components/Header/Navigation/MenuItem/MenuItem.styles.tsx, packages/core/src/components/Table/TableCell/TableCell.styles.tsx, packages/core/src/components/Table/TableRow/TableRow.styles.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
to fix the emotion warning:
```
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
```
=> chore(styles): replace `:first-child` with `:first-of-type`

app/src/components/common/FontSize/FontSize.tsx, app/src/generator/Colors/Colors.tsx, app/src/generator/Content.tsx, app/src/generator/FontFamily/FontFamily.tsx, app/src/generator/FontSizes/FontSizes.tsx, app/src/generator/Radii/Radii.tsx, app/src/generator/Sidebar/Sidebar.tsx, app/src/generator/Sizes/Sizes.tsx, app/src/generator/Spacing/Spacing.tsx, app/src/generator/Typography/Typography.tsx, app/src/generator/Zindices/Zindices.tsx
incorrectly using the `createTheme` to update the custom theme was leading to some inconsistent behavior.
=> chore: fix incorrect use of `createTheme`

packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.styles.tsx, packages/core/src/components/VerticalNavigation/TreeView/TreeViewItem.tsx, packages/core/src/components/VerticalNavigation/TreeView/__snapshots__/TreeView.test.tsx.snap, packages/core/src/components/VerticalNavigation/__snapshots__/VerticalNavigation.test.tsx.snap
=> feat(VerticalNavigation): move chevrons to the right

app/src/components/common/Header/Header.tsx, app/src/lib/navigation.ts, app/src/lib/routes.tsx, app/src/pages/Instructions/Step.tsx
- also replaced the path `templates` with `preview` as that's what we're using
=> chore: update theme creator's initial page

app/src/generator/Sidebar/Sidebar.tsx
- prevent tabs from scrolling along with their contents
=> chore: fix tabs on the Theme Creator

packages/core/src/components/Header/Navigation/MenuItem/MenuItem.styles.tsx, packages/core/src/components/Header/Navigation/MenuItem/MenuItem.tsx, packages/styles/src/theme.ts, packages/styles/src/themes/ds3.ts, packages/styles/src/themes/ds5.ts, packages/styles/src/types.ts
=> chore: enable deeper customization of Header item styles

.github/actions/build-artifacts/action.yml, .github/workflows/documentation.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/static-checks.yml, .github/workflows/tests-applitools.yml, .github/workflows/tests-pa11y.yml
- add `retention-days` to save storage usage
- remove `branches` from `workflow_dispatch`, it's not part of the syntax
=> ci(actions): add `retention-days` & fix `workflow_dispatch`

app/src/assets/HitachiLogo.tsx, app/src/components/common/FontSize/FontSize.tsx, app/src/components/common/ThemeSwitcher/ThemeSwitcher.tsx, app/src/components/components/BulkActions/BulkActions.tsx, app/src/components/components/ButtonConfigurator/ButtonConfigurator.tsx, app/src/components/components/Calendar/Calendar.tsx, app/src/components/components/FileUploader/FileUploaded.tsx, app/src/components/components/Input/Input.tsx, app/src/components/components/TagsInput/TagsInput.tsx, app/src/components/detailsView/Kpi1/Kpi1.tsx, app/src/components/detailsView/Kpi2/Kpi2.tsx, app/src/components/detailsView/Kpi3/Kpi3.tsx, app/src/generator/CodeEditor/CodeEditor.tsx, app/src/generator/Colors/Colors.tsx, app/src/generator/Colors/utils.ts, app/src/generator/FontFamily/FontFamily.tsx, app/src/generator/FontSizes/FontSizes.tsx, app/src/generator/GeneratorContext.tsx, app/src/generator/Radii/Radii.tsx, app/src/generator/Sidebar/Sidebar.tsx, app/src/generator/Sizes/Sizes.tsx, app/src/generator/Spacing/Spacing.tsx, app/src/generator/Typography/Typography.tsx, app/src/generator/Zindices/Zindices.tsx, app/src/generator/utils.ts, app/src/lib/utils/form.ts, app/src/pages/Form/Form.tsx, app/src/pages/Instructions/Step.tsx, app/src/pages/Instructions/Tutorial.tsx, app/tsconfig.json
- As discussed I added the type references for the app to fix errors like this:
- I also fixed type errors
=> chore: app type references added and type errors fixed

packages/core/src/components/DropDownMenu/DropDownMenu.stories.tsx
- Fixes the following issue (the dropdown menu was not opening for the main story):
https://github.com/lumada-design/hv-uikit-react/assets/43220251/360202a8-e168-48bc-99e9-3c9cc0c78175
=> docs: fix dropdown menu not opening in main story

packages/core/src/components/index.ts
- Added Drawer export in components `index.ts`
Let me know if I've missed something.
=> fix: export HvDrawer

.storybook/addons/mode-selector/ModeSelector.tsx, .storybook/addons/theme-selector/ThemeSelector.tsx, .storybook/addons/theme-selector/constants.ts, .storybook/addons/theme-selector/utils.ts, .storybook/decorators/withThemeProvider.tsx, packages/core/src/components/ActionsGeneric/ActionsGeneric.styles.tsx
As discussed, the stories theme is updated when the docs color mode is changed.
=> docs: update stories theme when updating docs color mode

packages/core/src/components/Accordion/Accordion.stories.tsx, packages/core/src/components/Badge/Badge.stories.tsx, packages/core/src/components/Banner/Banner.stories.tsx, packages/core/src/components/Card/Card.stories.tsx, packages/core/src/components/CheckBox/CheckBox.stories.tsx, packages/core/src/components/CheckBoxGroup/CheckBoxGroup.stories.tsx, packages/core/src/components/ColorPicker/ColorPicker.stories.tsx, packages/core/src/components/DropDownMenu/DropDownMenu.stories.tsx, packages/core/src/components/EmptyState/EmptyState.stories.tsx, packages/core/src/components/FileUploader/FileUploader.stories.tsx, packages/core/src/components/FilterGroup/FilterGroup.stories.tsx, packages/core/src/components/Input/Input.stories.tsx, packages/core/src/components/ProgressBar/ProgressBar.stories.tsx, packages/core/src/components/Radio/Radio.stories.tsx, packages/core/src/components/RadioGroup/RadioGroup.stories.tsx, packages/core/src/components/ScrollTo/Horizontal/ScrollToHorizontal.stories.tsx, packages/core/src/components/SelectionList/SelectionList.stories.tsx, packages/core/src/components/Snackbar/SnackbarProvider.stories.tsx, packages/core/src/components/Stack/Stack.stories.tsx, packages/core/src/components/Switch/Switch.stories.tsx, packages/core/src/components/Tabs/Tabs.stories.tsx, packages/core/src/components/Tag/Tag.stories.tsx, packages/core/src/components/TagsInput/TagsInput.stories.tsx, packages/core/src/components/TextArea/TextArea.stories.tsx, packages/core/src/components/TimePicker/TimePicker.stories.tsx, packages/core/src/components/ToggleButton/ToggleButton.stories.tsx, packages/core/src/components/Tooltip/Tooltip.stories.tsx, packages/lab/src/components/Wizard/Wizard.stories.tsx
Consolidation of the Storybook stories. This involved mainly:
- Merge variants into a single story where applicable
- Exclude irrelevant stories from Applitools
Reduced tests from 257 to 217 (~16%)
=> docs: review stories

packages/core/src/providers/Provider.tsx
This last change makes the UI Kit work on Next.js 🎉🥳
=> fix: protected the use of document on provider on SSR

packages/core/src/components/Button/Button.stories.tsx, packages/core/src/components/Button/Button.styles.ts, packages/core/src/components/Button/Button.tsx
icon color is always the same as text color
=> fix(button): primary icon default color

packages/core/src/components/GlobalActions/GlobalActions.styles.tsx, packages/styles/src/theme.ts, packages/styles/src/themes/ds3.ts, packages/styles/src/themes/ds5.ts, packages/styles/src/types.ts
- I didn't make the port to `classes` right now as this is intended to unlock work for the DA project asap.
=> fix(GlobalActions): align with DS5 specs

package-lock.json, package.json, packages/core/package.json, packages/core/src/components/DatePicker/DatePicker.stories.tsx, packages/core/src/components/Dialog/Dialog.stories.tsx, packages/core/src/components/Drawer/Drawer.stories.tsx, packages/core/src/components/FilterGroup/FilterGroup.stories.tsx, packages/core/src/components/TimePicker/TimePicker.stories.tsx, packages/lab/package.json, packages/lab/src/components/Wizard/Wizard.stories.tsx
- Interactions were added to some components in order for applitools to test meaningful baselines: wizard, dialog, drawer, filter group, time picker and date picker.
=> test: add applitools interactions

packages/core/src/components/AppSwitcher/Action/Action.tsx, packages/core/src/components/Button/Button.stories.tsx, packages/core/src/components/TimeAgo/TimeAgo.tsx, packages/core/src/components/Typography/Typography.stories.tsx, packages/core/src/components/Typography/Typography.test.tsx, packages/core/src/components/Typography/Typography.tsx
- Polymorphic pops added for the `Typography` component. I also needed to add polymorphic pops to the `TimeAgo` component.
=> fix: polymorphic props for Typography and TimeAgo

packages/core/src/components/BulkActions/BulkActions.styles.tsx, packages/core/src/components/BulkActions/BulkActions.tsx, packages/styles/src/theme.ts, packages/styles/src/themes/ds3.ts, packages/styles/src/themes/ds5.ts, packages/styles/src/types.ts
The dark mode styles were updated to this specification that I got from DS
=> feat(bulkActions): update do ds5 styles

packages/core/src/components/ToggleButton/ToggleButton.stories.tsx
- Pa11y issues fixed for the toggle button:
=> docs(ToggleButton): fix pa11y issues

packages/core/src/components/FilterGroup/FilterGroup.stories.tsx
Accessibility issues fixed on the filter group stories.
=> docs(FilterGroup): fix a11y issues

.eslintrc, .storybook/addons/theme-selector/ThemeSelector.tsx, .storybook/blocks/DocsContainer.tsx, .storybook/main.ts, .storybook/preview.ts, .storybook/theme/index.ts, .storybook/theme/styles/docs.ts, .storybook/theme/styles/manager.ts, docs/foundation/Icons/Icons.stories.mdx, docs/guides/styling/Customization.stories.mdx, docs/guides/theming/Theming.stories.mdx, docs/guides/theming/WhiteLabeling.stories.mdx, docs/overview/changelogs/Core.stories.mdx, docs/overview/changelogs/Icons.stories.mdx, docs/overview/changelogs/Shared.stories.mdx, docs/overview/changelogs/Styles.stories.mdx, docs/overview/status/ProjectStatus.stories.mdx, docs/overview/welcome/Center/Center.tsx, docs/overview/welcome/Footer/Footer.tsx, docs/overview/welcome/Header/Header.tsx, packages/core/src/components/ColorPicker/ColorPicker.stories.tsx, packages/core/src/components/Snackbar/SnackbarProvider.stories.mdx, packages/viz/src/components/BarChart/stories/BarChart.stories.tsx, packages/viz/src/components/BaseChart/stories/utils.tsx, packages/viz/src/components/ConfusionMatrix/ConfusionMatrix.stories.tsx, packages/viz/src/components/DonutChart/DonutChart.stories.tsx, packages/viz/src/components/LineChart/LineChart.stories.tsx
_cherry-pick_ some stuff on https://github.com/lumada-design/hv-uikit-react/pull/3628 to make upgrading simpler
- prepare for storybook@7 upgrade
- migrate stuff that breaks in v7
- leverage SB theming capabilities
=> docs(storybook): theming & sample improvements

packages/core/src/components/Carousel/Carousel.stories.tsx
I decided to remove the image that was leading to CORS problems in the carousel stories since this was breaking applitools.
=> docs(Carousel): image with cors problem removed

packages/core/src/components/Controls/Controls.stories.tsx
- Remaining a11y issues for the controls component fixed
=> docs(Controls): fix a11y issues

docs/foundation/colors/Colors.tsx, docs/guides/theming/ThemeContext.tsx, docs/guides/theming/Theming.stories.mdx, docs/overview/migration/MigrationV5.stories.mdx, packages/core/src/components/ActionsGeneric/ActionsGeneric.tsx, packages/core/src/components/BulkActions/BulkActions.tsx, packages/core/src/components/Dialog/Dialog.tsx, packages/core/src/components/Drawer/Drawer.tsx, packages/core/src/components/ScrollTo/Horizontal/ScrollToHorizontal.tsx, packages/core/src/components/ScrollTo/Vertical/ScrollToVertical.tsx, packages/core/src/components/Table/TableCell/TableCell.tsx, packages/core/src/components/Table/TableHeader/TableHeader.tsx, packages/core/src/components/Table/TableRow/TableRow.tsx, packages/core/src/components/Table/stories/TableSamples/LoadingContainer.tsx, packages/core/src/components/Tag/Tag.tsx, packages/core/src/hooks/useTheme.ts, packages/viz/src/components/ConfusionMatrix/utils.ts, packages/viz/src/hooks/useXAxis.tsx, packages/viz/src/hooks/useYAxis.tsx
making it simpler to get colors from the `activeTheme` & `selectedMode`'s palette
=> feat(theme): add `colors` helper to `useTheme`

packages/core/src/components/DatePicker/DatePicker.stories.tsx, packages/core/src/components/GlobalActions/GlobalActions.stories.tsx, packages/core/src/components/Input/Input.stories.tsx, packages/core/src/components/Kpi/Kpi.stories.tsx, packages/core/src/components/Stack/Stack.stories.tsx, packages/core/src/components/Tag/Tag.stories.tsx
- consolidate `HvInput` samples
- move sample container styles to decorators
- fix `HvDatePicker` missing decorators
- change `styled` samples to use `css` instead
- rename `HvDatePicker` morbid sample 💀 
- update deprecated input controls API
=> docs: Input, DatePicker, GlobalActions review

.github/workflows/pr.yml
- Change Deployment & Applitools jobs to not wait for "Static Tests", cutting workflow time in ~10min
=> ci(pr): run tests/deploy/applitools in parallel

packages/core/src/components/BaseInput/BaseInput.styles.tsx, packages/core/src/components/GlobalActions/GlobalActions.styles.tsx, packages/core/src/components/GlobalActions/GlobalActions.tsx, packages/styles/src/themes/ds3.ts
- fix(Input): disabled text style
- fix(GlobalActions): padding alignment
=> fix: Input & GlobalActions styles

packages/core/src/components/Slider/Slider.styles.tsx, packages/core/src/components/Slider/Slider.tsx, packages/core/src/components/Slider/base.ts, packages/core/src/components/Slider/utils.ts
=> fix(Slider): styles prefix

packages/core/src/components/BaseDropdown/BaseDropdown.tsx, packages/core/src/components/Calendar/Calendar.styles.tsx, packages/core/src/components/DatePicker/DatePicker.stories.tsx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/core/src/utils/useSavedState.ts
- replace `nth-child` with `nth-of-type` (unsafe in SSR)
- simplify typings
- simplify colors/remove unused `color`
=> chore(DatePicker): minor improvements

packages/core/src/components/BaseCheckBox/BaseCheckBox.tsx, packages/core/src/components/BaseDropdown/BaseDropdown.tsx, packages/core/src/components/BaseRadio/BaseRadio.tsx, packages/core/src/components/BaseSwitch/BaseSwitch.tsx, packages/core/src/components/CheckBox/CheckBox.tsx, packages/core/src/components/CheckBoxGroup/CheckBoxGroup.tsx, packages/core/src/components/ColorPicker/ColorPicker.tsx, packages/core/src/components/DatePicker/DatePicker.stories.tsx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/core/src/components/Dropdown/Dropdown.tsx, packages/core/src/components/FilterGroup/FilterContent/FilterContent.tsx, packages/core/src/components/FilterGroup/FilterGroup.tsx, packages/core/src/components/List/List.tsx, packages/core/src/components/ListContainer/ListContainer.tsx, packages/core/src/components/Radio/Radio.tsx, packages/core/src/components/RadioGroup/RadioGroup.tsx, packages/core/src/components/SelectionList/SelectionList.tsx, packages/core/src/components/Slider/Slider.tsx, packages/core/src/components/Switch/Switch.tsx, packages/core/src/components/TagsInput/TagsInput.tsx, packages/core/src/components/TimePicker/TimePicker.tsx
Fixes: https://github.com/lumada-design/hv-uikit-react/issues/3717
`forwardRef` was added to all form elements:
- Checkbox
- Checkbox group
- Date picker
- Dropdown
- Input (already had `forwardRef`)
- Radio
- Radio group
- Slider
- Switch
- Tags input
- Text area
- Time picker
- Color picker
- Filter group
- Selection list
Base components were also updated:
- Base checkbox
- Base dropdown
- Base radio
- Base switch
=> fix: forwardRef added to form elements

packages/core/src/components/InlineEditor/InlineEditor.stories.tsx, packages/core/src/components/InlineEditor/InlineEditor.styles.tsx, packages/core/src/components/InlineEditor/InlineEditor.tsx, packages/styles/src/themes/ds3.ts
- Default background color updated to `atmo1`
- Disabled state added
=> feat(InlineEditor): align with DS 5.7

packages/core/src/components/BreadCrumb/BreadCrumb.tsx, packages/core/src/components/BreadCrumb/Page/Page.styles.tsx, packages/core/src/components/BreadCrumb/Page/Page.tsx, packages/styles/src/themes/ds3.ts
- Background color updated to `primary_20`
=> feat(BreadCrumb): align with DS 5.7

packages/core/src/components/BaseDropdown/BaseDropdown.styles.tsx, packages/core/src/components/Pagination/Pagination.styles.tsx, packages/core/src/components/Pagination/Pagination.tsx, packages/styles/src/themes/ds3.ts
- Included a commit for the `BaseDropdown` styles here as it's used in the `Pagination` component. It should help with other stories
=> feat(Pagination): align with DS 5.7

app/src/App.tsx, app/src/lib/routes.tsx, app/src/main.tsx, app/src/pages/layout.tsx, app/vite.config.js
Bump to React Router data router: https://reactrouter.com/en/main/routers/create-browser-router#createbrowserrouter
> This is the recommended router for all React Router web projects. It uses the [DOM History API](https://developer.mozilla.org/en-US/docs/Web/API/History) to update the URL and manage the history stack. It also enables the v6.4 data APIs like [loaders](https://reactrouter.com/en/main/route/loader), [actions](https://reactrouter.com/en/main/route/action), [fetchers](https://reactrouter.com/en/main/hooks/use-fetcher) and more.
=> chore(app): upgrade to data router

packages/core/src/components/Table/TableCell/TableCell.tsx, packages/core/src/components/Table/TableRow/TableRow.tsx, packages/styles/src/themes/ds3.ts, packages/styles/src/themes/ds5.ts
Addresses: https://github.com/lumada-design/hv-uikit-react/issues/3804
=> fix(Table): HvTableCell sorted color not showing on first render

package-lock.json, packages/core/src/components/Dialog/Dialog.tsx, packages/core/src/components/TimeAgo/TimeAgo.stories.tsx, packages/core/src/components/Tooltip/Tooltip.tsx, packages/core/src/providers/Provider.tsx, packages/core/src/utils/document.ts, packages/core/src/utils/theme.ts
- Bump package versions (Applitools, Storybook, MUI, etc.)
This PR seems to have fixed Applitools styling (spacing) issues in some of our components:
- Checkbox, Radio, GlobalActions, Tabs, and component samples that use them
=> chore(deps): bump packages

app/src/pages/Flow/DashboardPreview/DashboardPreview.tsx, app/src/pages/Flow/Nodes/Dashboard.tsx
Fixes:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/d20ced59-4977-4d4d-8529-a6a44b6813a6
=> chore(app): fix chart width on first render

packages/core/src/components/Drawer/Drawer.stories.tsx, packages/core/src/components/Table/stories/TableHooks/ColumnResize.tsx, packages/core/src/components/Table/stories/TableHooks/UseHvFilters.tsx, packages/core/src/components/Table/stories/TableHooks/UseHvPagination.tsx
4 a11y issues fixed, namely all `scrollable-region-focusable` issues
=> docs: scrollable-region-focusable a11y issues fixed

packages/core/src/components/CheckBoxGroup/CheckBoxGroup.test.tsx, packages/core/src/components/CheckBoxGroup/CheckBoxGroup.tsx, packages/core/src/components/Table/stories/TableHooks/UseHvRowSelectionLocked.tsx, packages/lab/src/components/Dashboard/Dashboard.stories.tsx
- This change addresses DS specification on the flow of selection of items: when only some items are selected, pressing select all should remove all selections.
=>  fix(CheckboxGroup): fix incorrect select all or none behavior

.github/workflows/applitools.yml, .github/workflows/documentation.yml, .github/workflows/nightly.yml, .github/workflows/pr-close.yml, .github/workflows/pr.yml, .github/workflows/release-recover.yml, .github/workflows/release.yml, packages/core/src/OverflowTooltip/OverflowTooltip.js, packages/core/src/OverflowTooltip/stories/OverflowTooltip.stories.js, packages/core/src/OverflowTooltip/tests/tests/OverflowTooltip.test.js
- v4.x workflows fixed: several workflows were pointing to master and not v4.x 
- Backports part of [this fix](https://github.com/lumada-design/hv-uikit-react/pull/3820) to v4: `HvOverflowTooltip` fixed when `paragraphOverflow` is set to true: the tooltip was not showing.
- I didn't update the line clamp to 3 (instead 2) in this PR since I don't think it's needed. But let me know if you think otherwise.
=> fix(OverflowTooltip): paragraph overflow

packages/core/src/FilterGroup/Counter/Counter.js
Backports [this fix](https://github.com/lumada-design/hv-uikit-react/pull/3394) to v3
=> fix(FilterGroup): wrong count

packages/core/src/components/Button/Button.test.tsx, packages/core/src/components/Calendar/CalendarHeader/CalendarHeader.tsx, packages/core/src/components/Calendar/CalendarModel.test.tsx, packages/core/src/components/Calendar/CalendarNavigation/ComposedNavigation/ComposedNavigation.tsx, packages/core/src/components/Calendar/CalendarNavigation/MonthSelector/MonthSelector.tsx, packages/core/src/components/Calendar/model.tsx, packages/core/src/components/Header/Header.stories.tsx, packages/core/src/components/Header/Navigation/MenuBar/Bar.tsx, packages/core/src/components/Header/Navigation/MenuBar/MenuBar.tsx, packages/core/src/components/Header/Navigation/MenuItem/MenuItem.tsx, packages/core/src/components/Input/Input.tsx, packages/core/src/components/ListContainer/ListContainer.stories.tsx, packages/core/src/components/Tooltip/Tooltip.tsx, packages/core/src/components/Typography/Typography.tsx, packages/core/src/hooks/useControlled.ts, packages/core/src/hooks/useImageLoaded.ts
review some typings across core components
=> chore: review typings

packages/core/src/components/QueryBuilder/ConfirmationDialog/ConfirmationDialog.styles.tsx, packages/core/src/components/QueryBuilder/QueryBuilder.styles.tsx, packages/core/src/components/QueryBuilder/Rule/Rule.styles.tsx, packages/core/src/components/QueryBuilder/Rule/Rule.tsx, packages/core/src/components/QueryBuilder/Rule/Value/DateTimeValue/DateTimeValue.styles.tsx, packages/core/src/components/QueryBuilder/Rule/Value/NumericValue/Numeric.styles.tsx, packages/core/src/components/QueryBuilder/RuleGroup/RuleGroup.tsx
Small refactor of the query builder component to make it responsive. 
Since we don't have any DS specs for this component, let me know if you think the changes regarding responsiveness should be different.
=> perf(QueryBuilder): responsive layout

packages/core/src/FilterGroup/RightPanel/RightPanel.js
Backport of [this PR](https://github.com/lumada-design/hv-uikit-react/pull/3869) to v3.
=> fix(FilterGroup): fix total number of items on the right panel not showing the correct value when searching

packages/lab/src/components/Flow/Sidebar/Sidebar.tsx
- The drag overlay is now inside the sidebar drawer and not a sibling to fix the following bug:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/82a4eca3-e5a1-4b8d-a152-ea38144de0c9
=> fix(Flow): drag overlay inside sidebar drawer

docs/guides/theming/ThemeContext.tsx, packages/core/src/hooks/useTheme.ts
- Answers the comment left [here](https://github.com/lumada-design/hv-uikit-react/pull/3886#pullrequestreview-1780047121)
=> fix(useTheme): colors type

app/src/components/common/Header/Header.tsx, app/src/components/common/Tutorial/Step.tsx, packages/core/src/components/Button/Button.tsx
- forward `id` prop to `HvButton` root element (via others)
- fix app Tutorial `autoFocus` on "Next" button
=> fix(button): forward `id` prop

packages/core/src/components/Table/hooks/useBulkActions.ts
- explicit toggle bulk actions selection
- fixes a bug in development when using `React.StrictMode`
- improve docs/v6 typo warnings
=> fix(table): explicit toggle bulk actions selection

app/src/pages/Flow/Nodes/BarChart.tsx, app/src/pages/Flow/Nodes/DonutChart.tsx, app/src/pages/Flow/Nodes/Kpi.tsx, app/src/pages/Flow/Nodes/LineChart.tsx, packages/core/src/AvatarGroup/stories/AvatarGroup.stories.tsx
- The app was updated to leverage our internal hooks
=> chore(app): leverage internal flow hooks

packages/core/src/Tag/Tag.styles.tsx, packages/core/src/Tag/Tag.test.tsx, packages/core/src/Tag/Tag.tsx, packages/core/src/Tag/stories/Selectable.tsx, packages/core/src/Tag/stories/SelectableControlled.tsx, packages/core/src/Tag/stories/Tag.stories.tsx, packages/core/src/TagsInput/TagsInput.test.tsx
- Applitools errors are expected as the text size in the tags changed from `caption1` (12px) to `caption2` (10px) as specified.
=> feat(Tag): add actions

packages/core/src/BaseDropdown/BaseDropdown.test.tsx, packages/core/src/BaseDropdown/BaseDropdown.tsx, packages/core/src/Drawer/Drawer.stories.tsx, packages/core/src/Drawer/Drawer.tsx, packages/core/src/Grid/Grid.stories.tsx, packages/core/src/SimpleGrid/SimpleGrid.stories.tsx
- fix `HvDrawer` losing styled when `PaperProps` is passed
- needed to pass a `role` or custom component (eg. `aside`)
- add missing `HvBaseDropdown` `aria-disabled` when disabled
- fix `HvGrid`/`HvSimpleGrid` docs dark theme styles
=> Review Drawer & BaseDropdown accessibility

packages/core/src/Slider/Slider.tsx, packages/lab/src/Flow/Node/Parameters/ParamRenderer.tsx, packages/lab/src/Flow/Node/Parameters/Slider.tsx, packages/lab/src/Flow/stories/Usage.stories.mdx, packages/lab/src/Flow/types/flow.ts
- Added the Slider renderer. 
- Updated the docs.
=> feat(Flow): add Slider parameter renderer

.gitignore, examples/uikit-app-shell/package.json, examples/uikit-next/package.json, examples/uikit-vite-ts/.gitignore, examples/uikit-vite-ts/package.json
bump examples dependencies
addresses https://github.com/lumada-design/hv-uikit-react/pull/3911#pullrequestreview-1810774314 warnings
=> chore(examples): bump versions

packages/core/src/BaseDropdown/BaseDropdown.styles.tsx, packages/core/src/DatePicker/DatePicker.styles.tsx
Addresses part of https://github.com/lumada-design/hv-uikit-react/issues/3935
=> fix(DatePicker): input text overflowing

docs/overview/community/ReleaseVersioning.stories.mdx
Add "Breaking changes exceptions" docs according to our internal review
=> docs: add breaking changes exceptions

packages/core/src/Tag/Tag.tsx
- allows to use in `HvTooltip`, etc.
=> fix(Tag): add forwardRef

packages/lab/src/Flow/Node/Node.tsx, packages/lab/src/Flow/Node/Parameters/ParamRenderer.tsx, packages/lab/src/Flow/Node/Parameters/Select.tsx, packages/lab/src/Flow/Node/Parameters/Slider.tsx, packages/lab/src/Flow/Node/Parameters/Text.tsx, packages/lab/src/Flow/hooks/useFlowNode.ts, packages/lab/src/Flow/stories/Visualizations/Filter.tsx
- add `useFlowNodeUtils` wrapper to easily manipulate nodes
- add `setNodeData` to manipulate a node's `.data` object
=> feat(Flow): add `useFlowNodeUtils`

packages/core/src/FilterGroup/Counter/Counter.js, packages/core/src/FilterGroup/RightPanel/RightPanel.js, packages/core/src/FilterGroup/stories/FilterGroup.stories.test.js, packages/core/src/FilterGroup/tests/FilterGroup.test.js
Back ports https://github.com/lumada-design/hv-uikit-react/pull/3958 to v4 since this bug was introduced in this version recently
=> fix(FilerGroup): error when all option is selected & wrong counter

packages/core/src/FilterGroup/Counter/Counter.js, packages/core/src/FilterGroup/RightPanel/RightPanel.js, packages/core/src/FilterGroup/stories/FilterGroup.stories.test.js, packages/core/src/FilterGroup/tests/FilterGroup.test.js
Back ports https://github.com/lumada-design/hv-uikit-react/pull/3958 to v3 since this bug was introduced in this version recently
=> fix(FilterGroup): error when all option is selected & wrong counter

packages/core/src/FilterGroup/FilterGroup.test.tsx
@lumada-design/imperial Please review.
=> test: change locator to be more descriptive

packages/core/src/Table/renderers/renderers.tsx, packages/core/src/Table/stories/TableRenderers/DropdownColumnRenderer.stories.mdx, packages/core/src/Table/stories/TableRenderers/TableRenderers.tsx
I added this as a solution to [this](https://hv-eng.atlassian.net/jira/software/c/projects/HVUIKIT/boards/267?selectedIssue=HVUIKIT-7016) as  way for the user to be able to change how the dropdown behaves.
=> feat(hvDropdownColumn): add dropdown props

.gitignore, scripts/a11y-report/index.js
```
Report created 🚀
Found 1 violations have been found violations. Stories with issues:
https://lumada-design.github.io/uikit/master/?path=/story/tests-icons--icon-library"
```
=> ci(a11y): add logs with failed stories

.github/workflows/pr.yml, .github/workflows/static-checks.yml
@lumada-design/imperial Please review.
=> ci: move playwright tests to static-checks workflow

.github/ISSUE_TEMPLATE/1.bug_report.yml
- Make `v5` default
- Reword StackBlitz usage
- Consolidate environment & add build info
=> docs: improve issue template

packages/core/src/Table/stories/TableHooks/UseHvFilters.stories.mdx, packages/core/src/Table/stories/TableSection/TableFilter.tsx, packages/core/src/Table/stories/TableSection/TableSection.stories.mdx, packages/core/src/Table/stories/TableSection/TableSectionSamples.tsx
Table filter sample added:
- As discussed, the filter group was used instead of opening a dialog with a new filter.
=> docs(Table): table filter sample added

packages/core/src/Pagination/Pagination.styles.tsx, packages/core/src/Pagination/Pagination.tsx, packages/core/src/Pagination/Select.styles.tsx, packages/core/src/Pagination/Select.tsx, packages/core/src/Table/stories/TableSection/CompleteTableSection.tsx, packages/core/src/Table/stories/TableSection/TableEditable.tsx, packages/core/src/Table/stories/TableSection/TableFilter.tsx, packages/core/src/TableSection/TableSection.styles.tsx
Applitools errors are expected.
=> fix(Pagination): fix page size dropdown styles

templates/AssetInventory/CardView/CardView.tsx, templates/AssetInventory/data/utils.tsx, templates/AssetInventory/index.tsx, templates/Dashboard/index.tsx, templates/ListView/Kpi/Kpi.tsx, templates/ListView/data/utils.tsx, templates/ListView/index.tsx
improve templates types, loading indicators & other stuff
=> docs(templates): loading & code improvements

packages/core/src/Skeleton/CustomSkeleton.tsx, packages/core/src/Skeleton/Skeleton.stories.tsx, packages/core/src/Skeleton/Skeleton.styles.tsx, packages/core/src/Skeleton/Skeleton.test.tsx, packages/core/src/Skeleton/Skeleton.tsx, packages/core/src/Skeleton/index.tsx, packages/core/src/index.ts, templates/AssetInventory/CardView/CardView.tsx, templates/AssetInventory/data/utils.tsx, templates/AssetInventory/index.tsx
- Add the new component `HvSkeleton`
- Update the `AssetInventory` template to use this new component
=> feat(Skeleton): add Skeleton component

docs/overview/welcome/Footer/Footer.tsx, packages/core/src/Table/hooks/index.ts, packages/core/src/Table/hooks/useRowState.ts, packages/core/src/Table/stories/TableHooks/TableHooks.mdx, packages/core/src/Table/stories/TableHooks/TableHooks.stories.tsx, packages/core/src/Table/stories/TableHooks/UseHvFilters.mdx, packages/core/src/Table/stories/TableHooks/UseHvGroupBy.mdx, packages/core/src/Table/stories/TableHooks/UseHvHeaderGroups.mdx, packages/core/src/Table/stories/TableHooks/UseHvPagination.mdx, packages/core/src/Table/stories/TableHooks/UseHvRowExpand.mdx, packages/core/src/Table/stories/TableHooks/UseHvRowSelection.mdx, packages/core/src/Table/stories/TableHooks/UseHvRowState.mdx, packages/core/src/Table/stories/TableHooks/UseHvRowState.tsx, packages/core/src/Table/stories/TableHooks/UseHvSortBy.mdx, packages/core/src/Table/stories/storiesUtils.tsx
The hook was need to create a better Editable Table sample, I separated this from that pr for easier review.
Some broken links were fixed, and some tan stack were replaced with an unofficial link because the official was removed. This might not be a great solution, tell me if you think of something better.
=> feat: add useHvRowState hook

packages/core/src/QueryBuilder/Rule/Value/Value.tsx
Addresses https://github.com/lumada-design/hv-uikit-react/issues/4109
=> fix(QueryBuilder): value renderer

package-lock.json, packages/core/src/BaseCheckBox/icons.tsx, packages/core/src/FileUploader/File/File.tsx, packages/core/src/FileUploader/FileList/FileList.tsx, packages/core/src/VerticalNavigation/Navigation/Navigation.tsx, packages/core/src/VerticalNavigation/TreeView/TreeViewItem.tsx, packages/core/src/utils/wrapperTooltip.tsx
Fix some (small) a11y issues found by the new tool
- duplicate ids
- usage of `HvIconButton`
- usage of `HvOverflowTooltip`
=> fix(a11y): fix issues

packages/icons/lib/IconBase.tsx
Problem:
https://github.com/lumada-design/hv-uikit-react/assets/43220251/d83ee55a-c36e-4ff7-b830-2b1c3e3bc6d8
- This is why we were having several problems in Applitools
=> fix: icon palette mutation

packages/core/src/BaseCheckBox/BaseCheckBox.styles.ts, packages/core/src/BaseRadio/BaseRadio.styles.tsx, packages/core/src/CheckBox/CheckBox.stories.tsx, packages/core/src/LoadingContainer/LoadingContainer.stories.tsx, packages/core/src/Radio/Radio.stories.tsx, packages/core/src/Tag/stories/Tag.stories.tsx
- The wrong border color was used for the base checkbox component when disabled and checked
- The wrong background color was used for the base radio component
=> fix: base radio and base checkbox style

packages/core/src/Dropdown/stories/CustomDropdown.tsx, packages/core/src/Dropdown/stories/Dropdown.stories.tsx
I'm not sure if "Custom Dropdown" the best title for this sample or if I should just leave it has "HvBaseDropdown". I also used this story to add a sample with TreeView with search, but it may be hard to find, tell me if you think its better to separate.
=> docs(Dropdown): add base dropdown documentation

packages/core/src/MultiButton/MultiButton.tsx, packages/core/src/QueryBuilder/Context.tsx, packages/core/src/QueryBuilder/QueryBuilder.test.tsx, packages/core/src/QueryBuilder/QueryBuilder.tsx, packages/core/src/QueryBuilder/types.ts, packages/core/src/hooks/useLabels.ts, packages/core/src/utils/deepMerge.ts
Addresses https://github.com/lumada-design/hv-uikit-react/issues/4148
=> fix(QueryBuilder): override labels

packages/lab/src/Flow/Flow.spec.ts, packages/lab/src/Flow/Node/Node.styles.tsx, packages/lab/src/Flow/Node/Node.tsx, packages/lab/src/Flow/stories/Base/MLModelPrediction.tsx, packages/lab/src/Flow/stories/InitialState/index.tsx
=> feat(Node): add inline edit

packages/core/src/Table/stories/TableComplete/TableComplete.stories.tsx, packages/core/src/VerticalNavigation/VerticalNavigation.stories.tsx, packages/core/src/VerticalNavigation/stories/Collapsible.tsx, packages/core/src/VerticalNavigation/stories/CollapsibleIcons.tsx, packages/core/src/VerticalNavigation/stories/CollapsibleIconsWithCustomPopupStyles.tsx, packages/core/src/VerticalNavigation/stories/CollapsibleIconsWithoutSubItems.tsx, packages/core/src/VerticalNavigation/stories/Main.tsx, packages/core/src/VerticalNavigation/stories/MobileNavigation.tsx, packages/core/src/VerticalNavigation/stories/SliderMode.tsx, packages/core/src/VerticalNavigation/stories/TreeViewMode.tsx, packages/core/src/VerticalNavigation/stories/WithoutActions.tsx
Trying to fix some of the Applitools glitches: [example](https://eyes.applitools.com/app/test-results/00000251688508256582/?accountId=NWMfIF0XfUeh3g9JqZjRrg~~)
- Vertical navigation code samples improved and unnecessary `useEffect` removed
=> chore: review stories code sample

docs/tests/Table.stories.tsx, packages/core/src/Table/hooks/useHeaderGroups.ts
Addresses: https://github.com/lumada-design/hv-uikit-react/issues/4171
=> fix(table): grouped columns with sticky table

packages/core/src/Accordion/Accordion.test.tsx, packages/core/src/Accordion/Accordion.tsx
- Prop added to opt out of `stopPropagation` and `preventDefault` default behaviour
- Tests cleanup and new tests added 
ℹ️ Feel free to propose another naming for the prop, I wasn't very inspired 😅
=> feat(accordion): enable opting out of stopPropagation and preventDefault default behaviour

packages/core/src/Slider/Slider.test.tsx, packages/core/src/Slider/Slider.tsx
Adding test for https://github.com/lumada-design/hv-uikit-react/pull/4186
=> test(slider): new test added

package-lock.json, packages/code-editor/CHANGELOG.md, packages/code-editor/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/lab/CHANGELOG.md, packages/lab/package.json, packages/viz/CHANGELOG.md, packages/viz/package.json
This reverts commit afca98e38e1a611d8ac740a640801d42197e1d4b.
=> Revert "chore(release): publish"

packages/cli/package.json, packages/code-editor/package.json, packages/core/package.json, packages/icons/package.json, packages/lab/package.json, packages/shared/package.json, packages/styles/package.json, packages/uno-preset/package.json, packages/viz/package.json
- Add missing `package.json` fields in `styles` & `uno-plugin` packages
- add `directory` entry
- align entry order
=> chore: add missing package.json fields

packages/core/src/ActionsGeneric/ActionsGeneric.tsx, packages/core/src/DropDownMenu/DropDownMenu.tsx, packages/core/src/index.ts, packages/pentaho/src/Canvas/Canvas.mdx, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.spec.ts, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.stories.tsx, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.styles.tsx, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.test.tsx, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.tsx, packages/pentaho/src/Canvas/ToolbarTabs/index.ts, packages/pentaho/src/Canvas/ToolbarTabs/stories/Controlled.tsx, packages/pentaho/src/Canvas/index.ts
- Browser-like tabs component, named <s>`HvCanvasOrganizer`</s> `HvCanvasToolbarTabs`, added to the Pentaho package (under Canvas)
- <s>⚠️ **Let me know if you have a better name for the component**</s>
- Tests added
=> feat: canvas toolbar tabs component added

.github/workflows/release.yml
=> ci: fix release script

packages/core/src/providers/ThemeProvider.tsx
- configure MUI's createTheme to use our font/color tokens by default
=> feat(Provider): align MUI theme with UI Kit tokens

docs/foundation/Icons/Library.tsx, packages/core/src/Accordion/stories/FacetSearchSample.tsx, packages/core/src/Calendar/utils.tsx, packages/core/src/Drawer/Drawer.stories.tsx, packages/core/src/Section/Section.stories.tsx, packages/core/src/Table/TableBody/TableBody.tsx, packages/core/src/Table/TableCell/TableCell.tsx, packages/core/src/Table/TableHead/TableHead.tsx, packages/core/src/Table/TableHeader/TableHeader.tsx, packages/core/src/Table/TableRow/TableRow.tsx, packages/core/src/Table/TableSectionContext.ts, packages/core/src/VerticalNavigation/TreeView/utils/NodeTreeMap.utils.test.tsx, packages/icons/src/IconBase.tsx, packages/lab/src/StepNavigation/StepNavigation.tsx, packages/styles/tsconfig.json, packages/utils/src/hooks/useDefaultProps.ts, packages/utils/src/utils/classes.ts, packages/viz/src/ConfusionMatrix/ConfusionMatrix.stories.tsx, packages/viz/src/ConfusionMatrix/utils.ts
some minor improvements I had in my stashes:
- typings improvements
- linting performance
- ~hoist conditional CanvasPanel classes to root~ (too many changes required, reverted)
=> chore: typings & linting

packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.spec.ts, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.styles.tsx, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.test.tsx, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.tsx
Addresses comments left on: https://github.com/lumada-design/hv-uikit-react/pull/4283
=> chore(ToolbarTabs): review tests and use palette

packages/pentaho/src/Canvas/BottomPanel/BottomPanel.spec.tsx, packages/pentaho/src/Canvas/BottomPanel/BottomPanel.test.tsx, packages/pentaho/src/Canvas/PanelTabs/PanelTabs.test.tsx, packages/pentaho/src/Canvas/SidePanel/SidePanel.test.tsx, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.spec.ts, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.test.tsx
- New tests added to Pentaho components to test keyboard navigation
=> test: new tests with keyboard added for Pentaho components

packages/core/src/Forms/Suggestions/Suggestions.stories.tsx, packages/core/src/Forms/Suggestions/Suggestions.tsx, packages/core/src/Input/countries.ts
(fix is basically in the SB docs)
- add `open` prop that is fully controlled & deprecate `expanded`
- use `ClickAwayListener` to fix excessive `onClose` calls
- improve docs custom sample
=> fix(Suggestions): onClose & controlled open prop

packages/core/src/Card/stories/Variants.tsx, packages/styles/src/themes/pentahoPlus.ts
- add status colors to the variants sample
- remove hover effect on non-selectable cards
=> chore: add status to card variants

packages/code-editor/src/CodeEditor/languages/xml.ts
Improvements for the XML code editor:
- XSD parsing doesn't depend on the namespace (`xs:`, `xsd:`, etc)
- Element suggestions are now based on the hierarchy:
https://github.com/user-attachments/assets/c0d489b3-8c46-4280-b5fd-0c419fc8da69
=> feat: improve suggestions and parsing for XML code editor

package-lock.json, packages/code-editor/package.json, packages/code-editor/src/CodeEditor/CodeEditor.tsx, packages/code-editor/src/CodeEditor/languages/xml.ts, packages/code-editor/src/CodeEditor/plugins.ts, packages/code-editor/src/CodeEditor/stories/Xml/Xml.tsx
Code formatter added for XML: formats on paste and on blur
=> feat: xml code formatter

package-lock.json, package.json, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabEditor.tsx
- The content of the toolbar tabs inline editor is sanitised: more info in the Jira issue
=> fix(ToolbarTabs): inline edit content sanitised

packages/core/src/Badge/Badge.styles.tsx
- The `Badge` component is `Stable` and `Ready for Dev`. The only change was on the typography (`label` > `caption2`)
=> fix(Badge): add pentaho plus styles

.config/vite.config.ts, apps/app/package.json, apps/app/src/pages/Components.tsx, apps/docs/package.json, docs/overview/welcome/Header/Header.tsx, package-lock.json, package.json, packages/cli/package.json, packages/cli/src/templates/Welcome/index.tsx, packages/code-editor/package.json, packages/core/package.json, packages/core/src/Card/stories/Variants.tsx, packages/core/src/Carousel/Carousel.stories.tsx, packages/core/src/FileUploader/FileUploader.test.tsx, packages/core/src/Login/Login.stories.tsx, packages/core/src/TagsInput/TagsInput.stories.tsx, packages/core/src/TimePicker/TimePicker.test.tsx, packages/icons/package.json, packages/lab/package.json, packages/pentaho/package.json, packages/pentaho/src/Canvas/ToolbarTabs/ToolbarTabs.test.tsx, packages/shared/package.json, packages/styles/package.json, packages/uno-preset/package.json, packages/utils/package.json, packages/viz/package.json
- docs: optimize images
- some images had a large size and/or low quality
- test: default to `happy-dom` test environment
- better, faster, stronger
- fix `package.json` issues found via `npm pkg fix`
=> chore: misc improvements

.config/chromatic.config.json, .storybook/manager-head.html, .storybook/preview-head.html, .storybook/setupChromatic.ts, apps/app/index.html, packages/viz/src/LineChart/LineChart.stories.tsx
- load Inter & Open Sans fonts in single request & in <link preload>
- increase LineChart visual threshold to avoid browser flukes
=> test(Chromatic): better font loading & LineChart diffThreshold

apps/app/src/components/ThemeSwitcher.tsx, apps/app/src/components/common/UnitSlider.tsx, apps/app/src/generator/FontFamily/FontFamily.tsx, apps/app/src/generator/FontSizes/FontSizes.tsx, apps/app/src/generator/Sidebar/Sidebar.tsx, apps/app/src/generator/Typography/Typography.tsx, docs/guides/theming/ThemeStructure.tsx, package.json, packages/core/src/Dropdown/Dropdown.tsx, packages/core/src/Dropdown/stories/ExternalErrorMessage.tsx, packages/core/src/Dropdown/stories/MultiSelection.tsx, packages/core/src/QueryBuilder/Rule/Attribute/Attribute.tsx, packages/core/src/QueryBuilder/Rule/Operator/Operator.tsx, packages/core/src/QueryBuilder/Rule/Value/BooleanValue/BooleanValue.tsx, packages/core/src/QueryBuilder/stories/CustomRenderers.tsx, packages/core/src/Table/renderers/DropdownColumnCell/DropdownColumnCell.tsx, packages/core/src/Table/renderers/renderers.tsx, packages/core/src/Table/stories/TableHooks/AlternativeLayout.tsx, packages/lab/src/Flow/stories/CustomDrop/index.tsx, packages/lab/src/Flow/stories/DynamicHandles/index.tsx, packages/viz/src/BarChart/stories/BarChart.stories.tsx, packages/viz/src/DonutChart/DonutChart.stories.tsx, packages/viz/src/LineChart/LineChart.stories.tsx
add generics to `HvDropdown` so that the `values` are correctly inferred, and `multiSelect` changes `onChange`'s type
=> feat(Dropdown): infer values and onChange types using generics

package-lock.json, packages/lab/src/Wizard/Wizard.stories.tsx, packages/lab/src/Wizard/Wizard.test.tsx, packages/lab/src/Wizard/Wizard.tsx, packages/lab/src/Wizard/WizardContainer/WizardContainer.tsx, packages/lab/src/Wizard/WizardContent/WizardContent.tsx, packages/lab/src/Wizard/WizardTitle/WizardTitle.tsx
- add missing `className` forwarding
- add `data-title` alternative to pass a title (which doesn't require a `@ts-ignore`)
=> fix(Wizard): `className` forwarding & `data-title` for title

packages/styles/src/themes/pentahoPlus.ts
- Updated visual design for Input elements including select, input, dropdown, and dropdown menu to be closer aligned with PD guidelines.
=> fix: intermediary PD design alignment for input elements

packages/core/src/Table/TableCell/TableCell.styles.tsx, packages/core/src/Table/TableHeader/TableHeader.styles.tsx, packages/core/src/Table/TableHeader/TableHeader.tsx, packages/core/src/Table/TableRow/TableRow.styles.tsx, packages/core/src/Table/TableRow/TableRow.tsx
- improve/fix column resizing (color, increase drag area)
- improve sortable column hover styles
- current animation is buggy (sometimes hover shows up, sometimes not)
- improve row hover styles
- current animation is slow/sloppy
=> fix(Table): sort/hover/resize styles

apps/app/uno.config.ts, apps/docs/uno.config.ts, package-lock.json, package.json, uno.config.ts
- hoist `uno.config.ts` to root so we get proper IDE completions across the code-base by default
- add unocss icons plugin & phosphor icons
=> chore(unocss): hoist config & add icons plugin

packages/pentaho/src/Canvas/SidePanel/SidePanel.styles.tsx
- decrease the expand button height so that it doesn't overlap other elements so easily
=> fix(Canvas): expand button dimensions

apps/docs/src/components/code/Live.tsx, apps/docs/src/pages/components/Playground.tsx, apps/docs/src/pages/components/_meta.ts, apps/docs/src/pages/components/input.mdx, apps/docs/src/pages/components/textarea.mdx, packages/core/src/Input/Input.stories.tsx
- add Input
- add TextArea (inherits/links to input for most cases)
- improve `Playground` & `Live` (add missing `check`, fallback to `text`, change spacing, etc.)
=> docs: add Input/TextArea components & improve Playground

apps/docs/src/pages/_document.tsx, docs/overview/GetStarted.mdx, examples/uikit-app-shell/index.html, examples/uikit-vite-ts/index.html, packages/cli/src/baselines/vite/index.html, packages/cli/src/plop-templates/app-shell/index.html.hbs, packages/core/src/Typography/Usage.mdx, packages/styles/src/themes/pentahoPlus.ts
- fix `borderRadius` in P+ theme
- also uniformizes font usage in examples
=> fix(MultiButton): borderRadius

packages/core/src/MultiButton/MultiButton.styles.tsx, packages/core/src/MultiButton/stories/MultiButton.stories.tsx, packages/styles/src/themes/pentahoPlus.ts
fix `borderRadius` in larger sizes (sm/lg) & add new visual tests for it
=> fix(MultiButton): borderRadius in sm/lg sizes

packages/cli/src/templates/Canvas/index.tsx, packages/core/src/Accordion/Accordion.tsx, packages/core/src/Card/stories/Expandable.tsx, packages/core/src/DropdownButton/DropdownButton.tsx, packages/core/src/Forms/Suggestions/Suggestions.stories.tsx, packages/core/src/Section/Section.tsx, packages/core/src/Table/hooks/useRowExpand.tsx, packages/core/src/VerticalNavigation/TreeView/TreeViewItem.tsx, packages/icons/src/IconBase.tsx, packages/icons/src/IconContainer.tsx, packages/pentaho/src/Canvas/SidePanel/SidePanel.tsx
- Add `rotate` property to icons to simplify usage & optimize rendering
=> feat(icons): add rotate property

apps/docs/src/pages/components/radio-group.mdx
Some changes to the `Playground` to allow receiving children wrapped in a React Fragment.
=> docs: add `RadioGroup` documentation

package-lock.json, packages/core/src/ButtonBase/ButtonBase.styles.ts, packages/core/src/Tag/Tag.styles.tsx, packages/core/src/Tag/Tag.tsx, packages/core/src/TagsInput/TagsInput.styles.tsx, packages/core/src/TagsInput/TagsInput.test.tsx, packages/core/src/TagsInput/TagsInput.tsx, packages/core/src/utils/keyboardUtils.ts, packages/styles/package.json, packages/styles/src/theme.ts, packages/styles/src/themes/pentahoPlus.ts
- prepare tag to receive custom colors
- fix button/hover cursors when tag isn't selectable
- remove MUI `Chip` dependency to simplify styles overriding
=> fix(Tag): selectable styles & overridable colors

apps/docs/package.json, package-lock.json
https://github.com/advisories/GHSA-7m27-7ghc-44w9
=> chore: fix next vulnerability

apps/docs/next-env.d.ts, apps/docs/src/pages/components/tabs.mdx, packages/cli/src/templates/Dashboard/GridPanel.tsx, packages/core/src/Panel/Panel.styles.tsx, packages/core/src/Tabs/Tabs.stories.tsx, packages/core/src/Tabs/Tabs.styles.tsx
- add support for scrollable `HvTabs`
- simplify `HvPanel` border customisation
=> fix(Tabs): support for scrollable tabs

package-lock.json, packages/cli/package.json
- add `cpy-cli` to `cli`, which is only installed in the root
=> build(cli): add missing dev dependency

packages/core/src/Table/stories/TableSection/TableEditable.tsx, packages/core/src/Table/stories/TableSection/TableFilter.tsx, packages/viz/src/BarChart/stories/CustomEchartsOptions.tsx, packages/viz/src/providers/Provider.tsx, packages/viz/src/utils/registerTheme.ts
- fallback to default `echarts` theme if `HvVizProvider`/`HvProvider` aren't passed or have invalid colors/mode
- refactor to `keyframes` object
=> fix(VizProvider): fallback to default theme

docs/guides/theming/Theming.mdx, packages/core/src/ColorPicker/Fields/Fields.styles.tsx, packages/core/src/ColorPicker/PresetColors/PresetColors.styles.tsx, packages/core/src/ColorPicker/SavedColors/SavedColors.styles.tsx, packages/core/src/EmptyState/EmptyState.styles.tsx, packages/core/src/Tag/Tag.styles.tsx, packages/lab/src/Flow/stories/SubFlow/Node.tsx, packages/styles/src/themes/ds3.ts, packages/styles/src/tokens/space.ts
add `theme.space.xxs` according to the DS specs
=> feat(theme): add `xxs` spacing

apps/docs/src/components/code/Live.tsx, apps/docs/src/pages/components/tree-view.mdx
Also includes a small change to the `Live` component to allow the importing of UI Kit hooks.
=> docs: add `TreeView` documentation

apps/docs/package.json, apps/docs/src/components/code/Live.tsx, apps/docs/src/components/page/Description.tsx, apps/docs/src/pages/components/code-editor.mdx, apps/docs/src/pages/globals.css, package-lock.json, packages/code-editor/src/CodeEditor/CodeEditor.tsx
Also includes: 
- small fix to the `CodeEditor` component
- adding the package `react-markdown` to properly format JS Doc on Nextra
=> docs: add `CodeEditor` documentation

apps/docs/src/components/page/Props.tsx
- Move `@deprecated` props in the props table to the end and mark them with strikethrough
=> docs: mark deprecated props

packages/core/src/BaseRadio/BaseRadio.styles.tsx, packages/core/src/Radio/Radio.stories.tsx, packages/core/src/Radio/Radio.styles.tsx, packages/core/src/Radio/Radio.tsx, packages/core/src/Table/TableCell/TableCell.styles.tsx, packages/core/src/Table/TableHeader/TableHeader.styles.tsx, packages/styles/src/themes/pentahoPlus.ts
- fix Radio disabled hover styles
- remove (some) fixed Radio height (still forced 32px, but easier to override)
- improve Radio & TableCell border styling customisability
=> fix: Radio & TableCell style customisability

apps/docs/src/components/Header.tsx, apps/docs/src/components/code/CodeBlock.tsx, apps/docs/src/components/usage/Classes.tsx, apps/docs/src/components/usage/Props.tsx, apps/docs/src/pages/components/tag.mdx, apps/docs/src/pages/components/tags-input.mdx, packages/core/src/Table/TableBody/TableBody.tsx
- add navigation to component props & classes
- add TagsInput
=> docs: add TagsInput

packages/core/src/Banner/Banner.tsx, packages/core/src/Banner/BannerContent/BannerContent.styles.tsx, packages/core/src/Banner/BannerContent/BannerContent.tsx, packages/core/src/Snackbar/Snackbar.stories.tsx, packages/core/src/Snackbar/Snackbar.tsx, packages/core/src/Snackbar/SnackbarContent/SnackbarContent.styles.ts, packages/core/src/Snackbar/SnackbarContent/SnackbarContent.tsx, packages/core/src/utils/Callout.tsx
- fix Banner style alignment
- deprecate duplicate classes
- add `HvCallout` (private) utility that merged `BannerContent` & `SnackbarContent` features & classes
=> style: Banner & Snackbar alignment

packages/core/src/BaseInput/BaseInput.styles.tsx, packages/core/src/CheckBox/CheckBox.styles.tsx, packages/core/src/CheckBoxGroup/CheckBoxGroup.styles.tsx, packages/core/src/DatePicker/DatePicker.styles.tsx, packages/core/src/Dropdown/Dropdown.styles.tsx, packages/core/src/FormElement/WarningText/WarningText.styles.tsx, packages/core/src/RadioGroup/RadioGroup.styles.tsx, packages/core/src/Select/Select.styles.ts, packages/core/src/SelectionList/SelectionList.styles.tsx, packages/core/src/Switch/Switch.styles.tsx, packages/core/src/TagsInput/TagsInput.styles.tsx, packages/core/src/TimePicker/TimePicker.styles.ts, packages/styles/src/theme.ts, packages/styles/src/themes/ds3.ts, packages/styles/src/themes/ds5.ts, packages/styles/src/themes/pentahoPlus.ts, packages/styles/src/types.ts
- add `theme.form.errorColor` and use it in the various input/form elements
=> feat(theme): add `form.errorColor` token

.storybook/decorators/withThemeDecorator.decorator.tsx, .storybook/preview.ts
- add custom emotionCache with no vendor prefixes, for better dev debugging
- migrate from deprecated APIs
=> chore(storybook): add custom emotionCache

packages/core/src/MultiButton/MultiButton.styles.tsx, packages/core/src/MultiButton/stories/MultiButton.stories.tsx, packages/styles/src/themes/pentahoPlus.ts
- Fixes the incorrect border styles when the `MultiButton` only has one `Button`
- The left border radius was being incorrectly overridden by the last button styles
- Added visual test
=> fix(MultiButton): incorrect border styles when the `MultiButton` has only one button

apps/app/src/components/Header.tsx, apps/app/src/generator/CodeEditor/CodeEditor.tsx, apps/app/src/pages/Debug.tsx, apps/app/src/routes.tsx, apps/docs/src/components/Examples.tsx, apps/docs/src/components/Footer.tsx, apps/docs/src/components/code/ExpandableControls.tsx, apps/docs/src/components/code/ExpandableLayout.tsx, apps/docs/src/components/code/Playground.tsx, apps/docs/src/components/code/ToggableControls.tsx, apps/docs/src/components/code/ToggableLayout.tsx, apps/docs/src/components/home/CardsSection.tsx, apps/docs/src/components/home/HeroSection.tsx, apps/docs/src/components/home/Home.tsx, apps/docs/src/components/home/cards/Card.tsx, apps/docs/src/components/home/cards/DataConfig.tsx, apps/docs/src/components/home/cards/DataInsights.tsx, apps/docs/src/components/home/cards/DataSecurity.tsx, apps/docs/src/components/home/cards/FinancialPerformance.tsx, apps/docs/src/components/usage/Classes.tsx, apps/docs/src/components/usage/Description.tsx, apps/docs/src/components/usage/Props.tsx, apps/docs/src/pages/components/tooltip.mdx, apps/docs/src/pages/globals.css, docs/guides/styling/UtilityClasses.mdx
- use semantic spacing units & color tokens directly in docs
- rename App debug route to `Debug.tsx`, for better searching (we have tokens of `test.tsx` files)
- add App Color Switcher
=> docs: update unocss classes

package-lock.json
run `npm i` + `npm dedupe` to address [package-lock.json issue](https://github.com/lumada-design/hv-uikit-react/actions/runs/14105560831/job/39511208946?pr=4627)
=> chore(deps): dedupe

package-lock.json, packages/core/src/BaseInput/BaseInput.styles.tsx, packages/core/src/ButtonBase/ButtonBase.styles.ts, packages/core/src/FormElement/InfoMessage/InfoMessage.styles.tsx, packages/core/src/FormElement/Label/Label.styles.tsx, packages/core/src/Input/Input.styles.tsx, packages/core/src/Input/Input.test.tsx, packages/core/src/Input/Input.tsx, packages/styles/src/themes/pentahoPlus.ts
- align Input/FormElement label/description spacing
- add HvAdornment hover/active styles (both NEXT & P+ have it)
- update `pentahoPlus` styles:
- red required `*`
- HvInput background & hover styles
- rounded Searchbox
=> feat(Input): align P+ styles

packages/styles/src/themes/pentahoPlus.ts
=> style(Notification): fix P+ icon alignment

packages/core/src/stories/Components.test.stories.tsx
adjust grid/flex aligment layout so UIs are more stable when adding new elements
=> test(Chromatic): improve test stability

apps/docs/src/pages/components/checkbox-group.mdx, apps/docs/src/pages/components/input.mdx
also improves input adornments
=> docs(CheckBoxGroup): add component

packages/core/src/BaseDropdown/BaseDropdown.tsx, packages/core/src/Dropdown/Dropdown.test.tsx
add missing `disablePortal` prop forwarding. closes #4591
=> fix(Dropdown): disablePortal usage

.eslintrc.json, apps/docs/src/components/code/PopupLayout.tsx, apps/docs/src/examples/inputs/DropdownPrefix.tsx, apps/docs/src/examples/inputs/EditableInput.tsx, apps/docs/src/examples/inputs/TagsDropdown.tsx, apps/docs/src/examples/inputs/TagsSuggestions.tsx, apps/docs/src/pages/examples/inputs.mdx, packages/core/src/QueryBuilder/types.ts, packages/core/src/Table/TableHeader/TableHeader.tsx, packages/styles/src/types.ts
- add inline editable value sample
- fix tags suggestions adornment focus
- re-enable `no-unused-vars` ESLint rule (from warn to error): we were starting to pile-up warnings
=> docs(Input): add inline editable value

apps/docs/package.json, apps/docs/src/components/Examples.tsx, apps/docs/src/components/code/utils.ts, apps/docs/src/examples/kpis/DataLoading.tsx, apps/docs/src/examples/kpis/Selectable.tsx, apps/docs/src/examples/kpis/Semantic.tsx, apps/docs/src/pages/examples/_meta.ts, apps/docs/src/pages/examples/kpis.mdx, package-lock.json
https://lumada-design.github.io/uikit-docs/pr-4665/examples/kpis
=> docs(KPIs): add examples

packages/core/src/Dropdown/Dropdown.test.tsx, packages/core/src/Dropdown/List/List.tsx
Addresses https://github.com/lumada-design/hv-uikit-react/issues/4592
=> fix(Dropdown): ignore `disabled` items on select all

apps/docs/src/components/code/Controls.tsx, apps/docs/src/pages/components/icon-container.mdx, apps/docs/src/pages/docs/icon-library.mdx
- review `options` so that user-defined values (`control.values`) can be used
- move control types to components (instead of components inside components)
- update color & size props in icons
=> docs: review controls

packages/core/src/FormElement/Suggestions/Suggestions.styles.tsx, packages/styles/src/themes/pentahoPlus.ts
⚠️ Changes in Chromatic are expected and valid.
=> fix(Popper): align styles of poppers with specs

packages/styles/src/themes/pentahoPlus.ts
update `textDimmed` & `bgHover` colors
=> fix(theme): update P+ textDimmed & bgHover colors

docs/guides/styling/UtilityClasses.stories.tsx, packages/uno-preset/src/theme.ts
change uno plugin theme radius to use CSS vars
=> fix(uno): use radius from CSS vars

.storybook/manager-head.html
This reverts commit 29062dfa6982071fa7691d01a3879209b5c50423.
Revert https://github.com/lumada-design/hv-uikit-react/pull/4727 because it's no longer published
=> revert: "chore(sb): add top banner linking to new docs (#4727)"

packages/core/src/Table/stories/Table.stories.tsx
- remove "TableComplete" samples whose features are covered in other tables
- GroupedRows covers row expansion & header groups
=> test(Chromatic): merge table samples

packages/core/src/stories/Icons.test.stories.tsx
(removed by mistake in https://github.com/lumada-design/hv-uikit-react/pull/4744)
=> test(Icons): add icons test

.github/workflows/build.yml, package-lock.json, tsconfig.json
- fix `build.yml` script (`npm run build` instead of `npm run build -w packages`)
- run `npm dedupe` & `npm audit fix` to address issues (including #4782)
=> chore: fix build workflow & bump packages

package.json, packages/config/package.json
- config package wasn't correctly published, as `lerna` is expecting to publish from the `package` directory
- delete old unused `depcheck` & `lab:flow` scripts
=> fix(config): package publishing

apps/app/package.json, apps/default-app/package.json, examples/uikit-app-shell/package.json, examples/uikit-vite-ts/package.json, package-lock.json, package.json, packages/app-shell-ui/package.json, packages/code-editor/package.json, packages/core/package.json, packages/core/src/Card/stories/Expandable.tsx, packages/core/src/Grid/Grid.tsx, packages/core/src/hooks/useUniqueId.ts, packages/core/src/providers/Provider.tsx, packages/core/src/providers/ThemeProvider.tsx, packages/icons/package.json, packages/lab/package.json, packages/pentaho/package.json, packages/shared/package.json, packages/utils/package.json, packages/viz/package.json, templates/Canvas/ListView.tsx, templates/Canvas/Sidebar.tsx
migrate to MUI@7 & React@18 (simplify `useId`)
=> chore(deps): migrate to MUI@7 & react>=18

packages/core/src/stories/Icons.test.stories.tsx, packages/icons/src/IconBase.tsx
- remove `semantic` & `inverted` props
=> feat(icons): remove deprecated `inverted` & `semantic` props

.storybook/decorators/withThemeDecorator.decorator.tsx, apps/app/src/App.tsx, apps/app/src/components/Header.tsx, apps/default-app/app-shell.config.ts, apps/docs/src/app/examples/charts/GaugeChart.tsx, apps/docs/src/components/Main.tsx, apps/docs/src/components/code/DocsProvider.tsx, apps/docs/src/content/docs/theming.mdx, examples/uikit-vite-ts/src/Container.tsx, packages/app-shell-shared/src/types/Config.ts, packages/app-shell-ui/src/components/AppShellProvider/AppShellProvider.test.tsx, packages/app-shell-ui/src/components/AppShellProvider/AppShellProvider.tsx, packages/app-shell-ui/src/hooks/useThemeEventListener.test.tsx, packages/app-shell-ui/src/hooks/useThemeEventListener.ts, packages/app-shell-vite-plugin/src/vite-configuration-processor-plugin.ts, packages/app-shell-vite-plugin/src/vite-watch-config-plugin.ts, packages/code-editor/src/CodeEditor/CodeEditor.tsx, packages/core/src/providers/Provider.test.tsx, packages/core/src/providers/Provider.tsx, packages/core/src/providers/ThemeProvider.tsx, packages/shared/src/context/ThemeContext.ts, packages/styles/src/utils.ts, packages/viz/src/BaseChart/BaseChart.tsx, packages/viz/src/hooks/index.ts, packages/viz/src/hooks/useVizTheme.ts, packages/viz/src/providers/Provider.tsx
remove `themes` from `HvProvider` in favour of passing a single theme
```diff
<HvProvider
-  themes={[pentaho]}
+ theme={pentaho}
/>
```
=> chore(Provider): remove multi-theme support
